### ISSUE TITLE
Add pref to enable/disable dev models

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#104]
Following the introduction of `modelType` property [here](https://github.com/mozilla/firefox-translations/pull/103/files), I propose adding a preference to explicitly enable or disable the usage of low-quality models (test models).  Something like "Enable test models".

We'll need to filter available language pairs based on the `modelType` if this pref is disabled.

Most of those models are not really usable but still useful for testing purposes. We can make a decision on what models are prod or dev based on evaluation numbers and human feedback and then change it in the storage. The change will be propagated to the extension after registry updating.

I assume we will use only high-quality models for the experiment but all models for debugging and informal testing.

**Comment by andrenatal** [comment]
We can display a warning in the infobar, maybe in the dropdown?

**Comment by eu9ene** [comment]
> We can display a warning in the infobar, maybe in the dropdown?

Yes, we can. It would be another way of communicating the expected difference in quality to users.
