### ISSUE TITLE
Extension gets disabled after restarting Firefox

### ISSUE THREAD

**Issue by abhi-agg** [mozilla/firefox-translations#128]
Filing this one to not forget what @flodolo reported as per https://github.com/mozilla/firefox-translations/pull/123#issuecomment-1050184058

**Comment by flodolo** [comment]
Not a developer, but this seems relevant?
https://searchfox.org/mozilla-central/source/browser/components/BrowserGlue.jsm#2092

**Comment by abhi-agg** [comment]
@flodolo I couldn't make the extension run in a new profile https://github.com/mozilla/firefox-translations/issues/129. So, I couldn't reach the point where the extension was working fine and after restarting the browser it stopped working.

**Comment by andrenatal** [comment]
So this is happening due the conflict with the legacy in-tree extension like @flodolo well noticed. We'll have that occasionally removed, but #137 fixes this right away by changing the addon id of the xpi, which we should't touch anymore.

**Comment by abhi-agg** [comment]
Tested with the latest README instructions on a clean Firefox profile. The extension works very well.
