### ISSUE TITLE
Extension cannot be re-enabled on a website if accidentally clicking “Never translate this site”

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#139]
Description:
Accidentally selecting the “Never translate this site” from the “Options” drop-down menu on the bar will permanently disable the extension on a particular site, with no means of re-enabling it.

Restarting the browser, disabling/re-enabling the extension from Add-ons Manager or uninstalling/re-installing the extension, do not work.

The only way to make the bar appear again on that particular site is to create a new profile and install the extension once more.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access, for example, https://es.wikipedia.org/wiki/Wikipedia:Portada
3. Notice the translation bar appears
4. From the “Options” drop-down menu on the bar, select “Never translate this site”
5. Notice the bar disappears i.e. the extension is disabled on this particular website with no means of re-enabling it

Actual:
Selecting “Never translate this site” will permanently disable the extension on a particular website. 
The only method to re-enable it once more is to create a new profile and install the extension anew.

Expected:
The extension should have an options page (in the extension detail page from Add-ons Manager for example) where a “whitelist” section is present. Users should be able to add or remove particular websites from this “whitelist” in order to have more control over which websites the translation bar appears on.
Ultimately, this “whitelist” section can be used to reverse an accidental click on “Never translate this site” by removing the affected website from the list.

**Comment by acornestean** [comment]
Actually, I ignored the fact that the extension will be built-in and an options page would not be feasible. 
Still a way to make the bar appear again and give the user a chance to undo this mistake would be good. The past implementation of having an icon in the address bar with which the infobar can be shown/hidden on command would work well.

**Comment by andrenatal** [comment]
In theory the way the original extension developed years ago handles this was by using the about:preferences panel, but its display is being controlled by the `extensions.translations.disabled` flag iirc (I implemented that one year ago). I'll need to revisit that when I remove the legacy extension on #138

**Comment by acornestean** [comment]
Quick update.

The same issue occurs when selecting “Never translate <<X language>>” from the “Options” menu on the infobar. 

There is no way to bring the infobar back on websites in that language. Restarting the browser, disabling/re-enabling the extension from Add-ons Manager or uninstalling/re-installing the extension, do not work.

**Comment by andrenatal** [comment]
This will be fully sorted only when we remove the legacy extension and have the `extensions.translations.disabled` pref properly governing the panel preferences.

**Comment by acornestean** [comment]
With the latest version of the extension, the infobar can be shown again by clicking on the page action at the right end of the address bar if a user has accidentally selected “Never translate this site” or “Never translate <>” from the “Options” menu on the infobar.
