### ISSUE TITLE
Extension erroneously identifies Norwegian nynorsk as Norwegian bokmål

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#140]
Description:
The extension infobar wronlgy identifies a Norwegian nynorsk Wiki page as Norwegian bokmål.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access a Wikipedia page, for example, https://es.wikipedia.org/wiki/Wikipedia:Portada
3. From the left sidebar, identify and click on Norsk nynorsk
4. Notice the Norwegian nynorsk page loads (as also identified by the “nn” in the URL - https://nn.wikipedia.org/wiki/Hovudside)
5. Notice the infobar appears and wrongly identifies the page language as Norwegian bokmål
6. Click on the browser “back” button to return to the page from Step 2.
7. From the left sidebar, identify and click on Norsk bokmål
8. Notice the Norwegian bokmål page loads (as also identified by the “no” in the URL - https://no.wikipedia.org/wiki/Portal:Forside)
9. Notice the infobar appears and correctly identifies the page language as Norwegian bokmål

Actual:
The extension infobar wronlgy identifies a Norwegian nynorsk Wiki page as Norwegian bokmål.

Expected:
The extension should correctly identify the Norwegian nynorsk page as such.

![2022-03-03_15h45_06](https://user-images.githubusercontent.com/50236075/156577504-e728f589-1390-44f6-b954-664c46405cef.png)

**Comment by kpu** [comment]
Suggested fix: https://github.com/mozilla/firefox-translations/issues/30#issuecomment-1038915130

**Comment by acornestean** [comment]
With the latest version of the extension, Norwegian nynorsk pages are properly identified as such by the infobar.

For example, https://nn.wikipedia.org/wiki/Vatikanstaten, a page in Norwegian nynorsk, will be properly identified as such, confirming the fix. For further details, see the attached screenshot. 

![2022-03-11_11h34_11](https://user-images.githubusercontent.com/50236075/157841113-6a53f615-5752-4085-b8b5-52a095650cca.png)
