### ISSUE TITLE
Issues with the infobar not being displayed due race condition still persist

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#145]

**Comment by andrenatal** [comment]
@acornestean can you please test this one again, this latest patch should have fixed it permanently

**Comment by acornestean** [comment]
@andrenatal 

Used the artifact from https://github.com/mozilla/firefox-translations/actions/runs/2068529446 on Wikipedia with several languages (ES, IT, DE, RU, PT, nb-NO, ET) and it seems the issue no longer occurs i.e. the infobar is displayed each time a page is loaded. This was from about ~20 accessed pages on each language.

I’ve also checked the extension downloadable from https://github.com/mozilla/firefox-translations#testing on the same languages on Wikipedia, as I wasn’t sure the changes where merged to main and if the artifact mentioned above is the same as the extension from here – https://github.com/mozilla/firefox-translations#testing. So I wanted to double check.
With the one from https://github.com/mozilla/firefox-translations#testing I did stumble upon a few pages where the infobar did not show up – 1 maybe 2 pages from about 20 accessed. 

See the screenshots for more details. Note that the extension from https://github.com/mozilla/firefox-translations#testing is on the left and the artifact is on the right.

![2022-03-31_11h30_59](https://user-images.githubusercontent.com/50236075/161012941-f83fc91e-88b1-4169-9862-a39e61851939.png)

![2022-03-31_11h32_33](https://user-images.githubusercontent.com/50236075/161012987-f56a8e93-9f9b-416d-893b-e2432c2bb823.png)

**Comment by andrenatal** [comment]
Same as #174, we need to make sure your Nightly artifact is the latest
version.

**Comment by acornestean** [comment]
Using the latest Nightly downloaded from https://github.com/mozilla/firefox-translations#nightly-builds on Wikipedia with several languages (ES, IT, DE, BG, RU, PT, nb-NO, ET), the issue no longer occurs. The infobar is displayed without fail each time a page is loaded. Tested around ~30 pages per language.
