### ISSUE TITLE
Incorporate the survey in the user flow

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#159]

**Comment by eu9ene** [comment]
Actually, why do we need localization? A user can use Firefox Translations to fill it! :) We can add a hint to enable translation of forms too.

**Comment by ChrisBurnsOneOne** [comment]
Andre, please do not action this until I've had the opportunity to discuss further.

**Comment by andrenatal** [comment]
@ChrisBurnsOneOne ok, how do you want to do it? Do you want to have a meeting?

**Comment by ChrisBurnsOneOne** [comment]
Briefly, yes - I want to re-check the survey contents - it's been  a while - and run it by Robin to ensure he's happy with what's happening too. I'm available all day tomorrow and Thursday (GMT)  up to the usual fortnightly meeting. Email me with a time that works for you.

**Comment by andrenatal** [comment]
Maybe is better if you review the survey first. We used the one you shared with me.

**Comment by ChrisBurnsOneOne** [comment]
This is what I want to confirm because I'll need to dig it out to check. I'll email you.

**Comment by andrenatal** [comment]
I've just sent it to you

**Comment by ChrisBurnsOneOne** [comment]
OK, I see. As we'll only have one pass at this : 

- Question 6 from that link is redundant and can be removed (requesting email addresses for further use)

- I'd like to add another questionnaire, with 12 items. They're scored on a similar 7-point rating scale, where one is "do not agree" and 7 is "strongly agree :

1. The system is deceptive
2. The system behaves in an underhanded manner
3. I am suspicious of the system’s intent, actions, or output
4. I am wary of the system
5. The system’s actions will have a harmful or injurious outcome
6. I am confident in the system
7. The system provides security
8. The system has integrity
9. The system is dependable
10. The system is reliable
11. I can trust the system
12. I am familiar with the system

Lastly, can you confirm what telemetry you'll be collecting from Firefox itself ?

**Comment by kpu** [comment]
> Actually, why do we need localization? A user can use Firefox Translations to fill it! :) We can add a hint to enable translation of forms too.

The goal of the survey is to collect unbiased feedback (or at least feedback biased by who feels like taking a survey).  Making use of the tool a prerequisite for taking the survey would bias the results.

**Comment by eu9ene** [comment]
@ChrisBurnsOneOne @kpu we have to make a decision ASAP if you want this feature in the experiment. Localization of the user message through pontoon might take some time and we still don't know what questions we have and what platform to use. It's also not clear how to perform the localization of the survey itself. We could add questions to pontoon too probably. I suggest simplifying the questionnaire to something like a couple of scores and one-two text areas to hear about the overall experience, otherwise, it's unlikely that users will participate in a long survey.

**Comment by eu9ene** [comment]
This is the full list of included telemetry: https://github.com/mozilla/firefox-translations/blob/main/extension/model/telemetry/metrics.yaml. The survey will not be a part of telemetry. It will be a link to an external platform, either google form or something else more advanced, but we're out of time to add this link before code freeze.

**Comment by eu9ene** [comment]
Also, the survey will be anonymous and there will be no intersection between the survey and telemetry. It is against Mozilla's privacy policy. Telemetry will collect only technical and interaction level metrics and free text fields do not qualify.

**Comment by ChrisBurnsOneOne** [comment]
How many users will the survey be sent out to ? Also, how will they be chosen ?

**Comment by ChrisBurnsOneOne** [comment]
Previously we were told it'd be offered to around 10,000 users, and we could expect a completion rate of 3-5%. That would be sufficient.

**Comment by eu9ene** [comment]
@ChrisBurnsOneOne please take a look https://qsurvey.mozilla.com/s3/Firefox-Translations

We'll do the survey on Alchemer platform that is used by Mozilla. Data will be dumped as csv in the end.
We hope that Mozilla user research localization team will help us with translations.

**Comment by ChrisBurnsOneOne** [comment]
I see. I assume there's no way to have more than one question on each page ? I think this is why you expect completion rates to be very low.

**Comment by eu9ene** [comment]
@ChrisBurnsOneOne ok, I'm sending it for localization then. I also tried it on iOS and it looks pretty usable to me. I don't think there is space on the screen to answer more than one question
