### ISSUE TITLE
Dump of Ukranian-centric models

### ISSUE THREAD

**Issue by kpu** [mozilla/firefox-translations#166]
A dump of models from Helsinki: https://github.com/Helsinki-NLP/UkrainianLT/blob/main/translateLocally-models.json

"Additional ones are on the way. The quality might be a bit questionable but it is hard for me to judge."

These have some languages where we don't have en support yet, need to revise the pivoting assumptions.

**Comment by eu9ene** [comment]
We should add en <-> ukr, but not sure about the others. So far our strategy was to have en <-> <lang> models and to support other language pairs through pivoting. It's also easier to access quality this way.

**Comment by andrenatal** [comment]
ok, let's do this way

**Comment by eu9ene** [comment]
I checked the quality of uk -> en in [opus-mt-app](https://github.com/Helsinki-NLP/OPUS-MT-app/) and it looks decent. Those models produce separated dictionaries for source and target languages, so the issue is that the extension supports only one mixed dictionary for both languages. So, we have to change the structure of our model registry to be able to use separate dictionaries.

**Comment by kpu** [comment]
> I checked the quality of uk -> en in [opus-mt-app](https://github.com/Helsinki-NLP/OPUS-MT-app/) and it looks decent. Those models produce separate vocabularies for source and target languages, so the issue is that the extension supports only one mixed vocabulary for both languages. So, we have to change the structure of our model registry to be able to use separate vocabularies.

Indeed https://translatelocally.com/web/

**Comment by eu9ene** [comment]
Oh, nice, we have a similar page https://mozilla.github.io/translate/, more demos to the world! :) So it feels like it's worth the effort to add this support to be able to integrate these and future models. Especially if opus folks will decide to run their massive automatic training.

**Comment by eu9ene** [comment]
Also, those models are `gemm-precision: int8`, I guess they were created using marian master based on https://github.com/browsermt/students/tree/master/train-student#marian-master-slower. They are supposedly slower.  Should we add support of such models to the extension?

**Comment by abhi-agg** [comment]
> Those models produce separate vocabularies for source and target languages, so the issue is that the extension supports only one mixed vocabulary for both languages. So, we have to change the structure of our model registry to be able to use separate vocabularies.

marian [supports this use case already](https://marian-nmt.github.io/docs/). So, I am assuming that the engine (aka bergamot-translator) will work as well as it is built on top of marian. However, we just need to test the engine for this use case just to be sure and then make changes in the extension (which I believe would be easy).

> Also, those models are `gemm-precision: int8`, I guess they were created using marian master based on https://github.com/browsermt/students/tree/master/train-student#marian-master-slower. They are supposedly slower. Should we add support of such models to the extension?

It is technically possible by providing a model config for each language pair. Right now, we are using a global model config for all language pairs.

**Comment by jerinphilip** [comment]
@abhi-agg Possibly related: https://github.com/browsermt/marian-dev/issues/81

**Comment by jelmervdl** [comment]
The [demo page Kenneth posted](https://translatelocally.com/web/) is just the bergamot-translator wasm test page [with some tweaks](https://github.com/browsermt/bergamot-translator/commit/4cfb44cda703238174e41a367bbd762d341a703b).

**Comment by abhi-agg** [comment]
Just a heads up to everyone. If this requires landing stuff in gecko (being discussed in https://github.com/browsermt/marian-dev/issues/81#issuecomment-1079171876) then we can't achieve it by end of next week.

**Comment by andrenatal** [comment]
If this depends on touching gecko, forget about it then, it's just too late and I don't want to even think of risking opening another can of worms.

**Comment by eu9ene** [comment]
I agree we can think about it later. Adding those models requires updating too many parts: model registry and repo format, evaluation scripts, loading scripts in the extension and other places (translate website, HTTP service) + now maybe some work in gecko. We should do it at some point, especially if more models with the same format will be available.

**Comment by andrenatal** [comment]
Forget it then.
