### ISSUE TITLE
Automatic updates of model registry

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#168]
### Proposal

I expect new and updated models to pop up more often. There are our retraining efforts, the consortium is training new models and some third-party organizations also do training for TranslateLocally (see #166).  I propose to create a mechanism to not update the extension every time a new model is available in the model [repo](https://github.com/mozilla/firefox-translations-models). This will allow us to sign the extension once and not think about the updates. The model repo will still need to be updated manually. This will allow us to have full control over this process including performing automatic evaluation and CI checking that the models are not broken.

#### Implementation
We should store the model [registry](https://github.com/mozilla/firefox-translations-models/blob/main/registry.json) on GCP in the same way we store the models. This is a content script, so we can reload it at the same time as mediator.js is loaded (on tab opening) to have up-to-date model metadata. We can think of it as an external script on CDN. 

We'll need to invalidate the model cache if a model was updated. 

We'll also need to report the registry version in telemetry to understand what model was used.

#### Cocerns
The main question here is security. Is it secure enough to download the registry that contains hash sums of the models from somewhere?

QA will be a bit more complicated because models in the same extension version might change.

**Comment by eu9ene** [comment]
Let's push this out of schedule too. This is a nice-to-have new feature that still requires redesigning the model repo and the extension to be able to reload the model registry in the background script (modelRegistry is a content script now). Also, QA of a specific extension version will be less deterministic. We can definitely pursue this later when it will be clear that extension update is a long process and new models are coming pretty often.

**Comment by marco-c** [comment]
We are using Remote Settings in the built-in version to achieve this.
