### ISSUE TITLE
Two infobars at the same time

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#174]
1. Go to any page to translate
2. Quickly click on translation icon in URL bar before infobar has appeared automatically

Expected:
- one infobar

Actual
- two infobars

<img width="1621" alt="Screen Shot 2022-03-24 at 1 17 00 PM" src="https://user-images.githubusercontent.com/2486505/160029258-2f3f74f7-0f71-4eee-8093-d9fd1e6a2379.png">

**Comment by pdehaan** [comment]
I'm seeing the same thing currently on https://www.mozilla.org/de/ (on my Apple M1 rMBP). I think it's due to the empty language dropdown value. If I refresh the page a couple times and the language auto-detects as German, I cannot seem to get the second menubar to appear.

![Screen Shot 2022-03-30 at 12 49 11 PM](https://user-images.githubusercontent.com/557895/160918814-43cda880-10e1-44df-a814-e2776e27480f.png)

**Comment by eu9ene** [comment]
I tried to refresh and click on the icon actively and it doesn't lead to two info bars. But I'm able to break it at some point so that no infobar appears. Just constantly pressing F5, it's probably a different issue. Maybe too extreme a use case.

**Comment by acornestean** [comment]
Using the artifact from https://github.com/mozilla/firefox-translations/actions/runs/2068529446 I do not seem able to make the second infobar appear using the STR from eu9ene.

With the extension downloadable from https://github.com/mozilla/firefox-translations#testing it’s still reproducible.

See screenshot below. Note that the extension from https://github.com/mozilla/firefox-translations#testing is on the left and the artifact is on the right.

![2022-03-31_11h40_50](https://user-images.githubusercontent.com/50236075/161015516-f4ed9108-b2c1-4ac6-a81c-95f840c2e753.png)

**Comment by andrenatal** [comment]
Yeah, I confirm that the latest Nightly didn't build with the current tip of main:  https://github.com/mozilla/firefox-translations/releases, so that's why you couldn't reproduce the fixes in there @acornestean.

**Comment by andrenatal** [comment]
@acornestean I've manually triggered the job and now Nightly contains the latest code. Maybe you want to try again? Thanks!

**Comment by acornestean** [comment]
Using the latest Nightly downloaded from https://github.com/mozilla/firefox-translations#nightly-builds and the same STR as before, I cannot make the second infobar appear anymore.

The issue is fixed.
