### ISSUE TITLE
Report Firefox channel in telemetry

### ISSUE THREAD

**Issue by abhi-agg** [mozilla/firefox-translations#195]
We need the capability in the web-extension to detect the Firefox environment (i.e. Nightly vs Release channel) it is running on.

This is available in `about:telemetry#general-data-tab` -> `application.channel` field.

**Comment by abhi-agg** [comment]
I had created this issue thinking that it will be needed for https://github.com/mozilla/firefox-translations/issues/184 but I found a way to resolve https://github.com/mozilla/firefox-translations/issues/184 without needing this.

I am closing this issue. Please feel free to reopen if there is any value in collecting this info just for telemetry purposes.

**Comment by eu9ene** [comment]
We still need to report channel in telemetry if it's possible
