### ISSUE TITLE
Regression on russian

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#198]
We noticed some russian websites stopped detecting the language. Needs more investigation. 

Tested on: https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0

**Comment by eu9ene** [comment]
creation of a new firefox profile solved the issue, not sure what was the problem

**Comment by andrenatal** [comment]
Profiles can become messed when one is developing and using the same browser frequently.
