### ISSUE TITLE
Survey button label isn't properly rendered when manually summoning the infobar

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#199]

**Comment by andrenatal** [comment]
![Screen Shot 2022-03-30 at 2 40 45 PM](https://user-images.githubusercontent.com/973388/160935600-22a27de2-d444-476f-8952-6e727abfb099.png)

**Comment by acornestean** [comment]
Retested with the latest Nightly downloaded from https://github.com/mozilla/firefox-translations#nightly-builds with several different locale browsers. 

The survey button label is properly displayed after closing and manually re-opening the infobar.
