### ISSUE TITLE
Infobar not showing and general issues on browser with Icelandic locale

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#210]
Description:
1. The infobar does not automatically show up when accessing websites on a browser with Icelandic locale.
2. Clicking the address bar button will make the infobar appear however it’s entirely non-functional, cannot be closed and content is missing (missing icon, blank language selection dropdown, missing labels, missing Options entries, etc).
3. Clicking the address bar button again will create another infobar. This can be repeated indefinitely.

**The issue does not occur on other locales.**

Pre-requisites:
1. Install the latest Icelandic locale Nightly.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access https://en.wikipedia.org/wiki/Main_Page
3. Notice the infobar is not automatically shown
4. Click on the address bar button. Notice the infobar is shown but it’s missing content, labels, icon, etc.
5. Click on any infobar button. Notice the buttons don’t work.
6. Try to close the infobar. Notice it can’t be closed
7. Click on the address bar button several times. Notice another infobar is shown each time the button is clicked.

Actual:
On an Icelandic locale browser:
1. The infobar does not automatically show up when accessing websites
2. Clicking the address bar button will make the infobar appear however it’s entirely non-functional, cannot be closed and content is missing (missing icon, blank language selection dropdown, missing labels, missing Options entries, etc).
3. Clicking the address bar button again will create another infobar.

Expected:
1. The infobar should show automatically when accessing websites in supported languages.
2. It should be completely functional and not have missing content (such as icon, labels, etc.).
3. A infobar should not be displayed each time the address bar button is clicked.

https://user-images.githubusercontent.com/50236075/161708984-2f882477-b787-4de1-84e1-c6859e1a3229.mp4

**Comment by acornestean** [comment]
Update: Issue occurs in the exact same manner on Norwegian Bokmål and Norwegian Nynorsk locales.

**Comment by andrenatal** [comment]
This is happening because we don’t have the `enis` model, at least is not present in modelRegistry. @eu9ene Please refresh my memory: We don't have that model because the consortium never trained it?

**Comment by eu9ene** [comment]
Those locales are not supported. Some models are trained only in one direction (see https://github.com/mozilla/firefox-translations-models#currently-supported-languages). @andrenatal yes, we took some experimental models from https://data.statmt.org/bergamot/models/ because they are still useful for testing, but they can be of low quality and trained to translate only to English.

**Comment by acornestean** [comment]
Verified with the latest version of the extension on Icelandic, Norvegian bokmal and Norvegian nynorsk locale Nightlies.

Neither the infobar, nor the address bar extension button are displayed anymore since these locales are not supported, confirming the fix as per #219.
