### ISSUE TITLE
Assesss the utilization of alarms instead of setTimeout on bgscripts on telemetry and sentry

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#225]

**Comment by eu9ene** [comment]
I tested retries in PingSender even with all tabs closed and they work. There is also this [answer](https://discourse.mozilla.org/t/alarms-and-settimeout-setinterval-in-background-scripts/36662) that says: 
>setTimeout and setInterval will work just fine in Firefox. That part of the documentation refers to “event” background pages, which chrome would like to be the default, while in Firefox background pages are by default “persistent”, so always loaded.

Alarms API is not convenient to use and we don't use those timers for any critical functionality so I this it's fine to leave it as is.

**Comment by andrenatal** [comment]
Great, let's close this then.
