### ISSUE TITLE
Translations mis-identifies page language

### ISSUE THREAD

**Issue by yoasif** [mozilla/firefox-translations#240]
On https://ariadne.space/2022/01/22/the-fsfs-relationship-with-firmware-is-harmful-to-free-software-users/ Firefox translations identifies the page as being in Spanish, and offers to translate the page for me. 

The page is in English.

**Comment by kpu** [comment]
The first comment is a gigantic block of Spanish text.  So really the issue is handling multilingual pages.

**Comment by rebecca-burwei** [comment]
Another example is the login screen for sso.mozilla.com . Mine is in English, and Translations identifies it at Italian.

**Comment by bjherbison** [comment]
This is probably mentioned in some other issue (submitted through Foxfooding) but I have two short pages where one identifies as Spanish and the other doesn't. The difference is a colon (":") in the page that identifies as Spanish.
https://herbison.com/NotSpanish.html

**Comment by andrenatal** [comment]
I was able to reproduce all the issues listed above and https://github.com/mozilla/firefox-translations/pull/416 fixes all them
