### ISSUE TITLE
Toolbar has a couple UI issues on browsers that are <1240px

### ISSUE THREAD

**Issue by pdehaan** [mozilla/firefox-translations#245]
### STR
1. Install latest XPI from https://github.com/mozilla/firefox-translations/releases/download/nightly/firefox_translations.xpi into Nightly.
2. Resize your browser.

### ACTUAL RESULTS

<img width="1327" alt="Screen Shot 2022-04-11 at 6 54 44 PM" src="https://user-images.githubusercontent.com/557895/162863645-1a3bb8af-dc36-438d-82ee-924b487aa7d1.png">

**Figure 1:** Nightly at ~1240px wide.

---

<img width="1290" alt="Screen Shot 2022-04-11 at 6 59 22 PM" src="https://user-images.githubusercontent.com/557895/162863779-883d7e0e-2eb8-4e6a-8b91-7871bd83baa0.png">

**Figure 2:** At around 1200px wide, you lose the "&times;" button in the Translations toolbar.

---

<img width="1242" alt="Screen Shot 2022-04-11 at 7 00 55 PM" src="https://user-images.githubusercontent.com/557895/162863937-bff41dbd-7efe-4859-bcfc-d327e945af77.png">

**Figure 3:** At around 1110px wide, you lose the "Options" menubar button.

---

<img width="1089" alt="Screen Shot 2022-04-11 at 7 01 59 PM" src="https://user-images.githubusercontent.com/557895/162864098-9d091fe5-7840-4016-8502-15f76723946c.png">

**Figure 4:** At around 960px wide, you lose the "Participate in survey" button.

---

<img width="863" alt="Screen Shot 2022-04-11 at 7 03 35 PM" src="https://user-images.githubusercontent.com/557895/162864228-66be38c1-4917-423e-95fa-25be85259eb3.png">

**Figure 5:** At around 774px wide, you lose the "Enable quality estimation" checkbox.

---

Not sure if there are a few "easy wins" for elements we can remove from the toolbar, to save some space. Or if there are some options we can move out of the toolbar to save space so the &times; button is always visible.

**Comment by andrenatal** [comment]
Thanks @pdehaan . Yeah, this UI situation is well-known but we probably won't be able to fix that before foxfooding. Unless we find a way to maybe resize the notificationBox?

**Comment by pdehaan** [comment]
If we still have time, maybe we can remove the "Translate this page?" label since it doesn't really add a lot of benefit next to the big blue "Translate" button (and might save us 100px).

**Comment by andrenatal** [comment]
That's a great catch @pdehaan , that label is totally redundant. It doesn't fix this issue, but PR is up!

**Comment by jcchuang** [comment]
This might have been solved already... 

Just FYI, after I click on the "Translate" button, more elements got added to the toolbar (e.g., "Translate this tab automatically...") and the "Participate in survey" button is pushed even further to the right. On my laptop, I need to widen my window to over 1285px in width, in order to see the leftmost edge of the survey button.

<img width="1369" alt="Screen Shot 2022-04-13 at 5 14 58 PM" src="https://user-images.githubusercontent.com/577485/163272723-e72c5378-c1c5-45dc-b5fc-c250eacbd09f.png">

**Comment by pdehaan** [comment]
yeah, I think my concern would be is the &times; button always visible on a smaller 13" MacBook Air.
I can never remember how retina displays work: https://www.apple.com/ca/macbook-air/specs/

My 2021 16" rMBP has an alleged 3556-by-2234px resolution @ 254px per inch. If I go into System Preferences and select Displays and then try and change my resolution and hover over the little samples, I can see the "Default" resolution is a bizarre 1728 &times; 1117px (per the alt text). So the resolution seems to be half the actual reported resolution (because retina). At the other end of the spectrum (Larger Text), the resolution drops to 1168 &times; 755px. If I go to "More Space" option, the resolution increases to 2056 &times; 1329.

If we look at a [14" rMBP](https://www.apple.com/ca/macbook-pro-14-and-16/specs/), the resolution for the 14.2" screen is 3024-by-1964px (or presumably 1512-by-982px using default retina display).

And the 13.3" [MacBook Air](https://www.apple.com/ca/macbook-air/specs/) has a reported resolution of 2560-by-1600px, so maybe roughly 1280-by-800px when retina'ed.

The last two are just good guesses since I don't have a 13" MacBook Air available to test on.

**Comment by andrenatal** [comment]
I've tested on my macbook air 13 and it worked fine.

**Comment by plwt** [comment]
I am seeing this on my laptop - Debian 11, 14", 1600 x 900

**Comment by riveravaldez** [comment]
Hi, not sure if relevant, but in my case (Firefox on Arch Linux) even after resizing the window so Translate's close button (X) appears on screen, clicking on it does nothing.

**Comment by plwt** [comment]
@riveravaldez - I think what you are seeing might be https://github.com/mozilla/firefox-translations/issues/306

**Comment by andrenatal** [comment]
What we need to do here is to make the notificationBox responsive. I'm seeing other implementations able to adjust like this case for a tutorial about how to use tab reopening [1] [2], but I couldn't find the right implementation on gecko-dev to replicate in our extension.

@Rob--W do you know where we can find a reference about how they did that?


[1]
<img width="1589" alt="Screen Shot 2022-06-14 at 12 02 16 AM" src="https://user-images.githubusercontent.com/973388/173514629-58be9b67-43ea-42ab-a16d-01fac48b3935.png">

[2]
<img width="457" alt="Screen Shot 2022-06-14 at 12 02 24 AM" src="https://user-images.githubusercontent.com/973388/173514633-d59297da-42a8-4a70-89ac-c00934777c31.png">

**Comment by Rob--W** [comment]
> What we need to do here is to make the notificationBox responsive. I'm seeing other implementations able to adjust like this case for a tutorial about how to use tab reopening [1] [2], but I couldn't find the right implementation on gecko-dev to replicate in our extension.
> 
> @Rob--W do you know where we can find a reference about how they did that?

The example that you're pointing to ([source](https://searchfox.org/mozilla-central/rev/2398ab33adcea896838b3da678ff6480dbb98b9a/browser/components/BrowserGlue.jsm#4356-4392)) is using the default `notification` element (including [its markup](https://searchfox.org/mozilla-central/rev/2398ab33adcea896838b3da678ff6480dbb98b9a/toolkit/content/widgets/notificationbox.js#413-423)). I note that everything with variable-size content has the flex attribute set, which is probably causing the desired flexbox behavior (documentation: [XUL flex attribute](https://web.archive.org/web/20200811075812/https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/Attribute/flex)).

The [markup for the custom notification from this repo](https://github.com/mozilla/firefox-translations/blob/4be46609f41bbce739f1eadbd935d29a192b59fa/extension/view/js/translation-notification-fxtranslations.js#L14-L52) has `flex` in some places (possibly copied from somewhere), but there are still plenty of (localized) values whose element are not flexible.

**Comment by andrenatal** [comment]
I've noticed the flex attribute and played with it before but it didn't have any effect. I tried adding the markup from the bar aforementioned [1] but still didn't work [2]. 


[1] https://github.com/mozilla/firefox-translations/pull/407

[2]

<img width="450" alt="Screen Shot 2022-06-15 at 11 28 35 PM" src="https://user-images.githubusercontent.com/973388/174005896-79743eb6-e4b5-4dd4-8ab6-b3f2dab1f36c.png">

**Comment by julianfairfax** [comment]
> This might have been solved already...
> 
> Just FYI, after I click on the "Translate" button, more elements got added to the toolbar (e.g., "Translate this tab automatically...") and the "Participate in survey" button is pushed even further to the right. On my laptop, I need to widen my window to over 1285px in width, in order to see the leftmost edge of the survey button.
> 
> <img alt="Screen Shot 2022-04-13 at 5 14 58 PM" width="1369" src="https://user-images.githubusercontent.com/577485/163272723-e72c5378-c1c5-45dc-b5fc-c250eacbd09f.png">

This also breaks the rest of the right side of the window since everything is pushed somehow.

**Comment by cadeyrn** [comment]
> The Survey button seems to have disappeared.

This is intentional, see #431
