### ISSUE TITLE
Using a French browser with english as accepted language, firefox translation should propose english as target

### ISSUE THREAD

**Issue by sylvestre** [mozilla/firefox-translations#249]
As the title says, I am using a browser in French.
Even if we don't support Spanish => French, I should have the Spanish => English proposed to me (as I am accepting English as language in Firefox configuration)

**Comment by andrenatal** [comment]
Thanks @sylvestre . We'll need to use https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages instead of only https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language in order to support your usecase.
