### ISSUE TITLE
Missing enhancements and languages!

### ISSUE THREAD

**Issue by 0xC316c** [mozilla/firefox-translations#253]
I don't know if there is an option for it or not, but it doesn't seem like it has it yet.
If we have "Never translate this site" option in **Options** dropdown menu then why not a "Always translate this site"?

And instead of saying "This page is in", I think it makes more sense to use "Detected".

Also there is no **Turkish** language support, hopefully it'll be in future.

**Comment by andrenatal** [comment]
Hi @0xC316c , we have a very comprehensive tutorial on how to train model for new languages here: https://github.com/mozilla/firefox-translations-training, maybe you want to take a stab on trying to train for Turkish using it?

**Comment by 0xC316c** [comment]
Thank you @andrenatal I will give it a try.

**Comment by marco-c** [comment]
We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
For example, [here's the Turkish request](https://connect.mozilla.org/t5/ideas/support-turkish-translations/idi-p/33413).
