### ISSUE TITLE
L10N: Cannot read the whole French content in the UX

### ISSUE THREAD

**Issue by sylvestre** [mozilla/firefox-translations#259]
Screenshot:
![image](https://user-images.githubusercontent.com/733326/163978555-6a7a22ea-a72a-4231-824c-460466ba7f34.png)
I can only read "Participer au". I think a word is missing (Sondage?)

**Comment by andrenatal** [comment]
Thanks @sylvestre, this is a well known-issue but we hadn't any support from Firefox front-end during the entire course of the project so we ended getting stuck with only this outdated XUL notification bar, which is clearly not responsive neither the most appropriate interface element for this purpose. See #245  :/

A popup + page or browser action that automatically opens when the page is translatable would fit better and that's how chrome does, but an addon can't open the popup programmatically, which needs to be explicitly triggered by a user's action. Don't know if privileged addons can do it though, it might.

**Comment by 0xC316c** [comment]
This is much related to the issues #254 & #245

**Comment by andrenatal** [comment]
Hi @sylvestre, is this happening when your browser window is maximized or only when resized?

**Comment by sylvestre** [comment]
Maximized but it depends on the resolution

**Comment by andrenatal** [comment]
Thanks. So this is a critical UX issue and not an enhancement in contrary to what I expected I'm afraid. After the survey button there's still another the `Options`.  I don't know if we'll be able to solve that in the xul notification bar though.

**Comment by andrenatal** [comment]
Closing this in favor of #254 since it's a duplicate
