### ISSUE TITLE
Can't install this add-on

### ISSUE THREAD

**Issue by 1human** [mozilla/firefox-translations#263]
Please help me. I have already set the xpinstall.signatures.required to false.
But the browser still show me an error: This add-on could not be installed because it has not been verified.
What can I do? 
![Snipaste_2022-04-22_12-46-24](https://user-images.githubusercontent.com/18576031/164604983-fb195340-0c92-4638-8d7b-48a6d14d326d.png)
![Snipaste_2022-04-22_12-45-58](https://user-images.githubusercontent.com/18576031/164604989-b2d8dfc7-51bd-462a-afc0-31bf8a930c45.png)

**Comment by cadeyrn** [comment]
Which version of Firefox do you use? You can't disable the verification in stable release builds of Firefox.

**Comment by andrenatal** [comment]
Hi @1human, I second @cadeyrn (thank you!): this only works in Nightly so far. Can you please confirm the channel you are running?

**Comment by andrenatal** [comment]
I'm closing this because soon we won't need this procedure to install the addon anymore.
