### ISSUE TITLE
Evaluate options to replace Sentry

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#265]

**Comment by eu9ene** [comment]
Here is a PR that removes problematic code https://github.com/mozilla/firefox-translations/pull/269. Let's discuss if it's a viable solution.

**Comment by eu9ene** [comment]
So, based on our discussion I propose removing Sentry from content scripts and just propagating caught errors to bgScript for reporting there.

**Comment by andrenatal** [comment]
@eu9ene Yes, let's do this.
