### ISSUE TITLE
Replacement for unsafe scratch.innerHTML

### ISSUE THREAD

**Issue by Rob--W** [mozilla/firefox-translations#267]
As mentioned during today's review meeting, there is a highly unsafe use of innerHTML that enables script execution at [extension/view/js/InPageTranslation.js#L535-L536](https://github.com/mozilla/firefox-translations/blob/e4fd84ec938df868143aeb5b9161a704d61bd79c/extension/view/js/InPageTranslation.js#L535-L536).

```js
 const scratch = node.cloneNode(false); // shallow clone of parent node 
 scratch.innerHTML = translatedHTML; 
```

To make this safer, the following replacement can be used. There are some caveats, see below.

```js
const nonLiveDomContainer = document.createElement("template");
nonLiveDomContainer.innerHTML = translatedHTML;
const scratch = nonLiveDomContainer.content;
```

In the original code, `scratch` is an `Element` instance, in the new one it's a `DocumentFragment`. They have different interfaces, but the most important one, [`src.childNodes`](https://github.com/mozilla/firefox-translations/blob/e4fd84ec938df868143aeb5b9161a704d61bd79c/extension/view/js/InPageTranslation.js#L580) is supported. It looks like you're [using `src.outerHTML` for debugging](https://github.com/mozilla/firefox-translations/blob/e4fd84ec938df868143aeb5b9161a704d61bd79c/extension/view/js/InPageTranslation.js#L652) which is not available on the DocumentFragment. For debugging, `src.outerHTML ?? src` can be used instead.

I believe that this replacement should be good enough for you, but if you want `scratch` to be an exact copy of the element, then you could concatenate `node.cloneNode(false)`'s start tag with `translatedHTML` before assignment to `nonLiveDomContainer.innerHTML`, and get that node with `nonLiveDomContainer.content.firstChild`.

While the change above fixes the immediate issue with that specific line, an unsafe situation can happen again whenever any part of `scratch` is turned into live DOM, which happens when elements within are appended to the live document. This happens and needs to be resolved (separately) at https://github.com/mozilla/firefox-translations/blob/e4fd84ec938df868143aeb5b9161a704d61bd79c/extension/view/js/InPageTranslation.js#L599

Relevant docs:
- https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

**Comment by Rob--W** [comment]
> In none of those I was able to escalate from the page execution context into the extension execution context.

The threat is not the page escalating to execution in the extension's execution context, but the (remotely fetched) model that outputs a "translation" containing forged/unsafe HTML, which would trigger execution via line 599.

From a very high level, what I am seeing is this:
- page input 
  - extension forwards input
    - (black box) wasm code outputs translation
  - extension returns translation to content script - this translation is tainted, i.e. potentially unsafe
- translation is merged with the page

Because the wasm output is tainted, it cannot safely be used unless it's been validated or sanitized.

To resolve this, the `child`'s HTML needs to be sanitized before insertion.
Without any further context about the potential content, I can only suggest a generic solution that is satisfactory from the security POV, but potentially a suboptimal solution from the functionality/performance POV. The most general quick fix available is to sanitize the HTML before appending the child, e.g. using DOMPurify - https://github.com/cure53/DOMPurify:

```js
  // Instead of: dst.appendChild(child);
  dst.appendChild(DOMPurify.sanitize(elem.outerHTML, {RETURN_DOM_FRAGMENT: true }));
```

Note: to avoid parsing the HTML twice, I configured DOMPurify to return the DocumentFragment (instead of its default type, a string), since `.appendChild` also behaves as desired when a DocumentFragment is passed (i.e. the DocumentFragment's content is appended).

**Comment by kpu** [comment]
> > In none of those I was able to escalate from the page execution context into the extension execution context.
> 
> The threat is not the page escalating to execution in the extension's execution context, but the (remotely fetched) model that outputs a "translation" containing forged/unsafe HTML, which would trigger execution via line 599.
> 
> From a very high level, what I am seeing is this:
> 
>     * page input
>       
>       * extension forwards input
>         
>         * (black box) wasm code outputs translation
>       * extension returns translation to content script - this translation is tainted, i.e. potentially unsafe
> 
>     * translation is merged with the page
> 
> 
> Because the wasm output is tainted, it cannot safely be used unless it's been validated or sanitized.

Here's the HTML escaping in the source code to the wasm module.  My understanding is the compiled form of this is included in the extension now.  

https://github.com/browsermt/bergamot-translator/blob/5ae1b1ebb3fa9a3eabed8a64ca6798154bd486eb/src/translator/html.cpp#L16
https://github.com/browsermt/bergamot-translator/blob/5ae1b1ebb3fa9a3eabed8a64ca6798154bd486eb/src/translator/html.cpp#L169

**Comment by kpu** [comment]
> To resolve this, the `child`'s HTML needs to be sanitized before insertion. Without any further context about the potential content, I can only suggest a generic solution that is satisfactory from the security POV, but potentially a suboptimal solution from the functionality/performance POV. The most general quick fix available is to sanitize the HTML before appending the child, e.g. using DOMPurify - https://github.com/cure53/DOMPurify:
> 
> ```js
>   // Instead of: dst.appendChild(child);
>   dst.appendChild(DOMPurify.sanitize(elem.outerHTML, {RETURN_DOM_FRAGMENT: true }));
> ```
> 
> Note: to avoid parsing the HTML twice, I configured DOMPurify to return the DocumentFragment (instead of its default type, a string), since `.appendChild` also behaves as desired when a DocumentFragment is passed (i.e. the DocumentFragment's content is appended).

This would break javascript code that's associated with inline elements.  All the tags coming back should be exact string-level copies of what came in or quality estimation scores.  If you don't trust that C++ escaper and want to verify that property, dump all the input tags into a hash table and check all the output tags are in the hash table.

**Comment by Rob--W** [comment]
> > Because the wasm output is tainted, it cannot safely be used unless it's been validated or sanitized.
> 
> Here's the HTML escaping in the source code to the wasm module. My understanding is the compiled form of this is included in the extension now.
> 
> https://github.com/browsermt/bergamot-translator/blob/5ae1b1ebb3fa9a3eabed8a64ca6798154bd486eb/src/translator/html.cpp#L16 https://github.com/browsermt/bergamot-translator/blob/5ae1b1ebb3fa9a3eabed8a64ca6798154bd486eb/src/translator/html.cpp#L169

This code is compiled in the wasm binary. Under the threat model where the wasm code is viewed as an untrusted black box, this logic cannot be relied upon.

> This would break javascript code that's associated with inline elements.

If the HTML is unmodified, then that could be a way to address the issue, since it is a.

By "JavaScript code that's associated with inline elements", are you referring to inline event handlers (e.g. `onclick`)? I'd expect that to be less common than broken element references (i.e. web page that uses `element.onclick = ...` or `addEventListener` instead of relying on the inline event attribute for logic).

> All the tags coming back should be exact string-level copies of what came in or quality estimation scores. If you don't trust that C++ escaper and want to verify that property, dump all the input tags into a hash table and check all the output tags are in the hash table.

A reliable validation mechanism would be an acceptable alternative to sanitization.

**Comment by jelmervdl** [comment]
For line 599 using some sanitiser would be fine. This case only triggers for new elements, elements added by bergamot-translator, such as the `<font>` tags used to annotate sentence and token scores. Since those are the only elements that can be legitimately added by the wasm blob, DOMPurify might be a bit overkill. We could implement something that only supports those font tags and 4 attributes, and rejects everything else. If I recall correctly, the wasm blob won't even ever nest these elements, and they will always be leaf nodes (i.e. have no elements themselves)

In all other scenarios, the tag that comes out of the wasm binary _is only used to find the matching tag in the original live DOM_. [If it isn't found, the tag is ignored.](https://github.com/mozilla/firefox-translations/blob/e4fd84ec938df868143aeb5b9161a704d61bd79c/extension/view/js/InPageTranslation.js#L601)

> By "JavaScript code that's associated with inline elements", are you referring to inline event handlers (e.g. onclick)? I'd expect that to be less common than broken element references (i.e. web page that uses element.onclick = ... or addEventListener instead of relying on the inline event attribute for logic).

That's exactly why it is implemented this way.

>  If you don't trust that C++ escaper and want to verify that property, dump all the input tags into a hash table and check all the output tags are in the hash table.

Effectively, what is now implemented is not unlike this: for each fragment of html that is submitted to be translated, the real live DOM fragment is referenced in a table. When the translation comes back, the translated HTML fragment is matched element for element with the live DOM fragment.

**Comment by jelmervdl** [comment]
Without testing, something like this inside line 599:
```js
function validate(node) {
	const allowed = new Set([
		'x-bergamot-sentence-index', 'x-bergamot-sentence-score',
		'x-bergamot-word-score', 'x-bergamot-word-index'
	]);

	if (node.nodeType === Node.ELEMENT_NODE) {
		if (node.nodeName !== 'FONT')
			return false;

		if (!node.getAttributeNames().every(attribute => allowed.has(attribute)))
			return false;

		for (let child of node.childNodes)
			if (!validate(child))
				return false;
	}

	return true;
}
```

**Comment by Rob--W** [comment]
> (Without me having tested this…) would something like this inside line 599 suffice as validation/sanitation?
> ```js
> function validate(node) {
> 	...
> 
> 	if (node.nodeType === Node.ELEMENT_NODE) {
> 		if (node.nodeName !== 'FONT')
> 			return false;
> ```

This early exit is unsafe. Font elements can still have inline event handlers.

Unless you have a good reason not to, I would just recommend the use of DOMPurify.

**Comment by jelmervdl** [comment]
> Unless you have a good reason not to, I would just recommend the use of DOMPurify.

Performance 😅

The translator can insert `<font>` to wrap every subword token (so every 2-3 letters on average, or per letter in the worst case) of all translated text. So while the inserted HTML is not complex, the number of calls that would have to go through DOMPurify would be quite substantial.

**Comment by kpu** [comment]
What's more secure here?  
A. Allow only elements that already existed plus the *exact* font element that can come out.  
B. Allow any element to be injected as long as it doesn't have javascript but can otherwise damage the page with a full overlay on top z-order and change all the links to malicious sites.  

What more meets the availability criterion in information security?
A. Links that used to work still work, including javascript-based links
B. Remove all javascript from the DOM, so random pages break

**Comment by Rob--W** [comment]
> What's more secure here?  
> A. Allow only elements that already existed plus the *exact* font element that can come out.  
> B. Allow any element to be injected as long as it doesn't have javascript but can otherwise damage the page with a full overlay on top z-order and change all the links to malicious sites.  

Obviously A is more secure. Why are you comparing the two? B is not an option under consideration. The two compared options are A and C (=allow any element even if it contains JS).

Side note, even if malicious websites are linked, then the browser's same-origin policy will protect from cross-origin information leakage. With JS in the page itself, not that much.

Moreover, even without any new HTML but only changes to text, a risk to consider is misinformation. The user necessarily needs to trust the extension to output a good faith translation of the source text.

> What more meets the availability criterion in information security?
> A. Links that used to work still work, including javascript-based links
> B. Remove all javascript from the DOM, so random pages break

B is again not being considered: There is not the suggestion to remove all JS from the DOM, only to sanitize new DOM that doesn't have a counterpart in the source.
