### ISSUE TITLE
Cannot download translation model

### ISSUE THREAD

**Issue by badprogramshere** [mozilla/firefox-translations#271]
I'm trying to download the German > English model, but it always seems to fail, resulting in a 'We found an error loading the translation engine' message.

I'm using https://european-union.europa.eu/index_de as a test site, and I get this error in the web console:
`Model 'deen' construction failed: 'The operation is insecure. - getItemFromCacheOrWeb@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/translationWorker.js:447:40
downloadFiles@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/translationWorker.js:425:39
constructTranslationModelHelper/<@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/translationWorker.js:369:89
constructTranslationModelHelper@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/translationWorker.js:369:18
constructTranslationModel@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/translationWorker.js:332:28
loadLanguageModel@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/translationWorker.js:262:26
loadTranslationEngine/initialModule.onRuntimeInitialized<@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/translationWorker.js:76:26
doRun@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/bergamot-translator-worker-without-wormhole.js:2882:50
run@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/bergamot-translator-worker-without-wormhole.js:2894:7
runCaller@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/bergamot-translator-worker-without-wormhole.js:2863:22
removeRunDependency@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/bergamot-translator-worker-without-wormhole.js:429:8
receiveInstance@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/bergamot-translator-worker-without-wormhole.js:514:26
receiveInstantiationResult@moz-extension://d9888e29-9ab3-4c65-b069-d95128925624/controller/translation/bergamot-translator-worker-without-wormhole.js:518:22
'`

**Comment by andrenatal** [comment]
I tried but couldn't reproduce this one. 

<img width="1788" alt="Screen Shot 2022-05-01 at 1 42 11 PM" src="https://user-images.githubusercontent.com/973388/166163858-74ec4cd3-3e6f-4dc8-9b46-653700ae1c63.png">

**Comment by badprogramshere** [comment]
Yeah, I tested this again with a brand-new profile and it now seems to function normally. I did notice another problem, though - I'll make a new issue for that

**Comment by quininer** [comment]
I've noticed that this issue is reproducible in private mode.
