### ISSUE TITLE
Translation bar does not appear again after navigation

### ISSUE THREAD

**Issue by Rob--W** [mozilla/firefox-translations#275]
STR:

1. Visit example.com
2. Click on the pageAction translate button.
    (the toolbar appears)
3. Navigate elsewhere, e.g. by clicking on the link to iana.org
    (the toolbar disappears)
4. Click on the pageAction translate button again.

Expected:
- The translate bar should appear.

Actual:
- The translate bar does not appear.

With a debugger, I see that the logic exists early at:
https://github.com/mozilla/firefox-translations/blob/7230c7f65c3b367d087b31b621bf5cfcbddd22da/extension/controller/experiments/TranslationBar/api.js#L54-L56

The current implementation relies on the infobar X click handler and/or the content script to manage the reference to the infobar:
https://github.com/mozilla/firefox-translations/blob/7230c7f65c3b367d087b31b621bf5cfcbddd22da/extension/controller/experiments/TranslationBar/api.js#L142-L144

... the above logic is fragile, because it prevents the infobar from being shown if the logic ever forgets to close the infobar. I guess that I triggered such a condition with the above STR.

If the intent was to connect the lifetime of the stored toolbar with the actual visibility of the toolbar, then it would make sense to use the notificationBox's callbacks instead of relying on a call to closeInfobar. These callbacks are documented at https://searchfox.org/mozilla-central/rev/a730b83206183bf097820c5780eef0d5e4103b9d/toolkit/content/widgets/notificationbox.js#95-100.

**Comment by kpu** [comment]
I've seen this issue too, not sure if it's the same cause.
