### ISSUE TITLE
containsExcludedNode calls node.querySelector but doesn’t act on the result

### ISSUE THREAD

**Issue by Rob--W** [mozilla/firefox-translations#278]
`containsExcludedNode` calls `node.querySelector` but doesn’t act on the result. Remove it along with [the caller](https://github.com/mozilla/firefox-translations/blob/7230c7f65c3b367d087b31b621bf5cfcbddd22da/extension/view/js/InPageTranslation.js#L408), logic [already taken care of by `isExcludedNode`](https://github.com/mozilla/firefox-translations/blob/7230c7f65c3b367d087b31b621bf5cfcbddd22da/extension/view/js/InPageTranslation.js#L387-L388).

https://github.com/mozilla/firefox-translations/blob/7230c7f65c3b367d087b31b621bf5cfcbddd22da/extension/view/js/InPageTranslation.js#L375-L384

**Comment by Rob--W** [comment]
trivial to fix but no real impact except code readability

**Comment by jelmervdl** [comment]
This bug might cause performance to be worse. `containsExcludedNode` is called from `validateNode` to determine whether an element can be submitted as a single chunk to the translator, or should be split into smaller chunks. With the implication that one big chunk will translate faster (but also more accurately) than many smaller chunks.

**Comment by Rob--W** [comment]
Note: if you decide to fix this by returning a value, then I suggest to not compute the full selector over and over again, but once. This `containsExcludedNode` looks like it's potentially in a hot code path, so minimizing the amount of unnecessary overhead would positively impact performance.

**Comment by Rob--W** [comment]
To closer match the intention of the code, `return !!` should be prepended before the code referenced above (line 382).
This is desirable according to @jelmervdl, but I'll defer the decision on whether to fix this to the owners of this repo.

@andrenatal What's your opinion on what should be happening here? When I try a random Spanish Wikipedia page, I do see differences in the translation: https://es.wikipedia.org/wiki/Invasi%C3%B3n_rusa_de_Ucrania_de_2022

**Comment by Rob--W** [comment]
I'm slapping the block-first-update label on this for visibility. Although it is not strictly necessary to change this, the quality of the translation/result is affected by this mismatch in the intended behavior and the actual behavior. Therefore this issue should be tracked.

**Comment by andrenatal** [comment]
> When I try a random Spanish Wikipedia page, I do see differences in the translation: https://es.wikipedia.org/wiki/Invasi%C3%B3n_rusa_de_Ucrania_de_2022

Hi @Rob--W , sorry could you please elaborate on what you meant by this?

**Comment by Rob--W** [comment]
> > When I try a random Spanish Wikipedia page, I do see differences in the translation: https://es.wikipedia.org/wiki/Invasi%C3%B3n_rusa_de_Ucrania_de_2022
> 
> Hi @Rob--W , sorry could you please elaborate on what you meant by this?

- some words are different
- the table at the right looks different (looks like some whitespace has moved around the `<li>` nodes).
- The external references (e.g. `[1]` in the table at the right) are gone in some cases.

The "some words are different" looks reasonable, since the translation has more context to generate the translation.

These other issues are quality issues that is not directly caused by the `containsExcludedNode` call that I mentioned above, but it could be a sign of a quality/consistency issue when larger DOM subtrees are being translated. I didn't look that closely, but if you want to reproduce, you can easily do so as follows:

1. Load the extension in Firefox.
2. Visit https://es.wikipedia.org/wiki/Invasi%C3%B3n_rusa_de_Ucrania_de_2022 and translate from Spanish (to English).
3. Edit the extension and put `return !!` before line 382 (as suggested in my last comment). This would fix the reported bug (i.e. code matches the intended behavior).
4. Reload the extension.
5. Open the URL from step 2 in a new tab or window, and activate the translation again for that tab.
6. Now use Alt-Tab or Ctrl-Tab to quickly compare the results from step 2 and step 5. The differences are remarkable, and you can use the devtools to inspect the differences in HTML.

**Comment by andrenatal** [comment]
I've tested the suggested change and although I noticed minimal differences to the translation between having and not having it applied, the speed of the translation became noticeably (3x) slower with it, which is very undesirable specially given all the time (2 yrs) we spent to optimize the performance in this project. 

I've recorded a screencast [1] -- notice it takes 3 seconds to translate the first page (without `return !!`),  and 9 seconds to translate the second (with `return !!`).

I'm planning to sync with the latest developments in the parser that @jelmervdl has on their fork after we release, and I can revisit this issue then. With that said, I don't believe this should be a release blocker, neither touched now, given the high risk with little benefit, but an enhancement, which can be addressed when we sync up the branches.

[1] https://www.dropbox.com/s/w024egr86ln97oe/Screen%20Recording%202022-05-19%20at%209.35.19%20PM.mov?dl=0

**Comment by jelmervdl** [comment]
I agree that if there is such a performance regression it should be left out for now.

I also tested the effects of it, and on sites like Wikipedia it has little impact on the main text because even if containsExcludedNode returns true, hasTextNodes is also true and the element is accepted anyway.

I don't know why there is such a negative effect in performance, I didn't see it in my branch.
