### ISSUE TITLE
Ensure that translations are independent when cross-origin/cross-frame data is involved

### ISSUE THREAD

**Issue by Rob--W** [mozilla/firefox-translations#288]
To translate, the current implementation aggregates the source text from all frames from a tab, forwards it to the top-level frame, where a worker is spawned that does the translation, and then the messages are returned to the original frames. Even if #287 is fixed, there is still a possibility of cross-origin data leakage, when the translations are not independent. That is, if the translation engine maintains any state between translations, with the latest translation being informed/derived from data from previous translations, then a cross-origin info leak may occur.

@andrenatal mentioned that there is (or used to be) a cache that supports the translation. If this is indeed the case, the cache should be wiped as soon as the `frameId` of the source text to translate changes.

In general, any origin-specific state should be cleared when the worker processes a translation request from a different frame than before.

**Comment by eu9ene** [comment]
The translation itself is stateless. We use cache only for file downloading (models). Downloading of a new model happens on demand when a new language pair is translated, then it's cached.

**Comment by kpu** [comment]
There is an optional cache in the C++ code.  As to whether you are using it, that's a different question.

**Comment by jelmervdl** [comment]
@Rob--W is right, there is a translation cache in the wasm binary. See translationWorker.js, constructTranslationService, although the translation cache size is pointlessly small. Disabling it entirely as a quick fix won't cause much of a performance difference then.

**Comment by eu9ene** [comment]
Ok, I found that we set cache size for translation service to 10 here https://github.com/mozilla/firefox-translations/blob/7230c7f65c3b367d087b31b621bf5cfcbddd22da/extension/controller/translation/translationWorker.js#L305. 

Translation messages with different frameId can be added to the translation queue in random order, so I don't think we can invalidate the cache in between. We can just disable it.

**Comment by Rob--W** [comment]
If the cache offers any benefit, then you can consider keeping the cache until the first frameId change.

Even if messages were to be processed in an unspecified order, as long as frameId is present when the queue is drained, you'll be able to clear the caches as desired. But if the translation is async with multiple translations running concurrently, then the best that is possible is to disable the cache on the first cross-origin/frame input.

**Comment by kpu** [comment]
The cache is primarily useful in a textbox/outbound translation scenario where the user is making small edits and we want all the other sentences in the box to remain cached.  And all of that would be within-frame.  

If a page has duplicated sentences then those would be cache hits, but these are likely to be short sentences that are cheap to translate.
