### ISSUE TITLE
Cannot close infobar after translating a page

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#306]
Description:
After translating a page, the infobar cannot be closed/dismissed via the “X” button. 

The “X” button is greyed out but still visually reacts to clicks.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access, for example, https://de.wikipedia.org/wiki/Pressefoto_des_Jahres
3. Translate the page
4. Once the translation is complete, attempt to close the infobar by clicking the “X” button at the right side of the bar.
5. Notice the infobar cannot be closed/dismissed

Actual:
The infobar cannot be closed via the “X” button after translating a page

Expected:
The infobar should be dismissable whenever the user chooses to do so.

For more details, see the attached video.

https://user-images.githubusercontent.com/50236075/166416581-c27bfd44-267f-4982-8fc7-5e489ce710dc.mp4

**Comment by andrenatal** [comment]
Maybe this could be related to the changes @Rob--W is applying to the logic around the infobar?

**Comment by andrenatal** [comment]
Disregard the comment above, the X is disabled by the default whenever a translation is in progress, so this is the expected behavior.

**Comment by Rob--W** [comment]
@andrenatal "in progress" suggests that the translation could be complete at some point. Once the translation has commenced, I don't see an option to stop/disable it, other than disabling the add-on.

**Comment by dveditz** [comment]
The "X" never comes back, eveb when the text in the bar says "Elements pending to translate: 0".

**Comment by dveditz** [comment]
Despite my previous comment I don't really want this one "fixed". The add-on has modified the page we need to have some indication of that.

**Comment by andrenatal** [comment]
There's two different things being discussed here: one is the inability to close the infobar while the addon is translating, which is disabled on the grounds of what @dveditz pointed. 

The other discussion is about stopping the automatic translation altogether, which is a different issue, and currently not supported.

**Comment by andrenatal** [comment]
I agree that we should keep the toolbar displayed if a translation happened so the user could know that the page was modified, but we can maybe hide the close button instead of disabling it.

**Comment by acornestean** [comment]
Verified with the latest Nightly 1.1.3.

While a translation is in progress, the “Close” button will be hidden. 

See the attached video for more details.

https://user-images.githubusercontent.com/50236075/176412208-79ceb1a7-ee9f-4ffb-8d7c-e92a1f2747c2.mp4
