### ISSUE TITLE
Cannot opt-out of Private Browsing access

### ISSUE THREAD

**Issue by dveditz** [mozilla/firefox-translations#318]
Most add-ons give a choice of whether the add-on has access to pages in Private Browsing or not. On the about:addons management page Firefox Translations instead says

> Requires Access to Private Windows
> This extension has access to your online activities while private browsing.

Although I likely would have enabled this anyway, saying that an optional feature "requires" access to private browsing with no choice is extremely off-putting. If I didn't know the source of this add-on I would be sure this was a sign of surreptitious data harvesting.

**Comment by andrenatal** [comment]
Thanks for the report Daniel. How that can be sorted out?

**Comment by dveditz** [comment]
I have no idea, I didn't know that was possible! I don't see anything requesting or obviously requiring it in your manifest. Perhaps it's automatic for "experimental" addons? Maybe there's a way to opt-out? Question for @Rob--W I think.

**Comment by Rob--W** [comment]
It's automatic for extensions with a privileged signature. I have filed https://bugzilla.mozilla.org/show_bug.cgi?id=1768434 to consider changing it in Firefox.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
