### ISSUE TITLE
Dynamic text is not translated

### ISSUE THREAD

**Issue by dveditz** [mozilla/firefox-translations#322]
I'm a little confused about how the add-on is supposed to work. The appearance is that it makes a one-time translation pass and then is done, but the text in the translation bar afterwards is contradictory. The first part says "Automatic Translation enabled" which implies it's active, but then "Elements pending to translate: 0" implies it's done.

On the site https://www.el-mexicano.com.mx/ there's a banner at the top updated every few seconds with recent headlines. The one that's showing when you click the translation button gets translated, but then the rest are not (and the original one is untranslated next time it comes around). I don't know if this is a general problem or specific to the way this site is coded, but fwiw Google translate does notice and translate these as they change.

**Comment by jelmervdl** [comment]
That's a bug. It is supposed to translate dynamic elements, but on that page it seems to fail to do that for that top banner.

Taking a quick look at what's happening, it seems like it is the text node that's changing content. That then gets caught by [the textNode specific exception in `startTreeWalker`](https://github.com/mozilla/firefox-translations/blob/ef6ac0d2f127521c6b234519353769970b909296/extension/view/js/InPageTranslation.js#L238) which then ignores it.

What it should do is either translate that text in text mode, or submit the parent element for re-translation.

That could in theory also submit already translated text if the parent element contains multiple text nodes, but I doubt that's very common. [It's what I've been doing](https://github.com/jelmervdl/firefox-translations/blob/b03bf73f54cacd8a68ac6ed4a83988c723e5854e/extension/view/js/InPageTranslation.js#L168-L170) and what seems to work well for this page.
