### ISSUE TITLE
“We found an error loading the translation engine” when attempting to translate a page in Private Browsing

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#324]
Description:
Attempting to translate a page in Private Browsing fails and the infobar displays the “ We found an error loading the translation engine” message.

An error message is also displayed in the web console: 

`Model 'esen' construction failed: 'The operation is insecure. - getItemFromCacheOrWeb@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/translationWorker.js:460:40
downloadFiles@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/translationWorker.js:438:39
constructTranslationModelHelper/<@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/translationWorker.js:382:89
constructTranslationModelHelper@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/translationWorker.js:382:18
constructTranslationModel@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/translationWorker.js:345:28
loadLanguageModel@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/translationWorker.js:273:26
loadTranslationEngine/initialModule.onRuntimeInitialized<@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/translationWorker.js:79:26
doRun@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/bergamot-translator-worker.js:2882:50
run@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/bergamot-translator-worker.js:2894:7
runCaller@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/bergamot-translator-worker.js:2863:22
removeRunDependency@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/bergamot-translator-worker.js:429:8
receiveInstance@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/bergamot-translator-worker.js:514:26
receiveInstantiationResult@moz-extension://7f6c01e5-da66-4b70-84ec-0f8aecf59c76/controller/translation/bergamot-translator-worker.js:518:22`

NOTE:
The same page is translated without issues in Normal Browsing mode.

Steps to reproduce:
1. Install the Firefox Translations extension (I used the latest available Nightly 1.1.1 from https://github.com/mozilla/firefox-translations/releases/tag/nightly)
2. Access the extension detail page from Add-ons Manager and allow the extension to run in “Private Windows”
3. Open a private browsing window and access https://www.volkswagen.es/es.html
4. Notice the infobar is displayed and it correctly identifies the page language (Spanish in this particular case)
5. Click on the “Translate” button on the infobar
6. Observe the infobar displays the “We found an error loading the translation engine” message
7. Open the web console and notice “Model 'esen' construction failed: 'The operation is insecure.   etc.” is logged.

Actual:
Translating pages in Private Browsing fails with “We found an error loading the translation engine” displayed in the infobar.

Expected:
The extension should translate pages in Private Windows.

https://user-images.githubusercontent.com/50236075/167362346-6219c476-e411-456f-99af-5e35ee285287.mp4

**Comment by abhi-agg** [comment]
@acornestean Did you notice this behavior on Firefox Nightly or Firefox Release?

**Comment by acornestean** [comment]
@abhi-agg I ran across this issue while testing on the latest Firefox Nightly where I exclusively checked the extension. I did not test on Firefox Release.

**Comment by abhi-agg** [comment]
Thanks for confirming. I am looking into this issue 👍🏾

**Comment by abhi-agg** [comment]
Found the reason of the failure.

We are using `cache` API which is not available in private mode as per https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage: `Furthermore, because CacheStorage requires file-system access, it may be unavailable in private mode in Firefox.`

Working on fixing it.

**Comment by acornestean** [comment]
Verified the fix using the latest Nightly version of the extension. Translations now succeed as intended in Private Browsing and no error messages are displayed anymore.
