### ISSUE TITLE
It's not clear what "Enable quality estimation" does

### ISSUE THREAD

**Issue by Vinnl** [mozilla/firefox-translations#326]
I ticked "Enable quality estimation", but I don't see an estimate anywhere. Either it's intended for users, in which case it might be placed somewhere more obvious, or it's intended to provide feedback to the developers, in which case that might need to be made more obvious.

The only change I did notice was that the title of a page doesn't get translated, which I was about to report until I found https://github.com/mozilla/firefox-translations/pull/221.

**Comment by kpu** [comment]
The feature seems to be active in that https://es.wikipedia.org/wiki/Campeonato_Femenino_Sub-17_de_la_Concacaf_de_2022 translated from Spanish to English highlights "Goals scored", "Goatma", and "Beaters" in a red background.  The better translations are left as is.  

So the problems are 1) there's no explanation about what the feature does 2) for an easier language like Spanish there's often nothing annotated in page so it seems as though nothing happens. Paging @ChrisBurnsOneOne @rlhill

**Comment by rlhill** [comment]
Any feature should be explained (including expected output) in a non-technical language.  This also goes for any highlighting that then actually appears so it doesn't create confusion or just get ignored.  Similarly, some indicator that a page was translated successfully without problems is also needed, i.e. feedback even if 100% OK.  At this stage are there any quick, pragmatic solutions that can be implemented? Or do you want ideal solutions which may require more complex development (along with time and resources, presumably)?  Anything is better than nothing (at least in this case).

**Comment by kpu** [comment]
Actionable images of UI proposals, even recycled ones, would help @rlhill .  You can find a recent version of the extension in the meeting minutes.

**Comment by ChrisBurnsOneOne** [comment]
We need to paraphrase the technical detail into non-technical terms, as Robin suggests. We should probably consider adding a "what's this ?"-type button for both the initial QE activation prompt, and for any QE text moused-over on the page. That it's possible to mouse-over QE highlighted text should be included in the explanation of what QE does in the plugin.

![image](https://user-images.githubusercontent.com/77743443/167394404-95a53b63-14a2-414c-be0c-2f6d4dccc69d.png)

**Comment by Vinnl** [comment]
If I may offer a suggestion, now that I understand what this feature is supposed to do? You could also consider not showing the checkbox in advance, and only if you detect that there are more than 0 potentially problematic translations, at that point show a notification that that is the case, with a "Show me where" to activate highlights?

(Or even just remove the option altogether. The information is not really actionable to me as a user anyway, and it's often clear which translations aren't great anyway. Although one way to make it actionable, is to allow me to see the original text on e.g. hover.)

**Comment by kpu** [comment]
> If I may offer a suggestion, now that I understand what this feature is supposed to do? You could also consider not showing the checkbox in advance, and only if you detect that there are more than 0 potentially problematic translations, at that point show a notification that that is the case, with a "Show me where" to activate highlights?

On native CPUs the overhead of simple quality estimation is about 1-2% and it would be reasonable to do as you suggest.  The problem is WebAssembly, which already makes translation 10x slower than native, also makes translation with quality estimation a further 2x slower.  Since, as you suggest, many users will not use quality estimation, we didn't want to pay this overhead without explicitly asking the user.  

> (Or even just remove the option altogether. The information is not really actionable to me as a user anyway, and it's often clear which translations aren't great anyway. Although one way to make it actionable, is to allow me to see the original text on e.g. hover.)

Indeed, many people rely on fluency as an indicator of quality: https://aclanthology.org/W18-1803/ .  However, a common failure case in neural machine translation is fluent output that hallucinates a different meaning.

**Comment by ChrisBurnsOneOne** [comment]
There might also be some inconsistency in the presentation. In the example from @kpu some of the text is block-highlighted and underlined while some is only underlined - the "United" in United States vs. "Goals Scored".

![image](https://user-images.githubusercontent.com/77743443/167401111-d7bfc46a-d642-4f73-aa2f-cf537436f38a.png)

One for @andrenatal ?

@Vinnl  : the quality estimation function is also intended to help with translating and filling in forms online in other languages - the "Enable translation of forms" option. As a quick and slightly spurious example, try this page and enter some text in the main text box : https://www.postaonline.cz/trackandtrace
You should see some new functionality for you to try out.

**Comment by kpu** [comment]
And "I" is red underlined but not red background.  Is that word-level QE with underline and and sentence-level QE with background then?  

@Vinnl would you like to open a separate issue regarding your suggestion about "allow me to see the original text on e.g. hover"?

**Comment by jelmervdl** [comment]
That seems to be the case. Bad (sub)words get a squiggly line, bad sentences a background:  https://github.com/mozilla/firefox-translations/blob/ef6ac0d2f127521c6b234519353769970b909296/extension/view/js/InPageTranslation.js#L196-L208

**Comment by ChrisBurnsOneOne** [comment]
Good find. We need a "plain-English" / non-technical interpretation of that for users to view when they're being offered a the option to enable QE.

**Comment by andrenatal** [comment]
> Good find. We need a "plain-English" / non-technical interpretation of that for users to view when they're being offered a the option to enable QE.

Hi @ChrisBurnsOneOne @rlhill @kpu would you please provide such descriptive text of both quality estimation as outbound translation features so we could integrate in the interface? I believe both deserve explanations for the user before they select it.

Thanks!

**Comment by kpu** [comment]
Rename quality estimation to "Highlight potential errors in red"

**Comment by andrenatal** [comment]
thanks @kpu @ChrisBurnsOneOne , I'll have that incorporated.

**Comment by andrenatal** [comment]
PR is here: https://github.com/mozilla-l10n/firefox-translations-l10n/pull/13
