### ISSUE TITLE
Allow seeing original, untranslated strings

### ISSUE THREAD

**Issue by Vinnl** [mozilla/firefox-translations#327]
It would be nice if we could see the original word/sentence, e.g. on hover, on a translated page. Especially when a specific translation is ambiguous and I have a rudimentary grasp of the original language, that can help resolve doubts.

(Issue requested in https://github.com/mozilla/firefox-translations/issues/326#issuecomment-1120996921.)

**Comment by kpatenio** [comment]
I would also like to see the ability to toggle on or off the translation from the extension's infobar, if that's possible. The only way I know to undo a translation right now is to refresh the page.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).
