### ISSUE TITLE
Extension erroneously attempts to translate numbers which are part of calendars

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#328]
Description:
The extension will erroneously attempt to translate numbers which are part of calendars. The most visible effect of this is in Italian.

Some other effects of this is bug is that some numbers which are part of a calendar will be displayed multiple times after the page is translated from certain languages to English. From what I could find so far, this occurs when translating from German, Estonian, Russian to English.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access https://www.wincalendar.com/Italia/calendario (which is in Italian)
3. Translate the page
4. Notice the extension has “translated” several numbers and replaced them with long strings of text causing spillage and general page disorder.

5. Access https://www.wincalendar.com/kalender/Deutschland (which is in German)
6. Translate the page
7. Notice that several numbers are displayed multiple times.

**NOTE: The issue occurs on https://www.booking.com/ on the “Check-In Check-Out’ calendar as well after changing the website language, translating into English and opening the calendar.**

Actual:
The extension erroneously translates numbers which are part of calendars.

Expected:
The extension should not attempt to translate numbers which are part of calendars.

Italian:
https://user-images.githubusercontent.com/50236075/167607767-ff46e763-d7f4-47f8-9d89-1fdafd71162d.mp4

German:
https://user-images.githubusercontent.com/50236075/167607929-1e4718d7-ba5b-43a0-8194-e55cc34fe130.mp4

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842765.
