### ISSUE TITLE
Translation button should not display on all pages

### ISSUE THREAD

**Issue by Caspy7** [mozilla/firefox-translations#348]
My expectation of a translation feature is that the button in the URL bar only shows on pages that *need* translating.

My default language is English and most of the pages I visit are English but currently the button is displaying on all pages no matter what.

**Comment by abhi-agg** [comment]
@Caspy7 Thanks for reporting this. Could you please share following details regarding this bug?

1. A screenshot of the "button in the URL bar" (I just want to make sure that I am interpreting it correctly)
2. Which version of the extension are you using?
3. Are you using Firefox Nightly, Developer or Release?

**Comment by andrenatal** [comment]
This was working before and that was the original intended behavior. Maybe it's a regression.

**Comment by Caspy7** [comment]
1.1.2buildid20220523.151256
last updated June 2, 2022
Running Nightly Firefox.
![image](https://user-images.githubusercontent.com/3854676/172475392-3977c725-e006-46a3-998f-e1a42e5e2faf.png)

I had previously enabled the addon when it was built-in to Nightly, but eventually disabled it.

**Comment by andrenatal** [comment]
This is by design, since there are cases when the language detection model can't accurate detect the page's language.
