### ISSUE TITLE
Translation skips paragraphs

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#35]
1. Go to [https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D1%87%D0%B5%D0%BD%D0%BA%D0%BE,_%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9_%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B5%D0%B2%D0%B8%D1%87](https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D1%87%D0%B5%D0%BD%D0%BA%D0%BE,_%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9_%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B5%D0%B2%D0%B8%D1%87 )
2. Press translate
3. Scroll to the bottom and wait for a minute to make sure the translation is completed
4. Scroll up and observe that some paragraphs are translated to English and some are still in Russian

**Comment by andrenatal** [comment]
I'm unable to reproduce this on pages besides Russian. Do you have examples in other languages?

**Comment by andrenatal** [comment]
I think this is related to the prioritization queues. The in-page parser always starts translating what's in the viewport. So if I start translating from the top, the first paragraphs right after the viewport's end are skipped, but if I first scroll down and put these same paragraphs in the viewport, they are properly translated quickly.

**Comment by andrenatal** [comment]
I'm also seeing quite a few exceptions raised by the engine when translating with Russian involved.

**Comment by kpu** [comment]
Can you be more specific about the exceptions?

**Comment by andrenatal** [comment]
If you follow th exact steps above you'll be able to reproduce and see them
in the the console.

**Comment by kpu** [comment]
25503dc48c3a85ac747c8745bedc728134a89429 has fixed this.  I see full translation (albeit with bad quality and lots of dots) in 25503dc while c40f707 was indeed leaving Russian paragraph in the text.  

This confirms the hypothesis stated in https://github.com/mozilla/firefox-translations/issues/51#issuecomment-1024911744 that the crash was due to mismatch between the HTML feature setting and the content provided.

**Comment by eu9ene** [comment]
ok, I don't see this issue with the latest main now
