### ISSUE TITLE
Google search page identified as russian

### ISSUE THREAD

**Issue by lissyx** [mozilla/firefox-translations#355]
STR:
 - Google.com (Firefox/FR)
 - Search `QT_WRAP_UI`

Firefox translations identifies the page as Russian because after many English it has a few words in Russian

Maybe there is some way to improve the user experience ?

**Comment by jelmervdl** [comment]
Google is one of the many pages that correctly mentions the language of the page in the `<html lang="en-GB">` element. 

Maybe language detection can use this information? Not sure whether it is sufficient to just trust the attribute if it is there, or only use it when lang-id comes back with low confidence scores.

**Comment by nyanpasu64** [comment]
Possibly related: https://www.alsa-project.org/alsa-doc/alsa-lib/group___control.html is misdetected as Russian as well.

**Comment by andrenatal** [comment]
I was able to reproduce all the issues listed above and https://github.com/mozilla/firefox-translations/pull/416 fixes all them
