### ISSUE TITLE
One-Button Translate

### ISSUE THREAD

**Issue by Miserlou** [mozilla/firefox-translations#359]
It'd be great if I could click on the icon and have the page start translating without the need for the second interaction. If there is a secondary concern, it would suffice if this only worked on domains I've translated before.

**Comment by andrenatal** [comment]
Hi @Miserlou, the translation bar is supposed to be automatically displayed if the language is supported, and in this case only clicking the `Translate` button should be enough. Could you please provide the pages in question where the translation bar is not being displayed, and what's your browser locale, please?

**Comment by andrenatal** [comment]
The option to always translate a tab fulfills this
