### ISSUE TITLE
No Way to Stop Translation Once It Has Started

### ISSUE THREAD

**Issue by Miserlou** [mozilla/firefox-translations#362]
Once a page has been translated, the 'X' and 'Options' buttons are both greyed out and stop working. The icon in the URL bar also stops responding. The only way to turn off translation is to close the tab and open it again.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
The built-in version has a "Show original" button.
