### ISSUE TITLE
Missing or confusing "languages supported" verbiage

### ISSUE THREAD

**Issue by defense-commune** [mozilla/firefox-translations#364]
Hello,

The public page of your plugin:

https://addons.mozilla.org/fr/firefox/addon/firefox-translations/

doesn't list the languages supported by the translation engine. I think it definitely should, but maybe that's my personal opinion. What's more troubling is that your "firefox-translations" repository:

https://github.com/mozilla/firefox-translations

doesn't list the languages supported either. Instead, it makes the following rather misleading statement:

> _"Just browse to a website in one of the [languages supported](https://pontoon.mozilla.org/projects/firefox-translations-add-on/) and the option to translate should be displayed."_

Here, your "languages supported" link points to:

https://pontoon.mozilla.org/projects/firefox-translations-add-on/

But this list (as I later discovered) is irrelevant, because it is the "languages supported" by the user interface, not by the translation engine. For example, it lists French. But clearly, after installing your plugin, I cannot translate webpages into French. Only then, I found a second statement, visibly contradicting the first:

> _"Browse to a page in any of the supported languages ([https://github.com/mozilla/firefox-translations-models/#currently-supported-languages](https://github.com/mozilla/firefox-translations-models/#currently-supported-languages)) to have the translation option to appear"_

All this is somewhat blurry, at least for a casual visitor like me.

**Comment by kpu** [comment]
I know this isn't a direct answer to your issue, but French models should land this month.

**Comment by andrenatal** [comment]
Hi @defense-commune.

> doesn't list the languages supported by the translation engine. I think it definitely should, but maybe that's my personal opinion. What's more troubling is that your "firefox-translations" repository:

The languages supported by the addon are present in the addon listing. Maybe you posted the issue before we added them?

<img width="905" alt="Screen Shot 2022-06-07 at 11 46 56 AM" src="https://user-images.githubusercontent.com/973388/172459057-ee3dd080-dc67-409d-a61d-b6694c9fda3e.png">

**Comment by andrenatal** [comment]
I've fixed the issues in the README file and in the addon listing. The issue related to the lack of the french model is being tracked already in different issues, so I'm closing this. Thanks for reporting @defense-commune !
