### ISSUE TITLE
IPA characters are translated as regular characters

### ISSUE THREAD

**Issue by Elaborendum** [mozilla/firefox-translations#365]
Arnold Schwarzenegger's Wikipedia page in English:
![imagen](https://user-images.githubusercontent.com/71190696/171732815-7b267ee6-ab95-45ca-8611-9788a9a22580.png)
Arnold Schwarzenegger's Wikipedia page in English translated to Spanish:
![imagen](https://user-images.githubusercontent.com/71190696/171732914-a21fe5ff-0dda-4496-9d3e-553213fa3ca5.png)

Wikipedia's page on the city of Darjeeling in English:
![imagen](https://user-images.githubusercontent.com/71190696/171732975-5573b51c-b9cb-47b2-92c3-3d926b6d48e5.png)
Wikipedia's page on the city of Darjeeling in English:
![imagen](https://user-images.githubusercontent.com/71190696/171733023-ed1d90ac-edaf-489a-952d-91455b9388d6.png)

You can also see it on Sigmund Freud and Friedrich Hayek's pages.

There are also some other mistakes, like "the Mr Universe title" and "the Mr Olympia title" being translated as "Mr Title of the Universe" and "Mr The Olympia Title" in Arnold Schwarzenegger's page and a contraction like "del" linking the page of Kangchenjunga in Darjeeling's page. But I'm not exactly sure if I should also report mistranslations.

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842819.
