### ISSUE TITLE
http://dictionaries.mozdev.org/ is offline

### ISSUE THREAD

**Issue by ArneBab** [mozilla/firefox-translations#368]
I tried getting more dictionaries, but the server seems to be down.

**Comment by andrenatal** [comment]
Hi @ArneBab, sorry but probably you filed this issue in the wrong repo since this website you linked is not related to your project.

**Comment by ArneBab** [comment]
Ah, yes, I thought the "languages" right-click menu was from firefox-translations, but it seems to be the spell-checker. Sorry for the noise!
