### ISSUE TITLE
AMD CPU wasm validation error: unrecognized opcode: fd c

### ISSUE THREAD

**Issue by nkestrel** [mozilla/firefox-translations#370]
Testing version 1.1.2buildid20220523.151256 on an old AMD Phenom II X6 processor gives the following console error:

    Using optimized gemm (mozIntGemm) implementation
    Loading Translation Engine failure.
    failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 22339: unrecognized opcode: fd c bergamot-translator-worker.js:526:11

**Comment by abhi-agg** [comment]
As per this https://www.cpu-world.com/CPUs/K10/AMD-Phenom%20II%20X6%201090T%20Black%20Edition%20-%20HDT90ZFBK6DGR%20(HDT90ZFBGRBOX).html, this processor doesn't support `SSE4.1`

If this is really the case then the extension will not work as the underlying translation engine has simd instructions and wasm simd is disabled in Firefox for processors older than `SSE4.1`.

**Comment by kpu** [comment]
Can we make a better error message?

**Comment by nkestrel** [comment]
From `about:telemetry#environment-data-tab`:

     architecture    x86-64
     cpu.extensions    [hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSE4A]

No `SSE4.1` support for this processor which isn't surprising. The error at https://mozilla.github.io/translate/ is different:

    wasm streaming compile failed: CompileError: wasm validation error: at offset 1088: v128 not enabled

The web version fails more obviously, with empty language selection dropdowns, while the extension fails silently while "Loading Translation Engine...".

**Comment by abhi-agg** [comment]
> while the extension fails silently while "Loading Translation Engine...".

Do you mean you don't see any notification in the infobar regarding the engine loading failure?

**Comment by nkestrel** [comment]
The extension shows no indication of an error, it just gets stuck loading.

![translate](https://user-images.githubusercontent.com/9861435/172414611-7ec6c1ff-3d4b-47b4-bd29-b50b26dd852f.png)

**Comment by andrenatal** [comment]
I also saw this error on versions earlier than Fx 90.

**Comment by saviosg** [comment]
Does that mean it will not be possible to run this extension on computers that lack such SIMD extensions? Would it be unfeasible to compile Marian to run on such processors?

**Comment by pcp04** [comment]
I have the same CPU same problem.
If you don't fix this problem no one with AMD AM2+, AM3 and FM1 CPUs will be able to use this addon.

**Comment by andrenatal** [comment]
@pcp04 although this obviously affects this addon, engine compatibility issues should be filed and tracked in one of the repos below since there's nothing that can be done here to address it.

https://github.com/browsermt/bergamot-translator
https://github.com/browsermt/marian-dev/
https://github.com/marian-nmt/marian-dev
