### ISSUE TITLE
the add-on always shows: We found an error loading the translation engine. macos big sur with M1 chip.

### ISSUE THREAD

**Issue by W6C** [mozilla/firefox-translations#371]
take this government page as an example, https://www.governo.it/
the add-one automatically detected the right language(Italian), but it could not load the engine correctly and make any translation. is this a bug or a feature?

**Comment by kpu** [comment]
Are you using nightly or general release Firefox?

**Comment by Miserlou** [comment]
Related https://github.com/mozilla/firefox-translations/issues/361

**Comment by jelmervdl** [comment]
@W6C does this page work for you? https://mozilla.github.io/translate/ It might be something similar to https://github.com/mozilla/firefox-translations/issues/370

**Comment by W6C** [comment]
> Are you using nightly or general release Firefox?



general release, version 101.0, with settings:

1. all third-party cookies are blocked.
2. permanent private browsing mode is on.



> Related #361

removing & reinstalling resulted in no changes.

**Comment by abhi-agg** [comment]
@W6C Can you please share the logs of console tab in the Web developer tools of the browser?

**Comment by abhi-agg** [comment]
>     2. permanent private browsing mode is on.

I had missed this. Currently, permanent private browsing mode is not supported in the extension.

We are already tracking it in https://github.com/mozilla/firefox-translations/issues/340

**Comment by W6C** [comment]
> > ```
> > 2. permanent private browsing mode is on.
> > ```
> 
> I had missed this. Currently, permanent private browsing mode is not supported in the extension.
> 
> We are already tracking it in #340

thanks for writing this issue down.
