### ISSUE TITLE
Extension not accessible on Firefox on Android

### ISSUE THREAD

**Issue by ocrete** [mozilla/firefox-translations#374]
It would be great to get this extension whitelisted on Android.

**Comment by mderazon** [comment]
This is the single thing preventing me from ditching chrome on mobile. Any technical reason that makes this difficult ?

**Comment by Juraj-Masiar** [comment]
I've installed it on Nightly ([using custom collection](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)) but I can't make it work - there is no toolbar and action button doesn't do anything.

**Is Android version completely not working?** 
I was hoping it will work, just slower... The [Hacks article ](https://hacks.mozilla.org/2022/06/neural-machine-translation-engine-for-firefox-translations-add-on/)mentions ARM, but I guess they mean ARM powered desktops.

**Comment by tuukka** [comment]
> I've installed it on Nightly (using custom collection) but I can't make it work - there is no toolbar and action button doesn't do anything.

I tried the same, now the extension creates two entries in the menus:

![Add-ons menu](https://user-images.githubusercontent.com/76985/202842527-e84d2706-fa5a-438b-9ce2-83a1841155f8.jpg)

The lower, monochrome icon does nothing. 

The upper icon opens a page that is not fully viewable in portrait orientation:

![Screenshot_20221119-104305.jpg](https://user-images.githubusercontent.com/76985/202842730-53f93c94-90d0-4981-9b34-f8e43403c5f0.jpg)

But in landscape orientation, it works!

![Screenshot_20221119-104625__01.jpg](https://user-images.githubusercontent.com/76985/202842934-705c018e-be9a-41aa-badf-7d017069a26a.jpg)

How to move forward to get this to everyone?

**Comment by dm17** [comment]
Now that firefox-translations does offline translation (without sending the page content to the cloud), this would be very valuable for privacy-focused Android distributions! Think about those times you're using web page translators in order to checkout on a foreign website and entering a credit card number or something... Local translations - even if lower quality - are definitely peace of mind!

**Comment by sylvestre** [comment]
This is mostly a performance issue. We have been discussing about implementing it.

**Comment by andrenatal** [comment]
We also need to determine the proper UI for this (i.e., the current one is not compatible)

**Comment by Juraj-Masiar** [comment]
Having slow feature VS having no feature and forcing users to use Chrome, I think slow wins by far :).
I often need to translate lunch menu for some foreign visitors and having that in my Firefox would be a big help.

**Comment by jonalmeida** [comment]
@sylvestre (via cpeterson) the extension will also have to be [MV3 compatible](https://blog.mozilla.org/addons/2022/11/17/manifest-v3-signing-available-november-21-on-firefox-nightly/) for it to be enabled on mobile.

**Comment by sylvestre** [comment]
@jonalmeida thanks for the information.
However, we are considering moving intree the project.

**Comment by andrenatal** [comment]
I've landed experimental Android support that can be tested by following these steps: https://github.com/mozilla/firefox-translations#android

**Comment by andrenatal** [comment]
I've merged Android support to the main branch and am submitting a new version containing it to internal QA and review, which might take a couple of weeks. 

After that we'll have Android support in the version distributed on AMO and be able to install it on Nightly through a custom collection (which I'll create one containing only it and make it public) by following the instructions listed here: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/. That way we'll be able to have it permanently installed across restarts. 

In this meantime, these instructions are still valid to test it: 
https://github.com/mozilla/firefox-translations/edit/main/README.md#android


I'll keep everyone on this thread posted about the progress despite of having the issue closed.

https://user-images.githubusercontent.com/973388/214216658-dbb7c0df-d0e6-45eb-aa11-497f3d7c3287.mp4

**Comment by andrenatal** [comment]
Heads-up: I've implemented free-form translation as well. 

https://user-images.githubusercontent.com/973388/214455948-3c407241-7f75-42a2-bd19-8ef50e963c36.mp4
