### ISSUE TITLE
sometimes curly braces { } translated as Ã

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/firefox-translations#375]
1. Go to https://transvision.mozfr.org/?recherche=terms&repo=mozilla_org&sourcelocale=en&locale=de&search_type=strings_entities with the browser in English (Nightly 103.0a1) and Firefox Translate 1.1.2.
2. The add-on will offer to translate the page from German.

Actual result: `{` `}` translated as `Ã` in some cases. There are also occurrences which get translated with a single or double quote sign.

**Comment by kpu** [comment]
https://github.com/browsermt/bergamot-translator/issues/419

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842819.
