### ISSUE TITLE
Add-on not working on a Firefox 101.0 (OSX)

### ISSUE THREAD

**Issue by grigoryk** [mozilla/firefox-translations#376]
I'm trying an English -> {whatever} translation, with a few languages, seeing the same results.

After selecting a language and pressing translate, models download and I see an element countdown going down to zero.

However, then not much happens. Addon bar displays that 0 elements are still pending translation. The page remains in the original language. Some words will be switched, e.g. "More" may become "Read more" or something similar.

Here's a video of what this looks like for me: https://www.youtube.com/watch?v=c4NArGG9jtQ

**Comment by kpu** [comment]
If I had to guess, you have an M1 CPU?

**Comment by cadeyrn** [comment]
For me the add-on works on Firefox 101, macOS 12.4, Apple M1 Pro.

But I noted that the page in the video is in English and you selected different languages like Russian as original language. The dropdown is for the original language, there is no option for the destination language.

**Comment by grigoryk** [comment]
@kpu yup, M1 Pro.

@cadeyrn oh, wow, yeah. 🤦 🤦  I totally misunderstood that UI, even to the point of filing this bug! Going to a Russian-language site, yup, it translated into English just fine.

Since I was never asked for my "destination" language explicitly (it's not in the addon settings, not part of the UI), I assumed that the destination language isn't implied by the add-on and that's what I'm specifying in the UI.

For example, that mindset makes sense if I'm learning a foreign language and would like to practice reading articles in it.

But I think the current UI makes sense in a more realistic scenario - opening a webpage in an language I don't understand and translating it into my own.

Is destination language determined based on the current locale?

**Comment by abhi-agg** [comment]
@grigoryk Destination language is determined based on the "preferred language for displaying pages" in language preferences in the browser settings.

**Comment by andrenatal** [comment]
I think this can be closed
