### ISSUE TITLE
Model downloading is stuck if translation of forms is enabled but reversed translation is not supported

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#384]
**Steps**:
1. Go to https://nn.wikipedia.org/wiki/Norsk or any other page in Norwegian Nynorsk using English Firefox
2. Enable translation of forms
3. Press "Translate"

**Expected**:
- Checkbox "Enable translation of forms" is disabled for one-way languages
- Translation works

**Actual**:
- User is able to enable the checkbox and there is an error because it tries to download the reversed model that is required for the translation of forms but does not exist

**How it looks like:**

If using the language for the first time:

<img width="623" alt="Screen Shot 2022-06-06 at 4 50 41 PM" src="https://user-images.githubusercontent.com/2486505/172267499-58b8370b-de53-45c6-ad56-7598d3c31ee0.png">

If the model is already cached:

<img width="697" alt="Screen Shot 2022-06-06 at 4 50 02 PM" src="https://user-images.githubusercontent.com/2486505/172267600-370758b5-abf0-4de0-93a5-4cdc6271433b.png">

**Comment by eu9ene** [comment]
We can definitely make downloading code safer too. Since we persist the checkbox value regardless of the translated language, probably we should handle this on the model loading side. However, it will be confusing if the checkbox is enabled but the translation of forms suddenly doesn't work.

**Comment by andrenatal** [comment]
@abhi-agg how is this going?

**Comment by abhi-agg** [comment]
Currently, I am trying to figure out how to disable UI checkbox in our code base.

**Comment by andrenatal** [comment]
Number 1 works. Thanks @abhi-agg
