### ISSUE TITLE
an option to always translate a domain from a configured language

### ISSUE THREAD

**Issue by rezad1393** [mozilla/firefox-translations#387]
If I open certain Russian websites  I always want to translate those sites. 
also sometimes the addon doesn't detect the language.
so an option to always translate some websites and specifying their language, would help a lot.

**Comment by zpangwin** [comment]
In addition to domain names, it would also be nice to be able to configure the addon to auto-translate certain URL pattterns.

For instance, on reddit/lemmy/kbin/etc, there are certain subreddits/communities within a site that might tend towards one language while other areas on the same domain tend towards another language.

There may also be sections of the site which are in a language but for which you do not want them translated (for instance, a sub where the purpose is learning to speak German - you may want to have it left *untranslated* in that sub if you are learning to speak German, but have it translate a different sub from polish to english).

That said, even just adding a quick "Automatically translate this site" option would be a HUGE accessibility improvement over the current experience of having to manually confirm translations for each tab. I very much prefer opening multiple tabs when browsing and having to confirm on each tab is a huge chore.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).
