### ISSUE TITLE
Incorporate proper readme and architecture docs

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#39]

**Comment by andrenatal** [comment]
Every commit builds and artifact, so one could:

1 - Download the artifact from here https://github.com/mozilla/firefox-translations/actions/runs/1818968414. It will be downlaoded as a zip
2 - In Nightly, type `about:addons` click on the gear, then `install from a file` and load the saved zip file.
3 - On about:config change `extensions.translations.disabled` to `true`; `extensions.experiments.enabled` to `true`; `javascript.options.wasm_simd_wormhole` to `true`

**Comment by kpu** [comment]
Add `xpinstall.signatures.required` to `false` since that job isn't signing then it worked.  Can we add a README section?

**Comment by andrenatal** [comment]
Feel free.

**Comment by andrenatal** [comment]
I just filed an issue here: https://github.com/mozilla/firefox-translations/issues/89

**Comment by eu9ene** [comment]
I have a draft of the Sequence diagram for message flow on paper. It helps a lot to understand communication between components. We can use something like https://mermaid-js.github.io/mermaid/#/ or https://github.com/plantuml/plantuml with simple text notation to make it editable.
