### ISSUE TITLE
Include Polish in supported languages list from add-on detail page

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#390]
Description:
Polish is missing from the list of supported languages from the add-on detail page.

Steps to reproduce:
1. Install the latest Nightly 1.1.3
2. Access the Add-ons Manager page and click on the add-on card to display the detail page
3. Notice that Polish is missing from the list of supported languages

Actual:
Polish is missing from the list of supported languages in the add-ons’ detail page

Expected:
Add Polish to the list of supported languages in the add-ons’ detail page

![2022-06-08_13h55_55](https://user-images.githubusercontent.com/50236075/172600619-e3c04298-e55d-403b-b6fd-9f010870ad40.png)

**Comment by cadeyrn** [comment]
The content in the add-ons manager comes from addons.mozilla.org (AMO) and the current version on AMO is still version 1.1.2. Polish is not included in Firefox Translations 1.1.2, it will be in 1.1.3, AFAIU. So the description is correct in my opinion, even if the Nightly version already has expanded language support.

**Comment by andrenatal** [comment]
Hi @acornestean, we'll add Polish to the list of supported languages when we release the next update containing Polish. Thank you for reminding us.
