### ISSUE TITLE
Keeps asking me to translate from language I've told it never translate from

### ISSUE THREAD

**Issue by forteller** [mozilla/firefox-translations#394]
**Describe the bug**
Some times, not often, but still, the infobar shows up asking me if I want to translate from a language that I've already told the extension never to translate from. The last time this happened it was from Norwegian Bokmål and it happened on https://mail.protonmail.com/u/0/inbox/

**To Reproduce**
1. Select "never translate [language]" on a page where it asks about that
2. Keep going about your life
3. Notice that sometimes it still asks about translating that language 

**Expected behavior**
Never ask again for languages I've told it to never ask about.

**Screenshots**
![image](https://user-images.githubusercontent.com/343561/173066322-2f387330-8923-40f6-8799-ffab998b8d8f.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 100.0.2
- Processor information: Intel® Core™ i7-10750H CPU @ 2.60GHz × 12 
- OS version: Ubuntu 21.10
- System type (32-bit or 64-bit): 64
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: Several

**Comment by andrenatal** [comment]
Hi @forteller , could you please provide more info in regards of the pages you visited beyond protonmail? Specially public websites that won't require login and the languages you selected and the order you visited them. Thank you!

**Comment by andrenatal** [comment]
This is actually supposed to be fixed.
