### ISSUE TITLE
Source map error in console

### ISSUE THREAD

**Issue by cvladan** [mozilla/firefox-translations#419]
**Describe the bug**
Not critical, just polluting console.log.
Typical "Source map" missing error

**To Reproduce**
On my Firefox, wherever I go.

**Expected behavior**
Nothing in console, if possible

**Screenshots**

![image](https://user-images.githubusercontent.com/1913156/175812435-3f8cffc3-cc1b-44ba-b974-ea380aaf405e.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 102.0b9 (64-bit
- OS version: Windows 11
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Console logs from Web Developer Tools: on screenshot

**Comment by marco-c** [comment]
We are not going to make any improvements to the addon since we are now focusing on the built-in version.
