### ISSUE TITLE
Firefox Translations addon prevents GitHub single sign on authentication from working

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations#425]
**Describe the bug**
When opening GitHub pages and your auth token is expiring, GitHub would redirect you to a single sign on page. If Firefox Translations is enabled, the redirect doesn't happen and GitHub becomes unusable.

**To Reproduce**
1. Go to any GitHub page when your auth token is expired

**Expected behavior**
GitHub redirects to the single sign on page.

**Desktop (please complete the following information as possible):**
- Firefox Browser version: Nightly
- OS version: Linux
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: GitHub
- Language of the webpage: English
- Translating to (language): N/A

**Comment by andrenatal** [comment]
I really can't reproduce this one. @marco-c The addon has `Always translate this tab` activated?

**Comment by marco-c** [comment]
@andrenatal I can reproduce it pretty consistenly (every day on the first login to GitHub). I can't find that option, where is it?

Maybe related: I have GitHub always opening in a separate container, "Work".

**Comment by andrenatal** [comment]
Could you please share the steps to start this separate container so I could try to reproduce on my end?

**Comment by marco-c** [comment]
You can:
1) install https://addons.mozilla.org/firefox/addon/multi-account-containers/ (might be reproducible with different steps even without this addon, Containers are part of Firefox itself, this extension is adding some features on top of them);
2) open a GitHub tab
3) right-click on the GitHub tab on the tab strip, select "Open this tab in a new container", then select the "Work" container
4) in the "Multi-Account Containers" toolbar, select "Always open this site in...", then select the "Work" container

**Comment by andrenatal** [comment]
Thanks for sharing the steps @marco-c, but I still can't reproduce it. What version of the extension are you using? Is it the latest one from AMO?

**Comment by sylvestre** [comment]
@marco-c do you still see it?

**Comment by andrenatal** [comment]
Asked him in Hawaii and he said no.
