### ISSUE TITLE
Misidentifies languages

### ISSUE THREAD

**Issue by da2x** [mozilla/firefox-translations#436]
**Describe the bug**
The extension keeps misidentifying webpage languages. It prompts to translate from $randomLanguge when visiting webpages written in English. I’ve verified every time that the page contains either `<html lang="en|en-US|en-GB">`. It doesn’t happen for every webpage from a given website. Just a random article here, or a random forum thread there. I’ve got the impression that $randomLanguge is most often Italian, but I’ve seen others and this might just be selection bias.

**To Reproduce**
1. Difficult to say. The same webpage won’t bring up the toolbar again if I reload the page. So, I can’t provide examples that trigger the bug.

**Expected behavior**
* The extension should be better at detecting languages.
* The extension should have a button to report misidentified languages (and stop prompting on $currentDomain for 14 days).

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 102-flatpak
- Processor information: AMD Ryzen 5 PRO 4650U
- OS version: Fedora Linux 36
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: Hundreds.
- Language of the webpage: English
- Translating to (language): N/A
- Console logs from Web Developer Tools: Not captured.

**Comment by andrenatal** [comment]
This was fixed on #416
