### ISSUE TITLE
Extension is Duplicating Some Text on Websites

### ISSUE THREAD

**Issue by AlexStiyer** [mozilla/firefox-translations#439]
**Describe the bug**
When browsing websites, after successful translation, some translated words seem to start repeating over and over again. It seems to struggle specifically with symbols (-) and numbers.

The number of elements to translate appears to be stuck at 100

**To Reproduce**
1. Go to https://www.ebay-kleinanzeigen.de/stadt/muenchen/
2. Enable translations at the top of the screen
3. Wait for a few seconds

**Expected behavior**
After successful translation, numbers and symbols do not replicate

**Screenshots**
![image](https://user-images.githubusercontent.com/19898828/178231132-2690504d-2351-4b78-bb46-f61a1da255b0.png)
![image](https://user-images.githubusercontent.com/19898828/178230635-10f78ba5-d4ff-451a-95a6-708222b0d33e.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 102.0.1
- Processor information: intel i7 10th gen
- OS version: Windows 11
- System type (32-bit or 64-bit): 64
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: https://www.ebay-kleinanzeigen.de/stadt/muenchen/
- Language of the webpage: German
- Translating to (language): English
- Console logs from Web Developer Tools:
![image](https://user-images.githubusercontent.com/19898828/178231866-fe5f62ac-72cd-4989-b818-cc4675fc454f.png)

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category

**Additional context**
Loving the extension, can't wait until its fully operational! Good work everyone!

**Comment by AlexStiyer** [comment]
Thanks for the fast response.

Did the bad translated text keep changing while on the page?
- The page kept adding more iterations of the same symbol as it sat open

Were you logged in?
- To both firefox and the website yes!

Were you using some sort of ad-block extension? If so, which one?
- Yes uBlock Origin

Did you see this bug on more pages on this website, or just this page or this instance in particular?
- So far only this page

A few pieces of additional information:
I did not notice at first, but I had another translate extension (Translate Web Pages) installed at the same time though it was not enabled.

Once I noticed I did the following:

- Uninstalled Translate Web Pages
- Accessed https://www.ebay-kleinanzeigen.de/stadt/muenchen/
- I no longer experienced the duplication bug.

I was then curious to see if I could recreate the issue 

- Reinstalled Translate Web Pages
- Enabled both extensions at the same time
- Toggled between the two extensions

And the firefox translation is still working as expected 🤔 

It could have been some strange race condition between the two extensions. I will entirely uninstall the other translation extension and see if I ever note this occurring. Maybe worth closing this issue as a special case until proven otherwise?

**Comment by andrenatal** [comment]
I also can't reproduce this issue. @AlexStiyer What you could be seeing where that the two extensions mutation observers were competing and being notified of change in a loop.

**Comment by AlexStiyer** [comment]
@andrenatal I figured as such, definitely doesn't need to be researched farther. Thank you for your response.

**Comment by andrenatal** [comment]
Thanks Alex
