### ISSUE TITLE
Trying to translate a PDF breaks the tabstrip

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations#441]
**Describe the bug**
The Firefox tabstrip is broken when you open a PDF and try to translate it.

**To Reproduce**
1. Open any PDF
2. Translate it

**Expected behavior**
The PDF should be translated. If it can't easily be supported, the option to translate shouldn't be shown on PDF files.

**Screenshots**
Before:
![immagine](https://user-images.githubusercontent.com/1616846/178472692-9ac6600e-08a5-456a-8047-21eef9c05fd3.png)

After:
![immagine](https://user-images.githubusercontent.com/1616846/178472560-1f1d82e9-7556-420e-bd1c-16c171b93cd7.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: Nightly
- OS version: Linux
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: any PDF file
- Language of the webpage: English
- Translating to (language): Italian

**Comment by kpu** [comment]
PDF is a can of worms because one neds to add line unwrapping, column understanding, and next page wrapping just to get text.  People do this but it's a lot more code and models to dump in.  Also unclear what to do when text changes length during translation.  For the time being we should disable on PDF files.

**Comment by marco-c** [comment]
Maybe pdf.js could help give you all those information. CC @calixteman

**Comment by calixteman** [comment]
I think it's almost impossible to change the displayed text because of some text layout issues.
But maybe we could display the translation when the mouse is over a sentence, a paragraph, ...
Anyway, if we can help to try to integrate this nice stuff in pdfjs, feel free to ping us.
