### ISSUE TITLE
`@` (at) signs are removed out of email addresses in translations

### ISSUE THREAD

**Issue by KlassischSpielen** [mozilla/firefox-translations#442]
**Describe the bug**
`@` (at) are removed out of email addresses inside text blocks. Instead of the `@` a `-` will be embedded.

**To Reproduce**
1. Go to https://www.mozilla.org/de/about/legal/impressum/
2. Translate the page to English
3. Scroll down to "Contact information:" ("Kontaktinformation:")
4. See the email address translated as `legal-notices-mozilla.com`. The `@` sign has disappeared.

**Expected behavior**
The `@` (at) sign should be kept inside the email address.

**Screenshots**
![image](https://user-images.githubusercontent.com/109172737/178567145-d0839b2e-c7a2-48d0-81df-17e45283d0bd.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version:102.0.1
- Processor information: 2.4 GHz 8-Core Intel Core i9
- OS version: macOS 12.3.1
- System type (32-bit or 64-bit): 64bit
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: https://www.mozilla.org/de/about/legal/impressum/
- Language of the webpage: German
- Translating to (language): English

**Comment by migmanu** [comment]
I am also facing this issue. Only, instead of replacing `@` with `-` it replaces it with `Ã ` (note the space). Also from German to English.

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842819.
