### ISSUE TITLE
Firefox Translation color icon for enable/disable state

### ISSUE THREAD

**Issue by maxelo** [mozilla/firefox-translations#444]
Love the new implementation of "Firefox Translations" as a step forward on degoogle our dependecy on their products.

Using right now:
Firefox 102.0.1 (64-bit) for WIndows 10
Firefox Translations addon 1.1.2buildid20220523.151256

I would love to know if there is any chance we could have the addon as white when "is not being used" instead of always being blue.
By being colored, the addon looks as if it was always in use

Tthanks for your work!
Greetings from Valdivia, Chile

![Firefox Translations Color example](https://user-images.githubusercontent.com/1003307/178828337-42f08888-8cbb-48f8-b66a-e121a691fc51.png)

**Comment by andrenatal** [comment]
Hi @maxelo , this was already fixed and is being shipped in the upcoming release. Thanks for reporting!
