### ISSUE TITLE
Language detection doesn't work very well

### ISSUE THREAD

**Issue by simon-friedberger** [mozilla/firefox-translations#451]
For example this gets detected as Russian:
https://doc.rust-lang.org/stable/std/f64/consts/constant.PI.html
even though it is fairly obviously English.

**Comment by cadeyrn** [comment]
I can confirm your observation with Firefox Translations 1.1.2. With the current Nightly build of Firefox Translations it works as expected. Therefore it's probably a duplicate of #30 and will be fixed in Firefox Translations 1.1.3.

**Comment by simon-friedberger** [comment]
Good point! 
I think I missed that because it's already closed.
