### ISSUE TITLE
Translator not working on any page

### ISSUE THREAD

**Issue by roni2201** [mozilla/firefox-translations#456]
**Describe the bug**
Translator not working on any page, I put the main page from mozilla as example

**To Reproduce**
1. Turn on the Firefox Translations extension
2. Go to https://www.mozilla.org/en-US/firefox/new/
3. Click on 'translate'
4. Error happens, translate banner freezes, and did not translate the page

**Expected behavior**
Translate the page to Portuguese

**Screenshots**
[firefox_translations_bug.webm](https://user-images.githubusercontent.com/105252197/180336313-2a96eae6-0a13-4e0a-b255-531a8016887d.webm)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 102.0.1
- Processor information: Intel Core 2 Duo T7500
- OS version: Lubuntu 22.04 LTS kernel 5.15.0-43-generic
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.1.2buildid20220523.151256
- Webpage on which issue was observed: any page
- Language of the webpage: English
- Translating to (language): Portuguese
- Console logs from Web Developer Tools:
[console-export-2022-7-21_20-9-39.txt](https://github.com/mozilla/firefox-translations/files/9163433/console-export-2022-7-21_20-9-39.txt)

**Additional context**
In right side upper, toolbar menus disappear when the extension is enabled on page, as you can see on video (00:09 to 00:12)

**Comment by andrenatal** [comment]
Hi @roni2201, based on the logs it seems your cpu is not supported by the translation engine, but @abhi-agg might be able to confirm that. In the upcoming version we'll have better error reporting instead of what you are experiencing.

**Comment by abhi-agg** [comment]
Hi @roni2201 Does your cpu have SSE4.1 support? As per [this](https://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20Mobile%20T7500%20LF80537GG0494M%20(BX80537T7500).html), it doesn't.

If this is true then the extension will not work as it only supports cpus that have at least SSE4.1.

**Comment by roni2201** [comment]
@abhi-agg You are right, my CPU does not support SSE4.1. My notebook is very old. I only read a news on google about new translator extension made by Mozilla, then, I felt like testing it. I did not know about requirements to run the extension. My suggestion is should put a warning in section About this extension in addons.mozilla.org, a warning like: 'CPU support above SSE4.0 instructions' to avoid similar topics(issues).
Thanks for response @abhi-agg  and @andrenatal , I'm going to close this issue

**Comment by andrenatal** [comment]
Thanks @roni2201 . I added a remark to the extension's page about this limitation.

**Comment by pizzahut2** [comment]
@andrenatal Would it be difficult to add code which tests for existence of SSE4.1? I'm probably not the only one who didn't notice the developer comment, and so far the error message doesn't hint at the CPU being the culprit.
