### ISSUE TITLE
Title bar disappears after translation.

### ISSUE THREAD

**Issue by leinad-san** [mozilla/firefox-translations#457]
After translating the page, the title bar disappears. It comes back when opening a new tab, but the translated page remains without the bar.
I tested it only on translating pages from English to Portuguese (the default language of my browser).
![Screenshot_20220723_171823](https://user-images.githubusercontent.com/109875826/180621782-a81aa572-0474-455b-9c62-c13db365a82f.png)
![Screenshot_20220723_171901](https://user-images.githubusercontent.com/109875826/180621785-51b5a6c3-2973-47ea-bf43-2f1eb0f9705b.png)
![Screenshot_20220723_171921](https://user-images.githubusercontent.com/109875826/180621786-2f96fadf-82ba-4bf0-a4ef-f835dcc01da2.png)
.

**Comment by andrenatal** [comment]
Hi, thanks for the report. This issue was fixed and it will be available in the upcoming release.
