### ISSUE TITLE
the more you press the translation icon in the location bar, the more translation bars you have

### ISSUE THREAD

**Issue by bmillemathias** [mozilla/firefox-translations#461]
**Describe the bug**
a translation bar appears each time I press the translation icon in the location bar, stacking down under the  previous one.

**To Reproduce**
1. click the icon firefox translation, a translation bar appears atop off the website widget
2. click the icon firefox translation, a new translation bar appears under the previous one.
3. Continue until death 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8579/180934311-8491f1fd-dddf-4649-8e6f-f9a69fa12749.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 102
- Processor information: x86_64
- OS version: Linux Fedora 36
- System type (32-bit or 64-bit): 64
- Firefox Translation Extension version: 1.1.3
- Webpage on which issue was observed: anyone so far
- Language of the webpage: not relevant
- Translating to (language): not relevant
- Console logs from Web Developer Tools: 

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category

**Additional context**

**Comment by bmillemathias** [comment]
after restarting the browser the problem disappeared

**Comment by bicolino34** [comment]
@bmillemathias can you please reopen this issue?
