### ISSUE TITLE
text not appearing in the translation bar

### ISSUE THREAD

**Issue by bmillemathias** [mozilla/firefox-translations#462]
**Describe the bug**
Some widget have no text or missing icon the version 1.1.3 of the translation bar

**To Reproduce**

**Expected behavior**
have text (see comparision between v1.1.2 and v.1.1.3 here under)

**Screenshots**
v1.1.2
![image](https://user-images.githubusercontent.com/8579/180935249-257f5a4f-b2ce-440d-9566-6fa747e101cd.png)

v1.1.3
![image](https://user-images.githubusercontent.com/8579/180935144-b56a14dd-8d53-43f2-9f8f-e1d322dce02f.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 102
- Processor information: x86_64
- OS version: Linux Fedora 36
- System type (32-bit or 64-bit): 64
- Firefox Translation Extension version: 1.1.3
- Webpage on which issue was observed: anyone so far
- Language of the webpage: not relevant
-  Translating to (language): not relevant
-  Console logs from Web Developer Tools:

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category

there is no cpu extension field

**Additional context**

**Comment by bmillemathias** [comment]
after restarting the problem disappeared

**Comment by bmillemathias** [comment]
I got the same issue on another installation, not a showstopper but not really great for the user

**Comment by bicolino34** [comment]
Same for me. On Windows 8.1
![зображення](https://user-images.githubusercontent.com/58372007/181065508-0d7ef7a2-d7be-45a4-b61c-a5d639b312ed.png)
