### ISSUE TITLE
Nightly release link dead

### ISSUE THREAD

**Issue by jelmervdl** [mozilla/firefox-translations#465]
**Describe the bug**
The install nightly link in the readme is dead: [![Firefox Translations - Install Nightly](https://img.shields.io/badge/Firefox_Translations-Install_Nightly-2ea44f)](https://github.com/mozilla/firefox-translations/releases/download/nightly/firefox_translations.xpi)

The github actions do show the nightly release still being build and uploaded to the release, but I don't see any nightly releases in the releases tab on Github. The above link also just 404s for me and others.

Thanks to Julian Fairfax on Matrix for noticing.

**Comment by andrenatal** [comment]
This was now fixed. It seems someone created a nightly tag manually that wrecked things
