### ISSUE TITLE
Release notes tab opens and steal focus, interrupting user

### ISSUE THREAD

**Issue by nchevobbe** [mozilla/firefox-translations#469]
**Describe the bug**
When the extension updates (even if it's not the result of a user interaction), a tab opens with the release notes, stealing the focus.
This can be annoying if the user is performing some tasks (watching a video, writing an email, …).

**Expected behavior**

It looks like there's an API to check if the browser isn't busy (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/idle) which might be used before opening the release notes tab

**Comment by andrenatal** [comment]
fixed by #498
