### ISSUE TITLE
"Display Statistics" in Options menu seems to do nothing (and disappears after you translate)

### ISSUE THREAD

**Issue by dholbert** [mozilla/firefox-translations#472]
**Describe the bug**
The translation bar's "Options" menu initially has a menu item called "Display Statistics". If you click it, nothing happens.  It also disappears when you actually proceed to translate a page. Maybe it's obsolete cruft that was meant to be removed?

**To Reproduce**
1. Install https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/ in Firefox
2. Make the translation bar show up, by e.g. visiting a site in another language (like [this](https://www.letteratour.it/chi-siamo/copyr.asp)) or by visiting https://example.org/ and clicking the translate icon in the Firefox URL bar (and choosing any arbitrary "this-page-is-in" language) 
3. Click on the "Options" menu on the right side of the translate bar.
4. Click on "Display Statistics"
[nothing happens]
5. Click "Translate"
6. Click "Options" menu again.
[Look for "Display Statistics" item, notice that it's now missing.]

**Expected behavior**
* Statistics should be displayed in step 4; and it shouldn't mysteriously disappear after you complete a translation.
* Or, the menu item should simply not be present at all, if it really doesn't do anything.

**Screenshots**
Here's the menu-item in question:
![image](https://user-images.githubusercontent.com/426803/181119363-19dc1f06-73f5-4828-9ed2-ae09d2307965.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 103
- Processor information: Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
- OS version: Ubuntu 22.04
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.1.3buildid20220722.083742
- Webpage on which issue was observed: https://www.letteratour.it/index.asp and http://example.org/
- Language of the webpage: Italian (in the case of example.org, it's in English but you can pick any "dummy" initial-language, it doesn't matter)
- Translating to (language): English
- Console logs from Web Developer Tools: None (Nothing appears when I click`Display Statistics`)

**Comment by dholbert** [comment]
Here's what the site looks like in step 6 (after I've completed a translation).  Note that this non-functional "display statistics" menu-item has disappeared.
![image](https://user-images.githubusercontent.com/426803/181119925-099f611f-37e1-401e-8b1f-be65656382aa.png)

**Comment by dholbert** [comment]
I can reproduce using current Nightly Firefox 105.0a1 (2022-07-26) (64-bit) and the Nightly translations-extension-version linked from https://github.com/mozilla/firefox-translations#nightly-builds , v1.1.3

**Comment by dholbert** [comment]
Aha, so this *looks* like it has no effect, but really it seems to activate a special diagnostic mode during the following translation operation, which causes colorful borders to get drawn around various parts of the page.

This might be just a case where this menu-item is just mis-labeled?  (since it doesn't immediately display anything, and the borders that it does eventually cause to be displayed aren't really "statistics")

Maybe a better label would be "Show diagnostic overlay" or something like that? (Also, this might be better to move inside of "Translation preferences" rather than being in the top-level user-facing menu.)

**Comment by andrenatal** [comment]
This information in the translation bar is also something enabled by the `Display statistics` button. 

<img width="276" alt="Screen Shot 2022-07-26 at 8 23 30 PM" src="https://user-images.githubusercontent.com/973388/181153932-932e0f81-f799-474e-a0c5-e05cfb0b58ce.png">

**Comment by dholbert** [comment]
Gotcha, ok. So maybe "Statistics" isn't too far off.

So then my main UX-gripe would be just that the label sound like it'll have an immediate effect (`Display $X` sounds like `Show me $X right now`, but in fact it just toggles a flag to modify how a later action is performed).

Maybe a clearer label: "Show statistics while translating"?  (or something to that effect)

That would make it clearer...
 (a) ...that clicking this option won't have any effect right now, but will add something that you can see when you start the translation.
 (b) ...why this menu-item reasonably disappears from the menu after you perform a translation

This label is a bit longer than the current one, but not much longer than the existing `Never translate this site` label that's in the same menu.

**Comment by DawnPaladin** [comment]
I also find this confusing. It seems like this menu item should have a checkbox next to it like "Never translate this site" does.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
