### ISSUE TITLE
ignoreCache remains the same until the entire browser or extension is restarted

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#477]
@andrenatal yep this is going to be executed once for every new chrome window, what I meant is that in theory this may need to pass ignoreCache only one time to refresh a subscript that may have been cached by a previous version, at the moment ignoreCache will stay true for each new chrome window opened while the extension running just got updated, then in the next browser or addon startup ignoreCache will stay false and the script will be cached.

Yesterday I briefly touched base with @mixedpuppy about this corner case and we were in agreement that keeping it as is may be the safest option at the moment (and so to defer doing something about it to either a separate followup or if that turns out to have some impact on user perceived performance).

May still be worth capturing this corner case and related details collected about it in an issue to keep that in mind.

_Originally posted by @rpl in https://github.com/mozilla/firefox-translations/pull/470#discussion_r932051860_

**Comment by marco-c** [comment]
We are not going to make any improvements to the addon since we are now focusing on the built-in version.
