### ISSUE TITLE
Idea from Mozilla Connect community: Make Firefox Translations into a webpage or expand the capabilities of the add-on

### ISSUE THREAD

**Issue by j-sidd** [mozilla/firefox-translations#479]
This feature request is from the [Mozilla Connect](https://connect.mozilla.org/) community...

Link to post:

https://connect.mozilla.org/t5/ideas/make-firefox-translations-into-a-webpage-or-expand-the/idi-p/10849

Body text: 

I like the Firefox Translations add on, but it would be great if there was a webpage similar to Google or Bing translate, where we can simply input text that needs translating, and it would translate it.

Alternatively, the add on could be expanded, so that when you click the add on icon in the browser it loads up a text box that you could add text you want translated, and it would translate it.

**Comment by jelmervdl** [comment]
Something like https://mozilla.github.io/translate/?

That is the wasm test page from https://github.com/browsermt/bergamot-translator. I'm working on cleaning it up a bit in https://github.com/browsermt/bergamot-translator/pull/437
