### ISSUE TITLE
Option to disable opening changelog after update

### ISSUE THREAD

**Issue by parcelcat** [mozilla/firefox-translations#483]
**Is your feature request related to a problem? Please describe.**
After every extension update, the changelog opens in a new tab. I prefer not to have the changelog open automatically.

**Describe the solution you'd like**
Adding an option in the Preferences to disable/enable displaying the changelog after updates would resolve this.

**Describe alternatives you've considered**
This option is a simple solution that is used in many Firefox extensions. An alternative is to not show the changelog at all, or not show the changelog by default.

**Additional context**
Great extension! This option would make the extension easier to recommend to others.

Related: #469

**Comment by Mel34** [comment]
Only extension I use that opens it's changelog page in a new tab whenever it updates itself. Can it like, not?

**Comment by kevincox** [comment]
I'm going to put a vote in for "just don't". As a software developer myself I know that I am always looking to advertise new features to my users. But the unfortunate truth is that most of your users aren't quite as excited about every new feature as we are. Nearly all users see Firefox Translations as a utility that hides nicely in the corner and springs into action only when it is helpful.

Instead I would suggest that a dedicated "changelog" is created somewhere publicly. Then the preferences menu can have a link to this. This has a number of advantages over the current approach:
1. Users who don't care don't have it forced upon them.
2. Users can follow this blog via their regular news for, for example a feed reader or subscribe via email. This is much more comfortable for most people then a browser pop-up.
3. The changelog now has a public URL that can be shared. For example this can be posted to news aggregators and shared on social media which is great for marketing.
4. Non-users can subscribe. Maybe I am looking for a particular language in Firefox Translations and I want to subscribe to know when it launches, but don't have much use of it until then.

There are tons of services that can set up a free blog like wordpress.com or even GitHub releases can be used as they provide a feed and the option to subscribe via email.
