### ISSUE TITLE
Remember the selected language when language detection is not automatic

### ISSUE THREAD

**Issue by Yona-TYT** [mozilla/firefox-translations#484]
On some pages (such as twitter), the plugin does not automatically detect the language to translate, because it assumes everything is in the correct language.

So every time I activate the translation I must also use the selector to choose the language in which the page is.

Wouldn't it be better to remember my choice in the selector for the futures times?.

![Captura desde 2022-08-03 21-30-41](https://user-images.githubusercontent.com/27737574/182744100-18ef57e7-3199-484f-844c-8bbfd54bb496.png)

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).
