### ISSUE TITLE
After install, no translation or browser translation "bar" appears while viewing a page with german on it. You might want to write a sentence or two on how to use this extension? 2 screenshots isn't cutting it.

### ISSUE THREAD

**Issue by Bluto39** [mozilla/firefox-translations#489]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information as possible):**
- Firefox Browser version:
- Processor information:
- OS version:
- System type (32-bit or 64-bit):
- Firefox Translation Extension version:
- Webpage on which issue was observed:
- Language of the webpage:
- Translating to (language):
- Console logs from Web Developer Tools:

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category

**Additional context**

**Comment by marco-c** [comment]
The built-in version has a support page on SUMO.
