### ISSUE TITLE
Language is not detected / translation not offered

### ISSUE THREAD

**Issue by akumria** [mozilla/firefox-translations#490]
**Describe the bug**

When visiting https://www.suewag.de/privatkunden the toolbar extension does not detect German and there appears to be no way to force a translation even if I know what language a webpage is in.

**To Reproduce**
1. Go to https://www.suewag.de/privatkunden
2. Observe the translation toolbar does not detect German
3. There appears to be no way to trigger a translation

**Expected behavior**
The extension should detect the language or offer a way to force translation from a user selectable language

**Screenshots**

![suewag-translation-not-working](https://user-images.githubusercontent.com/202904/184132207-a65ac15a-0633-46cc-91bf-6b508e378465.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 104.0b7
- Processor information: Intel i7 [hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSSE3, hasSSE4_1, hasSSE4_2] 
- OS version: Linux (Debian)
- System type (32-bit or 64-bit): 64 (x86-64)
- Firefox Translation Extension version: 1.1.4buildid20220803.111909
- Webpage on which issue was observed: https://www.suewag.de/privatkunden
- Language of the webpage: German
- Translating to (language): English
- Console logs from Web Developer Tools:

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category

**Additional context**

**Comment by kpu** [comment]
Oh interesting.  This page is using [custom HTML elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) and all the text is attributes.  
```
<eon-ui-navigation-flyout-link href="https://www.suewag.de/privatkunden/produkte-tarife/glasfaser/bestellformular-glasfaser" text="Glasfaser-Pakete vorbestellen" aria-label="Glasfaser-Pakete vorbestellen" target="_self">
            </eon-ui-navigation-flyout-link>
```

**Comment by jelmervdl** [comment]
Custom elements are (mostly) supported by the add-on: Youtube uses them for most of the text, and those are translated. It's that they use [ShadowRoot](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) to wrap their contents. That effectively hides them from the add-on.

It should be possible to add support for it, they're using open shadowRoots so you can still drill down into them. But the API's we use like [TreeWalker](https://developer.mozilla.org/en-US/docs/Web/API/Treewalker) don't do this out of the box. I'm [tracking it here](https://github.com/jelmervdl/firefox-translations/issues/38).

**Comment by sylvestre** [comment]
German is detected for me but the translation isn't updating the text.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
This problem still occurs in the built-in version, we are tracking it in https://bugzilla.mozilla.org/show_bug.cgi?id=1841656.
