### ISSUE TITLE
French->English translation quality issue on https://www.ledauphine.com/sport/2022/08/15/je-reste-sur-mon-plan-initial-a-l-utmb-kilian-jornet-apres-ses-deboires-a-sierre-zinal

### ISSUE THREAD

**Issue by bgrins** [mozilla/firefox-translations#492]
**Describe the bug**
French->English translation quality issue on https://www.ledauphine.com/sport/2022/08/15/je-reste-sur-mon-plan-initial-a-l-utmb-kilian-jornet-apres-ses-deboires-a-sierre-zinal

**To Reproduce**
1. Go to https://www.ledauphine.com/sport/2022/08/15/je-reste-sur-mon-plan-initial-a-l-utmb-kilian-jornet-apres-ses-deboires-a-sierre-zinal
2. Translate page

**Expected behavior**
There are a few parts of the sentence "Nonuple vainqueur de Sierre-Zinal, dont il était le grand favori, [Jornet (34 ans) s'est largement incliné samedi](https://www.ledauphine.com/sport/2022/08/13/sensation-le-kenyan-kangogo-bat-kilian-jornet-a-sierre-zinal-a-deux-semaines-de-l-utmb), terminant 5e à près de 3 minutes du vainqueur kényan Mark Kangogo, après avoir été distancé rapidement sur un parcours écrasé par le soleil." where the results in Firefox seem potentially less accurate than Chrome and Safari.

* "Unpacious" vs "nine-time"
* "bowed" vs "lost heavily"
* "sun-crushed" vs "course crushed by the sun"

**Screenshots**
Results in Firefox:
![image](https://user-images.githubusercontent.com/95570/184705646-274aad02-049d-4725-9902-3c0198ebcf8b.png)

Results in Chrome:
![image](https://user-images.githubusercontent.com/95570/184705551-ea3395b4-61bf-4c50-877a-6b32c9109205.png)

Results in Safari:
![image](https://user-images.githubusercontent.com/95570/184705583-268cd7de-1809-4603-8a52-e28f38869285.png)

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
I've already reported this problem, and you can report additional translation errors on https://docs.google.com/forms/d/e/1FAIpQLSdoRWnsHX6vVnGIRyLi4Kl-p0GrmeVIioqWsTz3aVTRfLScng/viewform.
