### ISSUE TITLE
Translate arbitrary text to and from supported languages

### ISSUE THREAD

**Issue by MrDrMcCoy** [mozilla/firefox-translations#493]
Currently, the extension appears to only be able to translate existing web pages from the supported language list to your preferred reading language. A simple and useful addition to this extension would be to provide a place to paste arbitrary text for translation to and from any supported language. For example, translate a paragraph from the clipboard from Spanish to German when the reading language is English. Would it be possible to add this in?

**Comment by kpu** [comment]
Regarding clipboard, https://translatelocally.com/web/ and https://translatelocally.com/ though I recognize that we need to do a better job of cross-selling and integrating these offerings.  

Regarding selecting the language, try https://github.com/jelmervdl/firefox-translations/releases/download/v0.6.1/bergamot_translations.xpi and let us know what you think?

**Comment by MrDrMcCoy** [comment]
@kpu Thanks for all that. Seems that all the pieces exist, and merely need to be combined into a single, convenient package. That's all I was really looking for.

**Comment by andrenatal** [comment]
Thanks @MrDrMcCoy , this is a duplication of #479 . Let's track it there.
