### ISSUE TITLE
DE→EN: A very sticky bug with translation (strange loop while translating "adhesive")

### ISSUE THREAD

**Issue by garrett** [mozilla/firefox-translations#494]
**Describe the bug**

Translations usually work well, but there's a hilariously wrong translation in a recent Nordbayern.de article.

![image](https://user-images.githubusercontent.com/10246/185072359-7f9bb523-5834-41df-9e4f-2704c7dc6d17.png)

I'm reporting it as the translation seems to have hit a loop in a sentence and eventually gives up translating it (and thankfully moves on). This isn't the case of a "bad translation", but points to some bug in the code.

**To Reproduce**
1. Go to https://www.nordbayern.de/region/nuernberg/aktivisten-kleben-sich-fest-klima-protest-lost-chaos-in-nurnbergs-innenstadt-aus-1.12437350
3. Click on translate
4. Scroll down to the caption under the lead image.
5. See error on the caption and later in the page, at the 4th paragraph.

Since this is an article, it can change, so I made sure it is also archived @ https://www.nordbayern.de/region/nuernberg/aktivisten-kleben-sich-fest-klima-protest-lost-chaos-in-nurnbergs-innenstadt-aus-1.12437350

**Expected behavior**

This should be translated better:

_"Exakt 100 Sekunden vor zwölf Uhr klebten sich die ersten Klima-Aktivisten mit handelsüblichem Sekundenkleber fest."_ 

I did not expect:

_"Exactly 100 seconds before twelve o'clock, the first climate activists adhesive adhesive adhesive adhesives adhesive adhesive adhesive adhesive adhesives adhesive adhesive."_ 

For reference DeepL says: _"Exactly 100 seconds before noon, the first climate activists stuck themselves with commercial superglue."_

And Google Translate is similar: _"Exactly 100 seconds before twelve o'clock the first climate activists glued themselves with commercial super glue."_

- "kleben" (used as "klebten" here) is a verb for stick / glue / bond.
  - "Kleben" also happens to be a noun for adhesive / adhesives / glue / etc.
- "Sekundenkleber" is a noun for superglue / instant glue (literally: "seconds"+"glue").

The translation engine might be getting confused between the noun vs. verb usage of the word and then it starts [panicking in a "Kirk vs. Computer" fashion](https://www.youtube.com/watch?v=ZuYbDP2kDfg)?

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 103.0.2 (Flatpak, from Flathub)
- Processor information: Intel(R) Core(TM) i7-10610U CPU
- OS version: Fedora Linux 36 Silverblue
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.1.4buildid20220803.111909 (August 4, 2022)
- Webpage on which issue was observed: https://www.nordbayern.de/region/nuernberg/aktivisten-kleben-sich-fest-klima-protest-lost-chaos-in-nurnbergs-innenstadt-aus-1.12437350
- Language of the webpage: German (DE)
- Translating to (language): English (EN)
- Console logs from Web Developer Tools: 

```js
Using fallback gemm implementation bergamot-translator-worker.js:2965:17
Wasm Runtime initialized Successfully (preRun -> onRuntimeInitialized) in 0.007 secs translationWorker.js:83:29
Creating Translation Service with config: {"cacheSize":0} translationWorker.js:358:25
Translation Service created successfully translationWorker.js:360:25
Constructing translation model deen translationWorker.js:388:21
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: false
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            translationWorker.js:450:21
Aligned memory sizes: Model:17140837, Shortlist:5047568,  Vocab: 784269 translationWorker.js:451:21
Constructing translation model ende translationWorker.js:388:21
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: true
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            translationWorker.js:450:21
Aligned memory sizes: Model:17140835, Shortlist:3943644,  Vocab: 784269 translationWorker.js:451:21
Model 'deen' successfully constructed. Time taken: 0.391 secs translationWorker.js:327:23
loadLanguageModel function complete translationWorker.js:350:21
[InPlaceTranslation] /A Cloning node 
<a href="/agb" target="_blank" data-x-bergamot-id="0">
 because it was already inserted earlier InPageTranslation.js:817:37
[InPlaceTranslation] /A Cloning node 
<a href="https://abo.nn.de/verlage" data-x-bergamot-id="0">
 because it was already inserted earlier InPageTranslation.js:817:37
[InPlaceTranslation] /A Child <a href="https://abo.nn.de/verlage" data-x-bergamot-id="0"><font x-bergamot-sentence-index="1" x-bergamot-sentence-score="-0.077449"><font x-bergamot-word-index="6" x-bergamot-word-score="-0.475992"></font></font></a> has no text but counterpart <a href="https://abo.nn.de/verlage" data-x-bergamot-id="0"><font x-bergamot-sentence-index="1" x-bergamot-sentence-score="-0.077449"><font x-bergamot-word-index="3" x-bergamot-word-score="-0.00131381">cooperating</font> <font x-bergamot-word-index="4" x-bergamot-word-score="-0.166581">publishers</font></font></a> does InPageTranslation.js:831:37
[InPlaceTranslation] /A Child <a href="https://abo.nn.de/datenschutz" data-x-bergamot-id="3"><font x-bergamot-sentence-index="8" x-bergamot-sentence-score="-0.125247"><font x-bergamot-word-index="17" x-bergamot-word-score="-0.210845"></font></font></a> has no text but counterpart <a href="https://abo.nn.de/datenschutz" data-x-bergamot-id="3">https://abo.nn.de/datenschutz</a> does InPageTranslation.js:831:37
[InPlaceTranslation] /A Cloning node 
<a href="https://abo.nn.de/datenschutz" data-x-bergamot-id="3">
 because it was already inserted earlier InPageTranslation.js:817:37
[InPlaceTranslation] /A Cloning node 
<a href="/agb" target="_blank" data-x-bergamot-id="0">
 because it was already inserted earlier InPageTranslation.js:817:37
[InPlaceTranslation] /A Cloning node 
<a href="https://abo.nn.de/verlage" data-x-bergamot-id="0">
 because it was already inserted earlier InPageTranslation.js:817:37
[InPlaceTranslation] /A Child <a href="https://abo.nn.de/verlage" data-x-bergamot-id="0"><font x-bergamot-sentence-index="1" x-bergamot-sentence-score="-0.077449"><font x-bergamot-word-index="6" x-bergamot-word-score="-0.475992"></font></font></a> has no text but counterpart <a href="https://abo.nn.de/verlage" data-x-bergamot-id="0"><font x-bergamot-sentence-index="1" x-bergamot-sentence-score="-0.077449"><font x-bergamot-word-index="3" x-bergamot-word-score="-0.00131381">cooperating</font> <font x-bergamot-word-index="4" x-bergamot-word-score="-0.166581">publishers</font></font></a> does InPageTranslation.js:831:37
[InPlaceTranslation] /A Child <a href="https://abo.nn.de/datenschutz" data-x-bergamot-id="3"><font x-bergamot-sentence-index="8" x-bergamot-sentence-score="-0.125247"><font x-bergamot-word-index="17" x-bergamot-word-score="-0.210845"></font></font></a> has no text but counterpart <a href="https://abo.nn.de/datenschutz" data-x-bergamot-id="3">https://abo.nn.de/datenschutz</a> does InPageTranslation.js:831:37
[InPlaceTranslation] /A Cloning node 
<a href="https://abo.nn.de/datenschutz" data-x-bergamot-id="3">
 because it was already inserted earlier InPageTranslation.js:817:37
```

Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category

architecture 	x86-64 

cpu.extensions 	[hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSSE3, hasSSE4_1, hasSSE4_2, hasAVX, hasAVX2, hasAES]

**Comment by marco-c** [comment]
This was pretty funny indeed!

We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
I've already reported this problem, and you can report additional translation errors on https://docs.google.com/forms/d/e/1FAIpQLSdoRWnsHX6vVnGIRyLi4Kl-p0GrmeVIioqWsTz3aVTRfLScng/viewform.
