### ISSUE TITLE
DTD files are being removed from Firefox

### ISSUE THREAD

**Issue by flodolo** [mozilla/firefox-translations#496]
Just remembered you're [loading 2 DTDs files here](https://github.com/mozilla/firefox-translations/blob/e632961d6266fecc10b2bd3842d7b293b6d18d54/extension/view/js/translation-notification-fxtranslations.js#L50-L51).

notification.dtd is going away in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1785216) (which already has a patch), while translation.dtd is going in [this other bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1734220) (which will probably have a patch soon). I expect them to be gone with fx106.

If you need strings, they should live inside the add-on, or you should find a different way to load the existing Firefox UI.

(CC @eemeli)

**Comment by eemeli** [comment]
The patches migrating [notification.dtd](https://phabricator.services.mozilla.com/D154890) and [translation.dtd](https://phabricator.services.mozilla.com/D155110) to Fluent will now leave the legacy files in the tree until this is resolved.

I've filed [bug 1788595](https://bugzilla.mozilla.org/show_bug.cgi?id=1788595) for tracking this, as it's required for the exceptions added to the `browser_all_files_referenced.js` test.

**Comment by flodolo** [comment]
There is a patch here, no clue if the approach is good, but strings should live in the add-on
https://github.com/mozilla/firefox-translations/pull/527

**Comment by andrenatal** [comment]
fixed by #527
