### ISSUE TITLE
Option tab of the translation bar not vertically centered.

### ISSUE THREAD

**Issue by Jourdelune** [mozilla/firefox-translations#500]
**Describe the bug**
The bar option and the other tabs are not vertically centered. The screenshot will clarify the bug.

**To Reproduce**
1. Just open the translation bar.

**Expected behavior**
The tabs are centered vertically.

**Screenshots**
![image](https://user-images.githubusercontent.com/64205064/186604941-7b34f84b-a610-4d90-92e2-431011c60cc3.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: Firefox 104.0
- Processor information: GenuineIntel 4 cores
- OS version: Linux 5.15.0-46-generic
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 	1.1.4buildid20220803.111909
- Webpage on which issue was observed: github for exemple
- Language of the webpage: english
- Translating to (language): None but I use french
- Console logs from Web Developer Tools: No logs

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
