### ISSUE TITLE
Translate the title of the page

### ISSUE THREAD

**Issue by martinthomson** [mozilla/firefox-translations#501]
**Is your feature request related to a problem? Please describe.**
I notice that the title of the page is not translated.

**Describe the solution you'd like**
The text of the page title could be translated in place.

**Describe alternatives you've considered**
There is no easy way to indicate potential translation errors in a title, but it is still probably worth finding some way to do that, even if it is just on a tooltip.

**Additional context**
n/a

**Comment by martinthomson** [comment]
Ah, that's very surprising.  As you say, if you turn that option off, the title is translated.

That is surprising enough that I still regard this as a bug, rather than something intentional.

**Comment by jelmervdl** [comment]
I agree, it's a bug. It should translate the title as well, even though there is no way to communicate translation quality in the title.

Technically we can just implement it by stripping the tags added by quality estimation before we replace the title. The `InPageTranslation` class should be aware that [it is not allowed to add anything but text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title) to the `<title>` element.

**Comment by marco-c** [comment]
The built-in version is not translating title yet, implementing it is tracked in bug 1819205.
