### ISSUE TITLE
Translation bar width and sidebars

### ISSUE THREAD

**Issue by martinthomson** [mozilla/firefox-translations#502]
**Describe the bug**
The control bar displays at the full width of the window, not the width of the page.

**To Reproduce**
1. Open a sidebar (history, bookmarks, an addon).
2. Go to any site that might result in translation.
3. See the translation bar.

**Expected behavior**
The translation bar is related to content and has no need to present as browser chrome.  As such, it should follow the content.

**Screenshots**
n/a

**Desktop (please complete the following information as possible):**
- Firefox Browser version: Nightly 106
- Firefox Translation Extension version: 1.1.4buildid20220803.111909
- Webpage on which issue was observed: Any

**Additional context**
n/a

**Comment by andrenatal** [comment]
Closing this since the UI is going to be redesigned
