### ISSUE TITLE
Improve byline

### ISSUE THREAD

**Issue by martinthomson** [mozilla/firefox-translations#503]
**Is your feature request related to a problem? Please describe.**
The [addon page](https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/) says "Translate websites in your browser without using the cloud."  I find this a little indirect.  The real benefit here is privacy: you don't send the entire content of the page you are looking at to an external service (cloud or otherwise).

**Describe the solution you'd like**
"Translate websites in your browser, privately."

**Describe alternatives you've considered**
I'm sure that there are many more options here, but this seems to cover it already.  The phrase "in your browser" remains key, so that might even be emphasized more somehow, but the longer description already covers that quite nicely.

**Additional context**
n/a

**Comment by andrenatal** [comment]
Thanks for the suggestion @martinthomson . I've just changed it.
