### ISSUE TITLE
Reddit post translation glitches

### ISSUE THREAD

**Issue by vulongm** [mozilla/firefox-translations#505]
**Describe the bug**
When visiting a post on Reddit the translation glitches where the text is translated then becomes untranslated before translated again in a loop.

**To Reproduce**
1. Go to a subreddit such as https://www.reddit.com/r/de_EDV/ and turn on the translation
2. Click on a text post in the page

**Screenshots**

https://user-images.githubusercontent.com/50088314/187598202-ea2396dd-465a-434f-8503-9713f0ccc4e2.mp4

**Comment by andrenatal** [comment]
I can repro this. It seems reddit re-renders the content as you scroll it.

**Comment by DSnva** [comment]
Yes, old bug, very annoying! Now I don't use Firefox. I installed the "TWP - Translate Web Pages" (https://github.com/FilipePS/Traduzir-paginas-web) extension in google chrome and edge. In a firefox https://addons.mozilla.org/pt-BR/firefox/addon/traduzir-paginas-web/. Currently, version 9.8.0.3 has three translators, Google, Bing and Yandex. In Google Chrome, the bug disappears if I use Google translate, in Edge it disappears if I use translation from bing.

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842820.
