### ISSUE TITLE
[Language Request] Add Japanese Translation

### ISSUE THREAD

**Issue by ThisNekoGuy** [mozilla/firefox-translations#510]
**Is your feature request related to a problem? Please describe.**
This language is not supported yet.

**Describe the solution you'd like**
Translation support for this language to be added.

**Describe alternatives you've considered**
Use a different extension to provide this support.

**Additional context**
N/A

**Comment by ChaosDMNS** [comment]
omg yes... that should have been the first language they added. kinda weird.. it's like the language most people use online translators for.

**Comment by kpu** [comment]
It's on the list for the new EU-funded project High Performance Language Technologies.  Which is just starting writing a scalable pipeline.  So the release will take some time.

**Comment by MisterSheeple** [comment]
What alternatives are available for translating Japanese for the time being?

**Comment by vitonsky** [comment]
@MisterSheeple you can use https://github.com/translate-tools/linguist

Linguist let you choose translation backend. For now you can use Google or DeepL and when firefox will supports Japanese in their translator, just toggle translator in Linguist preferences to Bergamot

![image](https://user-images.githubusercontent.com/86191922/235343526-1482138d-3cc3-4179-bd24-d02c80388a7a.png)

**Comment by GunGunGun** [comment]
#714

**Comment by marco-c** [comment]
We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
For example, [here's the Japanese request](https://connect.mozilla.org/t5/ideas/japanese-translate-option-in-firefox-translations/idi-p/22959).
