### ISSUE TITLE
Translation can turn unicode characters into '?'

### ISSUE THREAD

**Issue by eythian** [mozilla/firefox-translations#511]
**Describe the bug**
Text with unicode characters can become '?' after translation

**To Reproduce**
1. Go to https://speld.nl/2022/09/13/farmers-defence-force-doet-woke-uitspraak-om-eindelijk-gezien-te-worden-als-gevaar-voor-democratie/
2. Click on translate from Dutch to English
3. Scroll down to the first paragraph of the story
4. See that the text which originally is "Minister Yeşilgöz van Justitie en Veiligheid" has become "Minister Ye?ilgaz of Justice and Security", and later in the next paragraph "Minister Ye?ilga?z"

**Expected behavior**
The unicode characters should be treated properly and not become '?'

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/2203130/190121310-258fef63-44c7-4335-a6c0-0ff90fa53e1c.png)

After:
![image](https://user-images.githubusercontent.com/2203130/190121433-4a1d9107-9a1a-4a61-80d8-aa8786e47413.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 104.0.1 (installed with snap)
- Processor information: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
- OS version: Ubuntu 22.04.1 LTS
- System type (32-bit or 64-bit): 64
- Firefox Translation Extension version: 1.1.4buildid20220803.111909
- Webpage on which issue was observed: https://speld.nl/2022/09/13/farmers-defence-force-doet-woke-uitspraak-om-eindelijk-gezien-te-worden-als-gevaar-voor-democratie/
- Language of the webpage: Dutch, though the name demonstrating the issue is Turkish
- Translating to (language): English
- Console logs from Web Developer Tools: 

Using fallback gemm implementation bergamot-translator-worker.js:2965:17
Wasm Runtime initialized Successfully (preRun -> onRuntimeInitialized) in 0.004 secs translationWorker.js:83:29
Creating Translation Service with config: {"cacheSize":0} translationWorker.js:358:25
Translation Service created successfully translationWorker.js:360:25
Constructing translation model nlen translationWorker.js:388:21
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: true
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            translationWorker.js:450:21
Aligned memory sizes: Model:17140899, Shortlist:4940304,  Vocab: 807730 translationWorker.js:451:21
Model 'nlen' successfully constructed. Time taken: 0.167 secs translationWorker.js:327:23
loadLanguageModel function complete translationWorker.js:350:21

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842819.
