### ISSUE TITLE
Thunderbird version

### ISSUE THREAD

**Issue by SecT0uch** [mozilla/firefox-translations#512]
First off, thanks for that extension, it really changes my everyday life.
I really like the idea of everything happening locally.

I'm wondering if it would be a lot of work to port that add-on for Thunderbird.
Would you consider it ?

**Describe the solution you'd like**
A add-on able to translate the body of emails.

**Comment by kpu** [comment]
https://github.com/jelmervdl/firefox-translations/issues/29

**Comment by jelmervdl** [comment]
@SecT0uch just to get a better idea of how people would use this functionality: would you want incoming email to be translated, or help with composing outgoing emails in a foreign language? Or both?

**Comment by SecT0uch** [comment]
I would like to selectively translate mails in my inbox, in a similar way the Firefox add-on allows it.

I'm often receiving e-mails in a foreign language and would like to be able to translate it locally in a few clicks.

**Comment by sylvestre** [comment]
I agree that it would be a cool feature.
If(when?) we move this code in Firefox tree, it will make it easier for the Thunderbird team to implement it.

Anyway, this issue tracker is for Firefox itself.
Please open a new bug here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird

**Comment by jmaris** [comment]
This would be an incredible addition. to thunderbird. I work in the public sector and regularly recieve emails in 24 languages, many of which I don't understand. Having this feature within Thunderbird would massively improve my workflows.

**Comment by cadeyrn** [comment]
You can follow [BZ-1823007](https://bugzilla.mozilla.org/show_bug.cgi?id=1823007) to see if/when an integration into Thunderbird will happen.
