### ISSUE TITLE
Transfer ownership to browsermt organization

### ISSUE THREAD

**Issue by kpu** [mozilla/firefox-translations#515]
My understanding is Mozilla no longer intends to maintain this repository now that the EU project Bergamot has ended.  By transferring it to github.com/browsermt, we will be able to merge the maintained version from https://github.com/jelmervdl/firefox-translations/ and maintain a redirect to the right repository.

**Comment by aggroskater** [comment]
Wait. What? Why on earth would they not continue to maintain and improve this add-on? This is a killer feature!

**Comment by andrenatal** [comment]
Misleading. Mozilla never announced that.

**Comment by lonnen** [comment]
@kpu we're off at a work week but I'll come back to this shortly
