### ISSUE TITLE
Normalize language codes on language detection

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#521]
We are seeing multiple reports on telemetry when the page reports to be in "EN", which ends summoning the translation bar even for english agents. Similar to https://github.com/mozilla/firefox-translations/commit/bc5cdf497f457410f35fc5f5a460ccbddd546a23

**Comment by sylvestre** [comment]
Yeah, I am getting this bug myself 
Anything I can do to help you debug this ?

**Comment by andrenatal** [comment]
I can't reproduce it. Do you have STRs?

**Comment by andrenatal** [comment]
Nevermind, I can now.
