### ISSUE TITLE
Shared with Firefox Sync "Never translate this page" information

### ISSUE THREAD

**Issue by srueegger** [mozilla/firefox-translations#523]
**Is your feature request related to a problem? Please describe.**
If you have Firefox installed on multiple computers. You have to mark the websites that you never want to have translated individually.

That can be a bit annoying.

**Describe the solution you'd like**
I would love it if you could (optionally of course) sync these settings across Firefox Accounts. That way, a website that I never want to translate would be marked as such right away on all my computers (and virtual machines).

**Describe alternatives you've considered**
no alternative solution.

**Additional context**
Firefox addons can use the Firefox Accounts infrastructure to sync data.

The "Firefox Multi-Account Containers" addon synchronizes its settings via the Firefox account.

![Bildschirmfoto vom 2022-10-13 19-14-17](https://user-images.githubusercontent.com/11472914/195662634-1cb7e477-824a-4a03-8b59-54a4b1e6c404.png)

**Comment by marco-c** [comment]
@gregtatum is this automatically done now in the built-in version?

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If this is not already supported in the built-in version, we should file a bug for it on [Bugzilla](https://bugzilla.mozilla.org/).
