### ISSUE TITLE
Cannot add exception language

### ISSUE THREAD

**Issue by Shituation** [mozilla/firefox-translations#531]
I cannot add a language as an exception for translation.
![sshot-002](https://user-images.githubusercontent.com/43975882/197814801-8737b0c5-ee19-4c81-8322-66e48780407c.png)

How do I add a language there so the app doesn't detect certain languages and offers me to translate it?

**Comment by Shituation** [comment]
Thanks!

**Comment by andrenatal** [comment]
fixed by #527 and others
