### ISSUE TITLE
[FEATURE] Add an option to translate X webpage by default

### ISSUE THREAD

**Issue by Shituation** [mozilla/firefox-translations#533]
Can you add an option to translate "favorite" pages by default? it would be the same than exceptions but to apply translations automatically instead of not doing so.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).

**Comment by Shituation** [comment]
can you elaborate a little more on that? went to check for "firefox translation built in" and I still see the extension is needed?
https://www.mozilla.org/en-US/firefox/features/translate/

**Comment by marco-c** [comment]
It hasn't been released yet, but we plan to release it soon. You can test it in the Nightly version of Firefox.
