### ISSUE TITLE
Firefox translate sometimes drops digits from numbers

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/firefox-translations#534]
Reported on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1797667

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:106.0) Gecko/20100101 Firefox/106.0

Steps to reproduce:

    Install Firefox Translate. I don't see a bug reporting option for it, so I'm using bug reporting for Firefox.

    Open in Firefox: http://swolkov.org/bdorg/bdorg08.htm#778

    Turn on Firefox translate

Actual results:

The Russian text includes:

К 5 июля насчитывали всего 244890 чел. (в т.ч. 23116 в штабах и управлениях и 23463 в гарнизонах), из которых 16765 офицеров (в т.ч. 4140 в штабах и управлениях и 1533 в гарнизонах), 167625 строевых (в т.ч. 4098 в штабах и управлениях и 14834 в гарнизонах), 28932 вспомогательных (в т.ч. 6320 в штабах и управлениях и 4926 в гарнизонах) и 31568 нестроевых (в т.ч. 8558 в штабах и управлениях и 2170 в гарнизонах) нижних чинов.

The English translation includes:

By July 5, there were only 24,490 people. (including. 23116 at the headquarters and management departments and 23463 in the garrisons), of which 16,765 officers (including 4140 at the headquarters and management departments and 1533 in the garrisons), 167625 combat (including 4098 at the headquarters and management departments and 14834 in the garrisons), 28932 auxiliary (including 6320, 6320 at the headquarters and management departments and 4926 in garrisons) and 31568 non-combustible (including the 8558 at the headquarters and management departments and 2170 in garrisons) lower ranks.

So 244890 becomes 24,490.

Expected results:

Firefox translate should not change numbers.

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842763.
