### ISSUE TITLE
Option to turn off the banner

### ISSUE THREAD

**Issue by christian179717** [mozilla/firefox-translations#535]
Hello,
it would be very nice if there was an option to permanently disable the banner under the address bar, as it is more often annoying than useful.

**Comment by kpu** [comment]
@christian179717 switch to https://addons.mozilla.org/en-US/firefox/addon/translatelocally-for-firefox/

**Comment by drzraf** [comment]
Yes, simply a button to translate when needed. Taking the screen all the time while I only use the extension 2% of the time is really inefficient (and a waste of resource, since language detection is ran for every tab I load)

**Comment by drzraf** [comment]
Would resolve
- https://github.com/mozilla/firefox-translations/issues/394
- https://github.com/mozilla/firefox-translations/issues/359
- https://github.com/mozilla/firefox-translations/issues/348
- https://github.com/mozilla/firefox-translations/issues/532 (duplicate)

**Comment by sylvestre** [comment]
Indeed, we have been discussing about what is next for this project and it will be clearly part of the roadmap.

**Comment by Janokisu** [comment]
I just noticed that there is already a button in the address bar to open the banner. That should be enough

**Comment by drzraf** [comment]
Cool. So it's only about opting out from the bar.

One caveat though, using the button, language is not autodetected by default

**Comment by andrenatal** [comment]
I'm planning a redesign of the whole interface with some other teams internally. There's no firm deadline about it yet, but it's in the books. The plan is to utilize a popup like other vendors do in the place of the notificationbox in the top.

**Comment by andrenatal** [comment]
I see some off-topic comments (now deleted) were posted to this thread. Please, before posting always pay attention to abide to the repo's code of conduct which is available here: https://github.com/mozilla/firefox-translations/blob/main/CODE_OF_CONDUCT.md

**Comment by piradix** [comment]
I vote for no translate banner by default. It is an UX error to show it permanently for site not in user language.
Don't forget, the user should always have the last word on an UX.
And can you add an expression to hide "for site". For example, no translation by default for "*.io"

Despite the annoying defect of being permanently displayed, this plus in is a "must", one last effort on the user interface and it will be perfect ;-)

If you want "tester" or UX appreciation, you can contact me.

**Comment by andrenatal** [comment]
I've added an option to prevent the translation bar from being displayed on #557 

<img width="234" alt="Screen Shot 2022-11-08 at 1 52 13 PM" src="https://user-images.githubusercontent.com/973388/200683783-50ba5713-0b10-42a4-a1b7-f5c43d94947c.png">

**Comment by acornestean** [comment]
@andrenatal

Testing version 1.2.0 of the extension revealed that the label of the “Never offer translations” is not displayed in the “Options” menu, regardless of the applied theme (either Light or Dark)

The option can be toggled on and off and it seems to work as intended in preventing the translation bar from being displayed though.

Tested on the latest Nightly 108.0a1 and Beta Developer Edition 107.0b9 on Windows 10 and macOS 11.3.1.

![2022-11-09_10h01_32](https://user-images.githubusercontent.com/50236075/200773485-f2988f51-2dfc-4303-acb9-9405a1d26a17.png)

**Comment by andrenatal** [comment]
@acornestean yes, the labels are missing in the build because https://github.com/mozilla-l10n/firefox-translations-l10n/pull/17 was never merged and then CI built the artifact without them

**Comment by acornestean** [comment]
> @acornestean yes, the labels are missing in the build because [mozilla-l10n/firefox-translations-l10n#17](https://github.com/mozilla-l10n/firefox-translations-l10n/pull/17) was never merged and then CI built the artifact without them

I'm guessing that this missing label will be fixed in the next artifact ?

**Comment by piradix** [comment]
Good news 👍 
I'm waiting for a release to test

For text translation in French : 
- "Never offer translations" =FR=> "Ne pas proposer de traduction"

But other text can be use :
- "Never default translations" =FR=> "Pas de traduction par défaut"
- "hide by default" =FR=> "Cacher par défaut"

**Comment by acornestean** [comment]
Verified as Fixed in the latest Nightly 1.2.0.

Tested on the latest Firefox Nightly 108.0a1 and Beta Developer Edition 107.0b9 under Windows 10, Ubuntu 16.04 LTS and macOS 11.3.1.

The label for the “Never offer translations” is now properly displayed in the “Options” menu. The function can be properly enabled/disabled and works as intended.

![2022-11-10_11h01_11](https://user-images.githubusercontent.com/50236075/201046866-d30aeb42-8777-4322-a3c8-d89215b11311.png)

**Comment by piradix** [comment]
It work fine on  : Windows 11 Pro French, Firefox Dev 107.b08
good job
see image
![Firefox 2022-11-10 170031](https://user-images.githubusercontent.com/64977993/201144609-a73debdd-b3b9-4f91-a06b-0159a620db77.png)

**Comment by antoinebj** [comment]
In the meantime is there an option to make that bar shown permanently?
I don't even mind the screen estate used. By far my main issue with it is that it shifts the entire page down after it has been loaded, which is too often as I'm about to click on something. And since it also shifts the side bar down, it creates usability problems with Tree Style Tab and possible other side bars.

**Comment by christian179717** [comment]
After the new update it's not possible to open the translater for the webpage by the add-on icon.
![grafik](https://user-images.githubusercontent.com/89655752/215538604-17f53720-57aa-419d-aac6-d0e232d08f8f.png)
Would it be possible to fix it e.g. add a button in the button of the window: "Translate the Website"?

**Comment by Janokisu** [comment]
@christian179717
what do you mean? there it is (?) 

![grafik](https://user-images.githubusercontent.com/54418395/215544909-2f2b7c28-32b5-4eef-8ac7-36978fca1312.png)

**Comment by andrenatal** [comment]
@christian179717 you should be able to open the translation option by clicking on this icon in the url bar

<img width="1284" alt="Screenshot 2023-01-30 at 11 55 24 AM" src="https://user-images.githubusercontent.com/973388/215581607-fcb3e5e5-2d8a-4343-b3da-64df8328c8f6.png">

**Comment by christian179717** [comment]
> @christian179717 you should be able to open the translation option by clicking on this icon in the url bar
> 
> <img alt="Screenshot 2023-01-30 at 11 55 24 AM" width="1284" src="https://user-images.githubusercontent.com/973388/215581607-fcb3e5e5-2d8a-4343-b3da-64df8328c8f6.png">

Forgot about that :facepalm:

**Comment by andrenatal** [comment]
No problem, I'm glad to help.
