### ISSUE TITLE
No "Never translate language xy" option on macOS

### ISSUE THREAD

**Issue by orthand** [mozilla/firefox-translations#556]
**Describe the bug**
The "Never translate language xy" option is not properly visible on macOS. There is only a thin clickable line but it's not with text as on my Windows machine.

**To Reproduce**
1. Go to page with different language or open via the context menu
2. Click on 'Options'

**Expected behavior**
Under "Never translate this site" the following option "Never translate language xy" is displayed with text.

**Screenshots**
<img width="206" alt="image" src="https://user-images.githubusercontent.com/62552927/200598221-00546674-4001-4fed-b673-fcc63dd9746e.png">
The blue line is only visible if hovering directly over it. Usually it looks like this:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/62552927/200601917-4b18f1fa-99e6-4450-b033-390c0ee38d2b.png">

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 106.0.5
- Processor information: M1 Pro
- OS version: macOS Monterey 12.6
- System type (32-bit or 64-bit): arm64
- Firefox Translation Extension version: 1.1.4buildid20220803.111909
- Webpage on which issue was observed: any / e.g. amazon.es

**Additional context**
- I've disabled most of my other extensions to test if those are the culprit but have seen no changes (on macOS). On Windows the option is always displayed independently of my extensions.
- The line separator is not inverted to white in dark mode/theme. Same settings and theme result in a white line on Windows.

**Comment by andrenatal** [comment]
Thanks for reporting it. This issue was fixed in the latest version that is
expected to be released in the next few days.
