### ISSUE TITLE
“We found an error loading the translation engine” and translation does not proceed with several languages

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#561]
**Describe the bug**
Attempting to translate to Icelandic (Beta), Norwegian Bokmal or Norwegian Nynorsk (Beta) throws an error in the translation bar - “We found an error loading the translation engine” and the translation does not proceed.

**To Reproduce**
1. Install the 1.2.0 version of Firefox Translations (https://github.com/mozilla/firefox-translations/releases/tag/nightly)
2. Go to https://es.wikipedia.org/wiki/Wikipedia:Portada
3. Once the translations bar is displayed, from the target language drop down, select Icelandic (Beta), Norwegian Bokmal or Norwegian Nynorsk (Beta)
4. Click the “Translate” button
5. Observe that the translations bar displays “We found an error loading the translation engine” and translation does not proceed

**Expected behavior**
The extension should be able to translate to the above target languages without encountering any errors.

**Screenshots**
![2022-11-09_10h08_22](https://user-images.githubusercontent.com/50236075/200776405-24fef136-3f22-4623-8624-8873760a1022.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: Nightly 108.0a1, Beta Developer Edition 107.0b9
- OS version: Windows 10, macOS 11.3.1
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.2.0

**Additional context**
Translating a page in Icelandic (Beta), Norwegian Bokmal or Norwegian Nynorsk (Beta) to any other language except the mentioned ones, works.

**Comment by acornestean** [comment]
Verified as Fixed in the latest Nightly 1.2.0 as per the specifications of #566. Tested on the latest Firefox Nightly 108.0a1 and Beta Developer Edition 107.0b9 under Windows 10, Ubuntu 16.04 LTS and macOS 11.3.1.

Unsupported languages have been removed form the languages dropdown i.e. Icelandic (Beta), Norwegian Bokmal and Norwegian Nynorsk (Beta) have been removed from the target language dropdown and as such, the error can no longer occur.

![2022-11-10_10h21_14](https://user-images.githubusercontent.com/50236075/201043163-4d42e256-7518-4a56-9da1-0a0d1968802a.png)

**Comment by drzraf** [comment]
I'm getting this error for every pages with `1.2.0buildid20221114.185738`. Then only, when I reload, it works.
I'm also getting the error for all English pages (I guess, because my browser is set to English)
