### ISSUE TITLE
Popup translation page target (right) language selector is missing several languages

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#562]
**Describe the bug**
The target language selector (on the right) of the translation popup page is missing the following languages: Icelandic (Beta), Norwegian Bokmal, Norwegian Nynorsk (Beta).

These languages can be found, though, on the source language selector (on the left).

Thus, pasting a text in Norwegian Bokmal, for example, in the source field and selecting English in the target field will produce a translation as expected. But switching the languages will leave a source language field with the prior English translation and an empty target language field.

**To Reproduce**
A.
1. Install the 1.2.0 version of Firefox Translations (https://github.com/mozilla/firefox-translations/releases/tag/nightly)
2. Go to https://es.wikipedia.org/wiki/Wikipedia:Portada
3. Click on the extension toolbar icon to display the popup translation page
4. Check the source language selector and the target language selector
5. Notice that the target language selector is missing Icelandic (Beta), Norwegian Bokmal and Norwegian Nynorsk (Beta), which do appear in the source language selector

https://user-images.githubusercontent.com/50236075/200784885-ffeb656c-2118-4ea0-b131-b26ae1d0e9c8.mp4

B.
1. Access https://no.wikipedia.org/wiki/Portal:Forside (page in Norwegian Bokmal)
2. Copy some text from the page and paste it in the source language field in the popup translation page
3. Set the source language to Norwegian Bokmal and the target language to English
4. Wait for the translation to finish
5. Switch the source and target languages between them via the “↔” button
6. Notice that the source field now contains the previous English translation, but the target field is empty

https://user-images.githubusercontent.com/50236075/200784971-fd6d04c5-acdd-46f3-bfdd-64ecfe2359ed.mp4

**Expected behavior**
A. Source and target language selectors should contain the same languages
B. Source and target language selectors should contain the same languages and thus allow translations to go both ways

**Desktop (please complete the following information as possible):**
- Firefox Browser version: Nightly 108.0a1, Beta Developer Edition 107.0b9
- OS version: Windows 10, macOS 11.3.1
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.2.0

**Comment by andrenatal** [comment]
Hi Alex, this is actually the expected behavior and the reason is because we have models from Icelandic, Norwegian Bokmal, Norwegian Nynorsk to other languages, but not for other languages to Icelandic, Norwegian Bokmal, Norwegian Nynorsk, thus we can translate **_from_** them but not **_to_** them
