### ISSUE TITLE
Slight difference in arrow size and positioning between Beta 107 and Nightly 108

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#564]
**Describe the bug**
The arrow located between the language pairs on the translations bar is slightly bigger and positioned lower on Beta compared to Nightly.
The translations bar is a bit taller on Beta than on Nightly and that might cause the difference in positioning and size. And also be the root cause of the issue.

**To Reproduce**
1. Install the 1.2.0 version of Firefox Translations on both the latest Nightly 108 and Beta Developer Edition 107 (https://github.com/mozilla/firefox-translations/releases/tag/nightly)
2. Go to https://es.wikipedia.org/wiki/Wikipedia:Portada on both browser editions
3. Notice the translation bar appears and shows the language pair currently in use and an arrow between them.
4. Take notice of the arrow and switch between the browsers.
5. Observe the arrow on Beta is bigger and slightly lower than on Nightly, possibly due to the difference in translation bar height between the browsers.
6. Translate the page on both browsers and repeat steps 3 to 5.

**Expected behavior**
The translation bar height, arrow position and size should be consistent across all browsers.

**Screenshots**

https://user-images.githubusercontent.com/50236075/200846000-a5296c27-b786-4cb5-ac50-9e92ba79dea3.mp4

https://user-images.githubusercontent.com/50236075/200846056-e8c7c789-6785-470b-bfc0-3102e80d2e33.mp4

**Desktop (please complete the following information as possible):**
- Firefox Browser version: Nightly 108.0a1, Beta Developer Edition 107.0b9
- OS version: Windows 10, macOS 11.3.1
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.2.0

**Comment by andrenatal** [comment]
Hi Alex, this is the expected behavior and exists due the underlying xul engine and it was supposedly addressed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1796698#c2. There's nothing we can and should do in the addon to change it.
