### ISSUE TITLE
[Suggestion] Improve UI for free from translation popup

### ISSUE THREAD

**Issue by Fanolian** [mozilla/firefox-translations#568]
**Is your feature request related to a problem? Please describe.**
I didn't read the [v1.2 changelog](https://github.com/mozilla/firefox-translations/commit/40c98b72f44a10455a3c83c22d1f052dcaba9d73) so I didn't know what the new toolbar icon was for. I thought it worked just like the URL bar icon (because icons are the same except colours), i.e. to select the page language and target language, then press `Translate` in the popup to translate the page. Turns out I can type anything in the text area to get a translation 👏. It would be great if there are more indications/instructions within the popup.

**Describe the solution you'd like**
Add an input placeholder text in the source language text area, such as "Enter text for translation…" or "Translate this text…". Placeholder for target language may be optional.

**Describe alternatives you've considered**
1. Change the text "Translate" below text areas to the suggested placeholder wordings. I thought "Translate" was a (poorly-designed...) button to click on.
2. Add a heading for the popup. But I think "Translate" at the bottom is supposed to be the heading, before it changes context?
3. Change the toolbar icon and/or tooltip to differentiate from URL bar icon.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
