### ISSUE TITLE
[Suggestion] Convert `Never translate [lang]` into a toggle

### ISSUE THREAD

**Issue by Fanolian** [mozilla/firefox-translations#570]
**Is your feature request related to a problem? Please describe.**
~v1.1.4 or 1.2 `Never translate [lang]` adds a language, even if added previously, to the exception list but does not remove the language when it is clicked again.~ 

On v1.2 when a language is already added to the exception list, `Never translate [lang]` is greyed out. Users have to click `Translation preferences` > `Exceptions` > `Remove language` instead.

**Describe the solution you'd like**
I suggest converting this option into a toggle, à la `Never translate this site`.

**Describe alternatives you've considered**
None

Update: edit my problem stated above after more testings on v1.2.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).
