### ISSUE TITLE
Settings doesn't show all options

### ISSUE THREAD

**Issue by Naxterra** [mozilla/firefox-translations#571]
**Describe the bug**
When I click on Settings (Einstellungen), it shows only the partial text.

**To Reproduce**
1. Go to Settings on top bar, below the favs.
2. Click on Setitings
3. Try to scroll down

**Expected behavior**
It should show all available options.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/41871948/201486392-5f7ef3c8-5cc5-46c4-a162-eecde0335012.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 106.0.5
- Processor information: i9 10900KF
- OS version: Windows 11
- System type (32-bit or 64-bit): x64
- Firefox Translation Extension version: 1.1.4buildid20220803.111909
- Webpage on which issue was observed: Every webpage
- Language of the webpage: English
- Translating to (language): German
- Console logs from Web Developer Tools: 

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category
application.architecture 	x86-64 
cpu.extensions 	[hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSSE3, hasSSE4_1, hasSSE4_2, hasAVX, hasAVX2, hasAES] 

**Additional context**

**Comment by andrenatal** [comment]
This was fixed in the current release 1.2.0 and is only waiting for the review step to be completed in order to be released to the public.
