### ISSUE TITLE
Replace `innerHTML` by safer and more performant methods

### ISSUE THREAD

**Issue by wagnerand** [mozilla/firefox-translations#573]
https://github.com/mozilla/firefox-translations/blob/7c7f4fc667eee7b04b8e9a7ec85b2fb3e5501461/extension/view/popup/js/index.js#L82 and https://github.com/mozilla/firefox-translations/blob/7c7f4fc667eee7b04b8e9a7ec85b2fb3e5501461/extension/view/popup/js/index.js#L87 should be refactored into [safe DOM manipulation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page) that does not evaluate strings as code.

**Comment by Rob--W** [comment]
> should be refactored into [safe DOM manipulation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page) that does not evaluate strings as code.

This is sound advice in general; in this specific case the `Option` constructor would be a better fit, and the (updated) PR #630 does use that now.
