### ISSUE TITLE
'Never translate [language]' option is hidden in 'translations bar'

### ISSUE THREAD

**Issue by notDavid** [mozilla/firefox-translations#574]
**Describe the bug**
1. My browser language is set to English
2. I go to a German website: https://www.spiegel.de/
3. I do **not** see the option 'Never translate German'

**To Reproduce**
The problem turns out to be: the menu item is there, however, it is hidden because it's  only a few pixels in height, so you can not see it and barely click it. When you hover the mouse over it, you will see a blue line, which is the missing menu item: See the attached screenshot. Clicking the blue line works.

**Screenshots**

![Screenshot 2022-11-15 at 09 13 30](https://user-images.githubusercontent.com/1530401/201867321-e62a0628-13de-4775-ac52-2f74695d8455.png)

![Screenshot_2022-11-15_at_09_13_46](https://user-images.githubusercontent.com/1530401/201867346-6c98ea8a-9e8f-4df1-9571-17e9279dac79.png)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: `106.0.5 (64-bit)`
- Processor information: `macOS M1`
- OS version: `macOS Ventura 13.0.1 (22A400)`
- System type (32-bit or 64-bit): `64-bit`
- Firefox Translation Extension version: `1.1.4buildid20220803.111909`
- Webpage on which issue was observed: https://www.spiegel.de/
- Language of the webpage: German
- Translating to (language): -
- Console logs from Web Developer Tools: -

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category
`Your organization has blocked access to this page or website`

**Comment by cadeyrn** [comment]
It's fixed in Firefox Translations 1.2.0 that should be available soon.
