### ISSUE TITLE
Empty menu of target languages in toolbar

### ISSUE THREAD

**Issue by jerome-tgl** [mozilla/firefox-translations#575]
**Describe the bug**
Empty menu of target languages in toolbar

**To Reproduce**
1. Go to a page in a supported language
2. Select the source language
3. Click on the picker for target language
4. Dropdown menu does not open or is empty

**Expected behavior**
Clicking the picker should reveal a dropdown menu with the list of supported target language

**Screenshots**
<img width="993" alt="Screenshot 2022-11-16 at 12 20 44" src="https://user-images.githubusercontent.com/8667221/202167971-a22b9d2b-e179-466d-9f77-353ba9466a0e.png">

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 106.0.5
- Processor information: Intel Core i5 [hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSSE3, hasSSE4_1, hasSSE4_2, hasAVX, hasAVX2, hasAES] 
- OS version: Mac
- System type (32-bit or 64-bit): x86-64
- Firefox Translation Extension version: 1.2.0buildid20221114.185738
- Webpage on which issue was observed: https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal
- Language of the webpage: French
- Translating to (language): Any
- Console logs from Web Developer Tools: Nil

**Additional context**

**Comment by kneirinck** [comment]
A workaround I found was downgrading to 1.4.
You can even upgrade again to 2.0 and as long as you don't restart your browser it'll keep working with all 2.0 features included.

**Comment by cadeyrn** [comment]
What versions are you referring to? The current version is 1.2.0, the previous one was 1.1.4. There is neither a version 1.4 nor a version 2.0.

**Comment by kneirinck** [comment]
> What versions are you referring to? The current version is 1.2.0, the previous one was 1.1.4. There is neither a version 1.4 nor a version 2.0.

my bad I meant 1.1.4 and 1.2.0, edited post above

**Comment by sha-265** [comment]
Same bug with FF 107.0 on Linux.

**Comment by blancho2** [comment]
Same bug with FF 107.0 (french) on Windows 10 22H2

**Comment by blancho2** [comment]
°° With the new version FF107.0.1 (and Windows 10 22H2) everything works fine now...

°°  Another question : is Firefox translation compatible with Windows 7 SP1 32bits (and FF107.0.1 32bits), because it does not work on my PC ???

**Comment by Forage** [comment]
I can confirm that the update from 107.0.0 to 107.0.1 fixed the issue for me on Ubuntu 22.10.

**Comment by cadeyrn** [comment]
I doubt that a change between Firefox 107.0.0 and 107.0.1 fixed the issue because none of these changes should affect this. And a few days ago I saw the same issue in Firefox 107.0.0. It was "fixed" by uninstalling and installing the add-on again.

**Comment by sha-265** [comment]
> I can confirm that the update from 107.0.0 to 107.0.1 fixed the issue for me on Ubuntu 22.10.

Same here with FF 107.0.1 on Ubuntu 22.04.

**Comment by blancho2** [comment]
I did not uninstall/reinstall firefox translation...
I just upgraded to the new version of firefox !!!

**Comment by andrenatal** [comment]
Thanks for reporting this. I assume that simply restarting the browser is not fixing it, right?

**Comment by sha-265** [comment]
> Thanks for reporting this. I assume that simply restarting the browser is not fixing it, right?

@andrenatal, nope.

**Comment by andrenatal** [comment]
Is anyone still seeing this error? I assume that was related to some lingering cache that should be gone by now.
