### ISSUE TITLE
Buttons size doesn't adapt to the text size in the toolbar

### ISSUE THREAD

**Issue by roundoutandabout** [mozilla/firefox-translations#576]
When setting a custom font size in the system, the text of the buttons doesn't fit into the buttons.
On the screenshot it is seen that the text "Translate" and "Options" don't fit.
It looks like the buttons don't expand down to fit the text, while the space allows it.

**To Reproduce**
1. Set font size to 14pt in: System Settings > Appearance > Fonts > Adjust All Fonts
2. Run Firefox with the extension enabled
3. Go to the website in foreign language

**Observed behavior**
Buttons in the popup toolbar of the extension do not adjust to the text size

**Expected behavior**
Buttons in the popup toolbar of the extension adjust to the text size

**Desktop:**
- Firefox Browser version: 107.0
- OS version: Manjaro Linux
- Desktop version: KDE Plasma 5.26.3
- System type: x86-64 
- Firefox Translation Extension version: 1.2.0buildid20221114.185738

![image](https://user-images.githubusercontent.com/15846984/202284216-205f2428-48a7-4e2e-a976-3c2307a2ca37.png)

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
