### ISSUE TITLE
Automatic translation of browser panel not working when 'Never offer translations' option is checked

### ISSUE THREAD

**Issue by Zechiax** [mozilla/firefox-translations#577]
**Describe the bug**
Automatic translation of the browser panel is not automatically translating the page after you click a link or go to another URL which reloads the page

**To Reproduce**
1. Have the 'Never offer translations' settings toggled on
2. Go to '[https://www.mozilla.org/en-US/](https://www.mozilla.org/en-US/)' (or any other site)
3. Click on the Firefox translations button in toolbar
4. Select any valid combination of languages to translate to
5. Click translate
6. Select the option to automatically translate the content of this panel during browsing
7. Manually refresh the page, click any link or go to different site
8. The page won't get translated again, until you press the Firefox Translations button, which will translate immediately with the previously selected languages
 
**Expected behavior**
The page should be translated automatically as if the 'Never offer translations' option is unchecked without having to click the Firefox Translations button

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 106.0.4
- Firefox Translation Extension version: 1.2.0 buildid: 20221104095936 
- Webpage on which issue was observed: Any translatable page
- Language of the webpage: Any
- Translating to (language): Any

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
