### ISSUE TITLE
Arrow in the translation bar is not centered

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#581]
**Describe the bug**
The arrow that shows translation direction in the translation bar is not centred and looks pretty bad

**To Reproduce**
1. Go to any website to translate
2. Press "translate"
3. Observe how the arrow that indicates translation direction is way off

**Expected behavior**
The arrow is nicely centred and looks visually pleasant

**Screenshots**
<img width="662" alt="Screen Shot 2022-11-19 at 7 14 58 PM" src="https://user-images.githubusercontent.com/2486505/202881272-f35d8605-c00a-4dab-a3b3-5d59667d75b4.png">
<img width="601" alt="Screen Shot 2022-11-19 at 7 14 41 PM" src="https://user-images.githubusercontent.com/2486505/202881275-87ce8744-e965-4f66-a0b5-b4930c6727c3.png">

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 107 (Release)
- Processor information: 2.4 GHz 8-Core Intel Core i9
- OS version: MacOS 12.6
- System type (32-bit or 64-bit): 	x86-64
- Firefox Translation Extension version: 1.2.0buildid20221114.185738
- Webpage on which issue was observed: https://www.pravda.com.ua/news/2022/11/19/7377104/
- Language of the webpage: Ukrainian
- Translating to (language): English

**Comment by andrenatal** [comment]
<img width="684" alt="Screenshot 2022-12-02 at 8 43 02 PM" src="https://user-images.githubusercontent.com/973388/205423914-92e07ba8-f938-4b49-a542-9bcd94db9a4f.png">
 
I can reproduce this on 107 but not on 108+ 🤷‍♂️. This XUL widget is very brittle, as you know :(. Hopefully this UI will be retired in the next version.
