### ISSUE TITLE
Support Chinese translations

### ISSUE THREAD

**Issue by tyuhao** [mozilla/firefox-translations#583]
There are probably about 15 million Firefox users in China.I hope this project can add other languages to the Chinese translator.Google Translate is not available in China  now, and if Firefox adds a Chinese translation, it will make Firefox more competitive and increase the number of users.

**Comment by sylvestre** [comment]
Yeah, it might take a while but it is clearly on our roadmap

**Comment by cnmade** [comment]
+1 please

**Comment by miracle859** [comment]
if Firefox adds a Chinese translation, it will make Firefox more competitive and increase the number of users.

**Comment by benjamin051000** [comment]
Please!

**Comment by marco-c** [comment]
We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
For example, [here's the Chinese request](https://connect.mozilla.org/t5/ideas/support-chinese-translations/idi-p/33405).

**Comment by WinstonSung** [comment]
As the comments [1] posted on Mozilla Connect [2] were rejected without any actual reason given in the guideline [3],
I'm just going to post them here as references:

> As a MediaWiki Language Converter developer & MozTW community member:
> 
> ----
> 
> Support the idea, but:
> 
> > Chinese translations
> 
> Is this referring to
> 
> * zh-Hans / zh-Hans-CN / zh-CN - Simplified Chinese (Mandarin, Simplified Han script),
> * zh-Hant / zh-Hant-TW / zh-TW - Traditional Chinese (Mandarin, Traditional Han script),
> * zh-Hant-HK / zh-HK - Traditional Chinese - Hong Kong (Mandarin, Traditional Han script, Hong Kong terms),
zh-Hans + zh-Hant,
> * or all of them?
> 
> ----
> 
> > I think this is quite simple because the conversion between Simplified Chinese and Traditional Chinese is a very mature technology.
> 
> Negative.
> 
> There are too much 1-to-multiple character & term conversions,
even the Language Converter for Wikipedia-zh cannot always handle them correctly and need many manual fixes.
> 
> See "Manual conversion rules" on Wikipedia-zh and the existence of "Module:NoteTA", "Module:CGroup/*" in many pages.

* \[1]: https://connect.mozilla.org/t5/premod/moderationitemspage/tab/rejected:idea
* \[2]: https://connect.mozilla.org
* \[3]: https://connect.mozilla.org/t5/ideas/ideas-guidelines/idi-p/6

**Comment by marco-c** [comment]
@WinstonSung thanks, the comments were only temporarily rejected by our automated system by mistake, they are visible now.

**Comment by WinstonSung** [comment]
I'd say please:

* "not to auto reject comments", and/or
* "add a 'auto-rejected, manual review later' label", and/or
* "add 'rejected reason: <guideline article>' explanation", and/or
* "add a 'revisit current review result' button"

as that ***really*** make new-registered already-community-member members quite frustrating.

**Comment by ddkwork** [comment]
English 2 Chinese can support？
