### ISSUE TITLE
Menu with language list misaligned

### ISSUE THREAD

**Issue by TheBlinded** [mozilla/firefox-translations#585]
**Describe the bug**
I am talking about the translation window that opens from the toolbar.
When I go to open the menu to change the language, the first time the menu often appears completely misaligned.
From the second/third click onwards, while the window is open, it opens correctly. The problem recurs when I open the translation window again.

**To Reproduce**
1. Open translation window from the toolbar icon
2. Open one of the two language selection menus (left or right)
3. Close and reopen the window and try again.

**Expected behavior**
Menu with language list aligned

**Screenshots**
![Schermata 2022-11-23 alle 23 28 59](https://user-images.githubusercontent.com/5796668/203657848-5f68d11a-1149-4a77-be5a-55ee70f00aea.jpg)
![Schermata 2022-11-23 alle 23 21 28](https://user-images.githubusercontent.com/5796668/203657857-3dd4b07c-2b7f-42cc-8234-636ebc52468c.jpg)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 107.0
- Processor information: Intel i7 4th, Intel Iris Pro, AMD Radeon R9 M370X
- OS version: MacOS 12.6.1
- Firefox Translation Extension version: 1.2.0buildid20221114.185738

**Comment by andrenatal** [comment]
This is very strange. Don't even know how to reproduce.

**Comment by TheBlinded** [comment]
The problem only occurs when using external mouse (usb or bluetooth, I tried three)

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
