### ISSUE TITLE
The more you click the translate icon the more translation bars appear

### ISSUE THREAD

**Issue by bmm-alc** [mozilla/firefox-translations#586]
**Describe the bug**
a translation appears each time you click the icon in the url bar

**To Reproduce**
1. click on the translation icon
2. a translation bar appears
3. repeat from step 1 ad libitum

**Screenshots**
[Screencast from 2022-11-24 07-07-19.webm](https://user-images.githubusercontent.com/80455946/203707162-f12f0b9b-6a13-4f42-ae8e-6f39a1482add.webm)

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 106.0.4
- Processor information: 
- OS version: Fedora 37
- System type (32-bit or 64-bit): 64
- Firefox Translation Extension version: 1.2.0buildid20221114.185738
- Webpage on which issue was observed: anyone
- Language of the webpage: does not matter
- Translating to (language): does not matter
- Console logs from Web Developer Tools: -

**Comment by andrenatal** [comment]
@bmm-alc is this still happening for you? Maybe you could have it normalized after you restart the browser. 

This issue was observed some time ago due the nature of the notificationBox API. The plan is to retire this UI in the next version so this won't happen again.
