### ISSUE TITLE
[Suggestion] Hide translation bar on scrolling 

### ISSUE THREAD

**Issue by MSmolarz** [mozilla/firefox-translations#589]
Hello,
is it possible to add the function to hide the translation bar on a non-translated page, e.g. when I scroll, so that it is only shown again when I click on the button in the title bar?
And on a translated page, hide it when scrolling down and show it again when scrolling up or mouse over?
Thanks
Mark

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
