### ISSUE TITLE
Timeout while downloading translations engine on low speed internet connection

### ISSUE THREAD

**Issue by mahlzahn** [mozilla/firefox-translations#591]
**Describe the bug**
Some translations don’t work because of a timeout downloading the translations engine (download starts but does not finish)

**To Reproduce**
1. Go to some website in foreign language
2. Click on translate
3. Wait while downloading (there is a counter)
4. At some point the download stops and error message comes in the header: something like: “While loading the translations engine an error happened” (freely translated from German)
5. When reloading the site/translation the download starts again from zero and again up to step 4.

**Expected behavior**
Firstly, full download and then translation. Secondly, continue download from where it stopped at next trial.

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 106.0.4 (64-Bit)
- Processor information: Not checked
- OS version: 5.10.151-1-MANJARO
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.2.0buildid20221114.185738
- Webpage on which issue was observed: any website
- Language of the webpage: tried English, Italian
- Translating to (language): German
- Console logs from Web Developer Tools: Not checked

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).
