### ISSUE TITLE
 modern flexbox in the browser toolbox causes small layout issues for Firefox Translations in Firefox 108+

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/firefox-translations#592]
_Also filed as [BZ-1802722](https://bugzilla.mozilla.org/show_bug.cgi?id=1802722)._

[BZ-1790616](https://bugzilla.mozilla.org/show_bug.cgi?id=1790616) caused some small layout issues with the translation bar of Firefox Translations.

I attached a screenshot for comparison of Firefox 107 and Firefox 108. I don't know why the second dropdown is empty in the Firefox 108 screen. Maybe another bug, maybe an issue in my profile, let's ignore that for now.

<img width="1728" alt="fxtranslations" src="https://user-images.githubusercontent.com/1100614/204111387-47cbf331-76f9-4e73-afd5-8458415c4912.png">

1. The blue button to start the translation was well aligned with the language selection fields in Firefox 107. In Firefox 108 it's no longer the case.

2. The close button had some space to the right end of the toolbar. It's no longer the case in Firefox 108.

3. Bonus: The blue arrow is better positioned than before but still not perfectly centered. While we are at it, maybe it could be positioned better?

4. Bonus: The whole content of the toolbar is not exactly vertically centered. But this was already the case before the change in [BZ-1790616](https://bugzilla.mozilla.org/show_bug.cgi?id=1790616). Again, while we are at it, it may be worth a look.

**Comment by marco-c** [comment]
We are not going to make any improvements to the addon since we are now focusing on the built-in version.
