### ISSUE TITLE
Please add Indonesian language support

### ISSUE THREAD

**Issue by Reno-Sifana** [mozilla/firefox-translations#593]
I will be very happy if in the future the Firefox Translations extension adds Indonesian language support in a future release.

**Comment by marco-c** [comment]
We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
For example, [here's the Indonesian request](https://connect.mozilla.org/t5/ideas/support-indonesian-translations/idi-p/33412).

**Comment by Reno-Sifana** [comment]
> We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
> For example, [here's the Indonesian request](https://connect.mozilla.org/t5/ideas/support-indonesian-translations/idi-p/33412).

Okay.
