### ISSUE TITLE
Add the feature to translate the content of a page without using the new popup

### ISSUE THREAD

**Issue by timotheejulien** [mozilla/firefox-translations#596]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have the old feature that translating the content of the page without copying the content to the new popup. 

**Describe alternatives you've considered**
In other word, I would like the same feature as Safari or Google Chrome

**Additional context**
I think my request was a old  implemented feature.

**By the way, thank you for you incredible work! 🙏🏻**

**Comment by cadeyrn** [comment]
With "content of a page" you mean some selected parts of a page? Because a full page translation is already the main feature of Firefox Translations. Then it's a duplicate of #590.

>  I would like to have the old feature […] I think my request was a old implemented feature.

what does "old" refer to?

**Comment by timotheejulien** [comment]
By "content of a page" I mean all the text inside the page. Maybe I don't find how to do it but now when I'm clicking on the icon of the extension I only have this popup (image below) and I have to copy and past the text of the page inside the popup.

I may missing something…

![FirefoxTranslations](https://user-images.githubusercontent.com/7768843/204770891-74c09c81-07b3-4a8c-a249-dbabf0fb22e8.png)

**Comment by cadeyrn** [comment]
> By "content of a page" I mean all the text inside the page.

To translate the complete website you have to use the icon in the address bar, not the toolbar button. I agree that it can be a bit confusing to have two different buttons now. But I am not sure what a better user experience would look like.

**Comment by timotheejulien** [comment]
Thank you for your help !
