### ISSUE TITLE
The Arrows on the Button in the middle of the poup-windows are too smal

### ISSUE THREAD

**Issue by wheelseal** [mozilla/firefox-translations#601]
**Is your feature request related to a problem? Please describe.**
For some people the Arrow on the button in the middle of the popup-window can be difficult to see.

**Describe the solution you'd like**
Make the Arrow bigger.

It is also important for people who are impaired in seeing.

![Arrow](https://user-images.githubusercontent.com/61382908/204852987-e4e6fe94-be82-4acd-963e-2b948424712c.jpg)

On the picture you see the original button on the left and my idea on the right. You see my button is wider and the double-Arrow is bigger and so, I think, better to see.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
