### ISSUE TITLE
`translate` class ignored after seeing `notranslate`

### ISSUE THREAD

**Issue by jelmervdl** [mozilla/firefox-translations#607]
**Describe the bug**
Elements with a `notranslate` class are ignored by `InPageTranslation`. Websites like Mastodon also [seem to use this](https://github.com/mastodon/mastodon/commit/7d0031a515a9ccd552fab9ad55b6edb7e0e5ba32) to get around issues with Google Translate. However, they also mark elements that they _do_ want translated with a `translate` class. Firefox Translations ignores that class at the moment.

**To Reproduce**
Have a page with something like this:
```html
<p class="notranslate">
  Könnte es dieses Element bitte ignorieren?
  <span>Das wäre toll.</span>
  <span class="translate">Aber bitte übersetzen Sie diesen Satz.</span>
</p>
```

If you translate that page then with Google Chrome, only the last sentence will be translated. If you translate it with Firefox Translations, it doesn't.

**Expected behavior**
Translate elements that are marked with `class="translate"` when they appear inside an `class="notranslate"` or `translate="no"` element.

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 107.0
- Processor information: Intel x86
- OS version: macOS 13.0.1
- System type (32-bit or 64-bit): 64bit
- Firefox Translation Extension version: 1.2.0buildid20221114.185738
- Webpage on which issue was observed: Any up-to-date Mastodon instance
- Language of the webpage: n/a
- Translating to (language): n/a
- Console logs from Web Developer Tools: n/a

**Additional context**
I haven't been able to find any documentation for Google Translate that says that `class="translate"` should work. But empirically it does.

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842814.
