### ISSUE TITLE
Greek support

### ISSUE THREAD

**Issue by nose-gnome** [mozilla/firefox-translations#610]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like there to be Greek support.  Allowing you to translate Greek pages or Greek words via the add-on

**Describe alternatives you've considered**

**Additional context**

**Comment by nose-gnome** [comment]
Are there any further updates on this?  Is this likely to be added?

**Comment by sylvestre** [comment]
no update yet but if you are aware of a database like https://github.com/Softcatala/parallel-catalan-corpus
please let us know

**Comment by marco-c** [comment]
We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
For example, [here's the Greek request](https://connect.mozilla.org/t5/ideas/support-greek-translations/idi-p/33410).
