### ISSUE TITLE
Mozilla Thunderbird support

### ISSUE THREAD

**Issue by nose-gnome** [mozilla/firefox-translations#613]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

It would be great if you could add Firefox translations to Thunderbird add-on store/Thunderbird, so it could translate emails or sites when you occasionally open a site (which you can do when looking at an RSS update)

**Describe alternatives you've considered**

**Additional context**

**Comment by sylvestre** [comment]
Dup of https://github.com/mozilla/firefox-translations/issues/512
