### ISSUE TITLE
"Changelog" is hard-coded and can't be translated

### ISSUE THREAD

**Issue by flodolo** [mozilla/firefox-translations#616]
https://github.com/mozilla/firefox-translations/commit/74414b03e0a4a5d124db701b84938b4491afcab8#diff-81901678c906287a3078cb9fed17c9942b15df4a8f613a8172dafbae86b2c438

The string should be exposed for localization, currently it's hard-coded in English.

**Comment by sylvestre** [comment]
As it will merge in tree, I think we will use firefox release notes and not use that file anymore.
So, probably wontfix
