### ISSUE TITLE
Finnish language support

### ISSUE THREAD

**Issue by mkndn** [mozilla/firefox-translations#623]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add support for translating Finnish websites to other languages.

**Describe alternatives you've considered**
No other translation plugins available for android. Tried some plugins for desktop but nothing works good, especially concerned about privacy.

**Comment by mkndn** [comment]
Any update on this please?

**Comment by sylvestre** [comment]
No, we aren't working on it currently. It will take some time

**Comment by marco-c** [comment]
We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
For example, [here's the Finnish request](https://connect.mozilla.org/t5/ideas/support-finnish-translations/idi-p/33408).
