### ISSUE TITLE
Translate button seems to be invisible until clicked

### ISSUE THREAD

**Issue by amadeusjustinn** [mozilla/firefox-translations#624]
**Describe the bug**
The Translate button appears to have some transparent text that cannot be spotted until the button is clicked.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use light mode and any language except for French on Firefox.
2. Go to https://mes-pronoms.vercel.app/.
3. Wait for pop-up at the top of the window.

**Expected behavior**
The Translate button should have legible text.

**Screenshots**

https://user-images.githubusercontent.com/67861264/209984320-509e4258-5a9c-4e81-a0b1-92ecabb50d50.mov

**Desktop:**
- Firefox Browser version: 108.0.1 (64-bit)
- Processor information: 2.4 GHz 8-Core Intel Core i9
- OS version: macOS 13.1 (22C65)
- System type (32-bit or 64-bit): 64-bit
- Firefox Translation Extension version: 1.2.0buildid20221114.185738
- Webpage on which issue was observed: Any site that needs translation (I used https://mes-pronoms.vercel.app/)
- Language of the webpage: French
- Translating to (language): English
- System architecture and extension information:
    - Build architecture: x86-64
    - `cpu.extensions`: [hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSSE3, hasSSE4_1, hasSSE4_2, hasAVX, hasAVX2, hasAES]

**Additional context**
I downloaded Firefox Translations when the browser was in Dark mode, so that might have something to do with this bug(?)
Also, `about:telemetry#environment-data` has been renamed to `about:telemetry#environment-data-tab`.

<img width="940" alt="Screenshot 2022-12-29 at 11 09 51 AM" src="https://user-images.githubusercontent.com/67861264/209986186-3ed0d738-8c32-40c2-b2b8-68005b14795f.png">

**Comment by ranjanmangla1** [comment]
Can you assign me this issue? I would love to work on it!!

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
