### ISSUE TITLE
Hindi support required

### ISSUE THREAD

**Issue by ranjanmangla1** [mozilla/firefox-translations#627]
Support for two of the widely spoken languages is required for the firefox translations extension

I can help with the hindi support

**Comment by cnmade** [comment]
+1 please

**Comment by miracle859** [comment]
+1 please

**Comment by sylvestre** [comment]
Chinese  request is here:
https://github.com/mozilla/firefox-translations/issues/583

**Comment by marco-c** [comment]
We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
For example, [here's the Hindi request](https://connect.mozilla.org/t5/ideas/support-hindi-translations/idi-p/33407).
