### ISSUE TITLE
Translation popup should autofill currently selected text

### ISSUE THREAD

**Issue by Caspy7** [mozilla/firefox-translations#628]
Sorry if this has been filed before. I scanned the titles and didn't notice it.

Earlier I was in a page that had a section of text in another language. This happens occasionally, particularly some posts on reddit. To translate I had to highlight then copy the text, invoke the popup then paste.

To save several steps we should detect if text is highlighted then prefill the translation box.

**Comment by andrenatal** [comment]
Hello @Caspy7 . I've implemented [that](https://github.com/mozilla/firefox-translations/commit/af29a6ca83c4e98566d510c0f150667a43e506d2) but haven't shipped yet and still make take few weeks until so. Just keep an eye in our communication channels. Thanks!
