### ISSUE TITLE
Translate input/placeholder

### ISSUE THREAD

**Issue by rafalkrupinski** [mozilla/firefox-translations#641]
**Is your feature request related to a problem? Please describe.**
Often placeholder has helpful hint regarding the expected input.

**Describe the solution you'd like**
Would be great if placeholders were also translated

**Describe alternatives you've considered**
Using a dictionary, but it beats the purpose of this plugin, and placeholders can't be easily copied and can be nuisance to type with foreign diacritic characters.

**Comment by andrenatal** [comment]
I had it implemented originally but vaguely remember needing to remove it due to conflicts with outbound translations, but I'll revisit it. Thanks for the suggestion @rafalkrupinski !

**Comment by rafalkrupinski** [comment]
Thank you for your work @andrenatal , It's a real life changer!

**Comment by marco-c** [comment]
We are not going to make any improvements to the addon since we are now focusing on the built-in version.
