### ISSUE TITLE
Translation toolbar missing

### ISSUE THREAD

**Issue by aib** [mozilla/firefox-translations#642]
**Describe the bug**
Translation toolbar does not appear. There is no obvious method to force its appearance.

**To Reproduce**
1. Go to any site where the translation toolbar does not appear
2. Try to find a way to translate the page

**Expected behavior**
I would expect a translation tool to be able to translate any web page from any supported language to any supported language.

**Screenshots**
N/A

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 109.0 (64-bit)
- OS version: 5.15.0-48-generic
- System type (32-bit or 64-bit): x86_64
- Firefox Translation Extension version: 1.2.0buildid20221114.185738
- Webpage on which issue was observed: many
- Language of the webpage: various
- Translating to (language): any
- Console logs from Web Developer Tools: empty

**Additional context**
Is there a workaround using the developer console, maybe?

It's really annoying to copy-paste every bit of text to the translation popup window that opens when I click the add-on button. There should be a way to translate the whole page, like the translation toolbar when it appears.

**Comment by andrenatal** [comment]
Hi @aib, if the extension detects that supports the translation between the page's to your browser's language, the translation bar will automatically be displayed, otherwise you can manually trigger it by clicking on the translation icon in the address bar. Aren't you seeing any of these options?

<img width="110" alt="Screenshot 2023-01-23 at 6 31 11 PM" src="https://user-images.githubusercontent.com/973388/214200700-c4e7b121-7e34-4adf-b9b9-aac65e635363.png">

https://user-images.githubusercontent.com/973388/214200800-c5a93c7e-63c8-4ef9-b512-33ab3cbc2b23.mov

**Comment by aib** [comment]
Hi @andrenatal, thanks for the swift response.

The icon in the address bar is indeed there and able to force the translation toolbar to appear. I guess it must have been there when I spent a good 5 minutes looking for it before opening this issue, as well. My apologies.

Do you think it might be a good idea to change this issue's title and text to turn it into a "how do I force the translation toolbar to appear—here's how with a video" question to aid other dimwits like me?

**Comment by andrenatal** [comment]
No problem @aib , I am glad to help. 

I agree it's utilization is not outright clear so I am preparing a complete tutorial on how to use the extension to be released with the next version.

**Comment by fallmake** [comment]
@andrenatal I just had the exact same experience leading me here. Expected "Translate" in page context menu OR right-click option of the addon button in the toolbar to trigger the translation bar. The URL bar button is nice though and the tutorial is a good idea.

A context menu item "Translate to <firefox_display_language>" would be great for occasional quick full-page translations (not to be confused with translation of selected-text https://github.com/mozilla/firefox-translations/issues/358) and was what I was actually looking for. I think translation is a general-enough feature to not be considered clutter there.

**Comment by marco-c** [comment]
We are not going to make any improvements to the addon since we are now focusing on the built-in version.
