### ISSUE TITLE
Telemetry reporting engine crashes

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#65]
We need to have telemetry reporting whenever the translation engine crashes or fail (re: https://github.com/browsermt/bergamot-translator/issues/316). Are we capturing those @eu9ene ?

**Comment by eu9ene** [comment]
At the moment any translation fail is reported without distinguishing between engine and non-engine. We have a metric in the schema to handle this. I'm adding it.

**Comment by andrenatal** [comment]
Thanks @eu9ene . Code looks good to me, feel free to merge it after we can distinguish between the sources.
