### ISSUE TITLE
Include option to auto detect input language in popup

### ISSUE THREAD

**Issue by veyndan** [mozilla/firefox-translations#664]
### Is your feature request related to a problem? Please describe.

The initial state of the popup requires three inputs:

1. The text that you want translated.
2. The language of the inputted text.
3. The desired language of the outputted text.

Firefox Translations has a "suggestion" section once you start typing. This can _speed up_ step 2 (as long as you know to write the text beforehand). Ideally, we should be able to _eliminate_ step 2 altogether.

### Describe the solution you'd like

Replace the "Choose a language" option in the language selection view with "Detect language". When the user starts typing, the text "Detect language" is change to "{language} - detected" (e.g., "English - detected").

If the user _is happy_ with the detected language, they don't have to select the input language from the language selection view. If the user _is not happy_ with the detected language, they can select the desired language from the language selection view.

### Additional context

This is very similar to what Google Translate does. I find it useful as it requires a bit less clicking.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
We don't have a pop-up yet in the built-in version, but the about:translations page has the autodetect functionality.
