### ISSUE TITLE
 Firefox Translations extension adds noticeable (>1s) delay to browser readiness at launch time

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#666]
### Describe the bug

Moving from https://bugzilla.mozilla.org/show_bug.cgi?id=1809926 to here:

> This is especially noticeable when a content blocker is also enabled, as these will delay webpage load time until they are ready.
> 

> Two profiling sessions attached, one with Firefox Translations enabled, the other without Firefox Translations -- all else being the same.
> 

### To Reproduce

> Steps to reproduce:
> 
>     Install uBlock Origin (from https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)
>     Install Firefox Translations (from https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/)
>         I wouldn't know but it's possible the number of currently downloaded translations package influence -- I can't remember how many I have locally on my side, maybe ~5
>     Open a simple webpage (i.e. http://example.org/)
>     Check the setting "Open previous windows and tabs" so that the browser opens the above webpage at next launch
>     Quit Firefox
>     Launch Firefox
> 
> Notice the >1s delay for the restored webpage to open compared to when Firefox Translations is disabled.
> 

### Expected behavior

No slowness.

### Screenshots

![image](https://user-images.githubusercontent.com/973388/215591519-6a3ebf50-3e83-403c-9651-36a519332efd.png)

### Additional context

Refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1809926 for more info

### Firefox Browser version

110

### System type

None

**Comment by marco-c** [comment]
I think we can WONTFIX this for the extension, and track the problem in the built-in version in https://bugzilla.mozilla.org/show_bug.cgi?id=1836974.
