### ISSUE TITLE
Form translation bottom pop-up shows source and target language as “undefined”

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#667]
### Describe the bug

Source and target languages are shown as “undefined” in the form translation pop-up.

### To Reproduce

1. Install Firefox Translations 1.3.2
2. Access https://www.apple.com/fr/contact/feedback/
3. Enable the “Enable translations of forms” function and translate the page
4. Select a reason from the “My comments relate to” drop-down so as to proceed to the actual feedback form
4. Click on the “Comments” field to bring up the form translation pop-up
5. Notice the source and target languages are shown as undefined

### Expected behavior

Form translation pop-up should correctly show the source and target languages

### Screenshots

![2023-01-31_10h58_37](https://user-images.githubusercontent.com/50236075/215716112-30e2c51f-0b3f-4c52-bb57-9c7800d51deb.png)

### System type

None

**Comment by andrenatal** [comment]
Hi @acornestean , this is now fixed on Nightly. Could you please test it? Thanks!

**Comment by acornestean** [comment]
Verified as Fixed using the latest Nightly version of Firefox Translations (e082f53).

Source and target languages no longer appear as “undefined” in the form translation pop-up, but are displayed properly. See screenshot for more details.

Tested on the latest Firefox Nightly 111.0a1 and Beta Developer Edition 110.0b8.

![2023-02-02_11h35_29](https://user-images.githubusercontent.com/50236075/216290425-224da270-7e7b-4cd4-bd9c-8beb30f1999e.png)
