### ISSUE TITLE
“Elements pending to translate” counter flickers rapidly between 25 and 0 when translating long pages

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#669]
### Describe the bug

When translating long pages, when the counter for elements pending translation reaches 25, it will flicker rapidly between 25 and 0 until it reaches 0 as the translation is complete.

### To Reproduce

1. Install Firefox Translations v1.3.2
2. Access https://de.wikipedia.org/wiki/COVID-19
3. Translate the page
4. Notice that when the counter for elements pending translation reaches 25, it will rapidly flicker between 25 and 0 until it ultimately reaches 0 as the translation of the page is complete

### Expected behavior

The “Elements pending to translate” counter should go down to 0 without the value flickering as the page content is translated.

### Screenshots

https://user-images.githubusercontent.com/50236075/216021518-48102170-9d73-46ff-b5e6-0da4b13e38dc.mp4

### System type

None

**Comment by andrenatal** [comment]
Hi Alex, this is just how it is by design. That represents the amount of elements in the worker's queue. I know it's not the best UX but that will be hopefully get better in upcoming versions. Thanks for reporting.
