### ISSUE TITLE
The first 2 rows from the translation pop-up is considered as one row, causing words to be stringed one after the other in the translation

### ISSUE THREAD

**Issue by acornestean** [mozilla/firefox-translations#674]
### Describe the bug

In the input field of the translation pop-up, the first 2 rows are considered as one single row, which causes words that are added on what appears to be 2 separate rows to end up on after the other in the translation on the right.

The issue does not extend past the first 2 rows of the input field.

The issue occurs on both Firefox for desktop and Firefox for Android.

### To Reproduce

1. Install Firefox Translations v1.3.2
2. Open the translation pop-up and select any source and target languages
3. In the input field, write a word on the first row and notice it is translated in the target field
4. Press Enter to move the cursor to the next row in the input field and write another word.
5. Notice that in the target field the translated words are stringed one after the other as if the first 2 rows of the input field is considered as one single row
6. Move the cursor at the end of the first word in the input field and press Enter
7. Notice that only now will the translation result be shown on different rows.

### Expected behavior

The first 2 rows of the input field should act as 2 separate rows.

### Screenshots

https://user-images.githubusercontent.com/50236075/216561923-8ac9ae6b-8820-48c4-a11f-7ec3f9bb24a0.mp4

### System type

None

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
