### ISSUE TITLE
Wrong Lithuanian  translation 

### ISSUE THREAD

**Issue by st-182** [mozilla/firefox-translations#676]
### Describe the bug

When I want to add a new search engine to the list, I see the wrong translation of "Pirdėti" instead of "Pridėti". It is obviously a typo, could you please correct it and release update, thank you. 
You can check the translations in DeepL Translate:
correct - https://www.deepl.com/translator#lt/en/Prid%C4%97ti
incorrect - https://www.deepl.com/translator#lt/en/Pird%C4%97ti

### To Reproduce

1. Open Firefox with Lithuanian translations 
2. Open any search engine
3. Press right mouse button for menu to appear
4. You can see typo there

### Expected behavior

There should be " Pridėti "Youtube" " instead of " Pirdėti "Youtube" ".

### Screenshots

![photo_2023-02-08_22-08-25](https://user-images.githubusercontent.com/31894656/217640156-3092b5a2-2548-4ff5-b9fc-a25536c86334.jpg)

### Firefox Browser version

the last available

### System type

None

**Comment by andrenatal** [comment]
Hello @st-182 , it seems you reported this issue in the wrong repo. Maybe @flodolo could help you determine what's the right one (I don't know).

**Comment by flodolo** [comment]
https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla%20Localizations&component=lt%20%2F%20Lithuanian

**Comment by st-182** [comment]
ok, thank you

**Comment by flodolo** [comment]
BTW, if you want to contribute, translations happen here
https://pontoon.mozilla.org/lt/firefox/all-resources/?search=Pird%C4%97ti&string=223562

Your suggestion seems to be easy enough for me to fix directly, since the other strings confirm the spelling.
