### ISSUE TITLE
Manual translation does not start after pasting text.

### ISSUE THREAD

**Issue by marcel263** [mozilla/firefox-translations#677]
### Describe the bug

Manual translate does not start after pasting, only after a keypress.

### To Reproduce

Paste text into panel for manual translation, accessible through the extension icon.
Notice how translation does not start, only after manually pressing the keyboard. This becomes a chore sfter a while.

### Expected behavior

Translate on any change, whether it is by keypress or paste event.

### System type

None

**Comment by andrenatal** [comment]
Hello. This was implemented already and will be available in the upcoming version to be released in a couple of weeks, hopefully 🤞

**Comment by marcel263** [comment]
@andrenatal Dear, thank you for the quick response. Indeed it was overlooked by me in the changelog. Will be looking out for all of the improvements.
