### ISSUE TITLE
Wrong English to French translation

### ISSUE THREAD

**Issue by mathpce** [mozilla/firefox-translations#681]
Hello,

I got weird translations from English text to French:
| English (source) | French (translation) | Problem |
|---|---|---|
|To whet your appetite|Pour éblerler votre appétit|"éblerler" does not exist in French, I have checked with major search engines and two leading dictionaries|
|to whet your appetite|pour éveillez votre appétit|The difference is only the uppercase. The translation's meaning seems right here, but it should use an infinitive form ("éveiller") instead of a conjugated verb|

**Comment by Raziel-SSJ** [comment]
Hi.

Effectively, **English to French**, as well as **French to English** translations are often unusable.
**Sometimes not accurate.** _The meaning is not appropriate/adapted/related to the context, or the conjugation is incorrect._
**Sometimes totally wrong.** _Translate into an unrelated word(s) (with a totally different meaning, even its(their) different meanings or its(their) synonyms), or words that doesn't even exist._
**Sometimes words are added from nowhere.**
**Sometimes words are not translated at all.**

Understanding of the context and/or usage of synonyms seems to be problematic.
"Google Translate", sadly, is far ahead concerning this. But I really hope you'll be able to catch up with them.
A good point would be to add the possibility of having/seeing multiple results with synonyms or related words as Google does.  

An example here in my comment:
"Google Translate", sadly, is far ahead concerning this.
_Gives, when double/reverse translated:_
"Google Translate", is unfortunately far from being at the forefront.
**In addition to giving the opposite meaning, the end of the sentence is missing.**

**Comment by marco-c** [comment]
@Raziel-SSJ can you provide example wrong translated sentences in French and English, the more the better.
