### ISSUE TITLE
Preload current tranlation engine for right click translate?

### ISSUE THREAD

**Issue by joveian** [mozilla/firefox-translations#685]
### Is your feature request related to a problem? Please describe.

Thanks for adding right click translation!  I've noticed it is slow when frequently translating short phrases due to needing to load the translation engine each time.

### Describe the solution you'd like

If it is possible at some point to add an option to keep the translation engine loaded for faster right click translation I would use that.  I don't care if it uses lots of memory.

I've heard that TranslateLocally run outside the browser is much faster but I haven't tried that yet.  A way to use external translation utilities from this addon might be a solution to this issue as well, ideally a general API that could be used by Apertium and any other local translation software as well.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
We'll keep this in mind as we implement selection translation in the built-in version.
