### ISSUE TITLE
source language should be detected and auto selected

### ISSUE THREAD

**Issue by yukulele** [mozilla/firefox-translations#687]
### Describe the bug

if "Never offer translations" option is checked, source lang is not selected.

### To Reproduce

- enable "Never offer translations" option
- open a page to translate (example: https://it.wikipedia.org/wiki/Mozilla_Firefox)
- open the translate page tool

### Expected behavior

current page language should be selected as source language

### Screenshots

source language is not selected:
![Screenshot_20230314_215824](https://user-images.githubusercontent.com/347244/225134741-6f59674c-d157-4525-ab6c-e67395cc3be6.png)

### Firefox Browser version

109.0.1

### System type

None

### Firefox Translation Extension version

1.3.2

**Comment by calvinkarpenko** [comment]
It should be noted that it does do this for some websites (such as dw.com and derspiegel.de, and even nrk.no) so it appears to be detecting it based on the content of the HTML lang attribute.

**Comment by prlbr** [comment]
I have the same issue (Firefox 111.0/Firefox Translations 1.3.2) even when "Never offer translations" is not checked. It does not detect the source language of a webpage automatically, even though the webpage has a correct `lang` attribute on its `html` element.

Example URL: https://github.com/mozilla/firefox-translations/issues/687 (this issue)

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).
