### ISSUE TITLE
Weird translation on Le Monde article "Chute de la Silicon Valley Bank : les leçons d’une faillite bancaire"

### ISSUE THREAD

**Issue by yoasif** [mozilla/firefox-translations#688]
### Describe the bug

I saw a weird English translation when navigating to https://www.lemonde.fr/idees/article/2023/03/15/chute-de-silicon-valley-bank-les-lecons-d-une-faillite-bancaire_6165566_3232.html

### To Reproduce

1. Navigate to https://www.lemonde.fr/idees/article/2023/03/15/chute-de-silicon-valley-bank-les-lecons-d-une-faillite-bancaire_6165566_3232.html
2. See headline "Chute de la Silicon Valley Bank : les leçons d’une faillite bancaire"
3. translate to English from French
4. Translation that appears is "Silicon Valley Bank Falls: Lessons from Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank"

### Expected behavior

Something like "Fall of Silicon Valley Bank: lessons from a bank failure" (Google translate).

### Screenshots

![Screenshot 2023-03-15 at 18-56-49 Silicon Valley Bank Falls Lessons from Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Bank Ban](https://user-images.githubusercontent.com/152493/225461558-68f00da7-de0f-41b5-bf75-0e323d6bed4f.png)

### Firefox Browser version

Firefox Nightly

### Processor information

i3-1125g4

### OS version

Fedora 37

### System type

64-bit

### Webpage on which issue was observed

https://www.lemonde.fr/idees/article/2023/03/15/chute-de-silicon-valley-bank-les-lecons-d-une-faillite-bancaire_6165566_3232.html

### Language of the webpage

French

### Translating to (language)

English

**Comment by benyaminl** [comment]
Reproduceable on same fedora 37 xfce spin, firefox rpms 110 with latest addons of ff translation (never install, this is first time I use it). 

![image](https://user-images.githubusercontent.com/2817332/225550251-ca0bcd4e-67c6-46c2-a8e1-534c0440a099.png)

**Comment by gregtatum** [comment]
If the `:` is removed from the source text, it fixes it.

**Comment by marco-c** [comment]
Even removing just the whitespace between "Bank" and ":" fixes this. Might be an issue related to tokenization (see also https://github.com/google/sentencepiece#whitespace-is-treated-as-a-basic-symbol).

**Comment by marco-c** [comment]
We might be able to fix this with some data augmentation (randomly adding whitespaces between words and ":" in our datasets).

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
I've already reported this problem, and you can report additional translation errors on https://docs.google.com/forms/d/e/1FAIpQLSdoRWnsHX6vVnGIRyLi4Kl-p0GrmeVIioqWsTz3aVTRfLScng/viewform.
