### ISSUE TITLE
Feature like "Simple Translate" add-on

### ISSUE THREAD

**Issue by cosmonet-fr** [mozilla/firefox-translations#689]
### Is your feature request related to a problem? Please describe.

Often, when I use a translator, I prefer to translate a word or group of words rather than an entire page. But it uses GG translation :/ 
Would it be possible to have this same functionality in "Firefox translate" or have another addon "Simple Translate by Firefox"?

thank 

### Describe the solution you'd like

I find that using "Simple Translate" is great for this. It allows you to quickly translate selected or typed text on web pages.

**Comment by cadeyrn** [comment]
This feature already exists. Just select text and use the context menu entry of Firefox Translations. Make sure that you're using the latest version of the add-on since it's a new feature of Firefox Translations 1.3.
