### ISSUE TITLE
Swap should only swap the language pair, not the content.

### ISSUE THREAD

**Issue by marcel263** [mozilla/firefox-translations#690]
### Describe the bug

I fail to see what good swapping the translated text does. This reminds of funny videos that circulate the internet where people feed the same text endlessly, passing back and forth and compare the result with the original, often barely recognisable.

Just swap the language pair, not the contents of the input fields, for people who need a reverse dictionary or need to check a translation.

### To Reproduce

Press "swap" button as shown with horizontal arrows.

### Expected behavior

Don't swap the text field content, which causes a loop, e.g. machine translating the text from the target language back. Instead, swap just the language pair. Also practical if one wants to just put a language in the right function (e.g. swap English into place) for further adjustment of language choice. The behavior is erratic.

**Comment by lhpitn** [comment]
no, that behavior is correct, users are used to swap buttons that swap both, like google and deepl translator

**Comment by marcel263** [comment]
> no, that behavior is correct, users are used to swap buttons that swap both, like google and deepl translator

No, it is erratic behaviour. There is no need to translate back what the machine translated, that is not the point of a translation software. Convention or not.

If user pastes the text and presses swap, it removes their text and it gets replaced with the previous answer, even if the translator corrupted the translation (e.g. false translations, loanwords). Now the user must paste again.

What is the point of machine accepting not its user command but listens to its own?

**Comment by cadeyrn** [comment]
> No, it is erratic behaviour. There is no need to translate back what the machine translated, that is not the point of a translation software. Convention or not.

Did you check it before saying "No"? Google and DeepL _do_ this. And to be honest I sometimes make use of this behaviour when I use one of these services. So I don't think it's a fair assumption that there is no need for anyone.

**Comment by marcel263** [comment]
> > No, it is erratic behaviour. There is no need to translate back what the machine translated, that is not the point of a translation software. Convention or not.
> 
> Did you check it before saying "No"? Google and DeepL _do_ this. And to be honest I sometimes make use of this behaviour when I use one of these services. So I don't think it's a fair assumption that there is no need for anyone.

What is the point of a software erasing user input?

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).
