### ISSUE TITLE
the icon for this extension implies support for japanese, which it does not have

### ISSUE THREAD

**Issue by colons** [mozilla/firefox-translations#692]
![the icon for this extension, depicting a hiragana 「あ」 in a cycle with a latin 'a'](https://raw.githubusercontent.com/mozilla/firefox-translations/main/extension/view/icons/translation-color.svg)

maybe this is just me, but i was very surprised to discover that this extension does not support japanese at all, when its icon is what it is

i feel like maybe it would be a good idea to replace the あ with a character from a language that is actually supported

**Comment by colons** [comment]
i recently encountered this icon, which is presented as an embedded svg on a firefox update notification shown at launch, notifying me about this extension's existence (headed "Say ‘hola’ to Firefox Translations")

![a less misleading icon that seems to be built into firefox itself](https://user-images.githubusercontent.com/1394710/228661136-f0bcc145-0d17-4df2-9847-ea57d3407c21.svg)

if firefox already thinks this is the icon for this extension, it's probably a good candidate for replacements that solve this issue

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
