### ISSUE TITLE
Please add Chinese translation for this Add-ON

### ISSUE THREAD

**Issue by miracle859** [mozilla/firefox-translations#696]
### Is your feature request related to a problem? Please describe.

For now the pure and local translation is widely used for the user 
some people use edge because of the translation too 
If Firefox adds a Chinese translation, it will make Firefox more competitive and increase the number of users.
Please let us know, do you have a blue map to add Chinese and when? 

### Describe the solution you'd like

request add Chinese language

**Comment by sylvestre** [comment]
Dup of #583 as you probably saw ;)
