### ISSUE TITLE
Remove from address bar

### ISSUE THREAD

**Issue by nollinvoyd** [mozilla/firefox-translations#699]
### Is your feature request related to a problem? Please describe.

I have limited toolbar space.  I'm a user that only requires translation features on rare occasions.  

### Describe the solution you'd like

There should be an option in settings to switch to a toolbar button instead of the address bar. 

### Describe alternatives you've considered

I'd prefer to keep the Mozilla addon, but I will be forced replace it if the issue is not addressed

**Comment by migmanu** [comment]
Sorry, I fail to understand your problem. You have limited toolbar space but you would like to have the extension icon moved from the address bar to the toolbar?

**Comment by nollinvoyd** [comment]
I want to have a movable button to place on the overflow menu, or perhaps, when it is in use, to place it temporarily on the menu bar, 

The more buttons on the navbar, the further my address field shrinks.  Extremely inconvenient.

My only other workaround is to disable it until I need it, which is not preferable.

Is this possible?

**Comment by nollinvoyd** [comment]
I'd appreciate If you could just tell me it's not possible, so I could stop checking back here.  Thanks

**Comment by yokoffing** [comment]
Similar to #657

**Comment by nollinvoyd** [comment]
Can I assume there are no plans to address requested changes?

**Comment by sylvestre** [comment]
we are looking at a different approach. more soon!

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
