### ISSUE TITLE
Support alt message translation from images via context menu

### ISSUE THREAD

**Issue by saschanaz** [mozilla/firefox-translations#701]
### Is your feature request related to a problem? Please describe.

For example: https://social.bund.de/@RKI/110134617299795225

It's easy to get a translation for text as the extension now support translation via context menu, but there's no good way to do the same for images.

### Describe the solution you'd like

Could be great if the extension could detect `alt` attribute from the given image and use that for translation.

### Describe alternatives you've considered

Copypaste `alt` attribute manually. That requires interacting with DevTools or another extension like [Copy Alt Text](https://addons.mozilla.org/en-US/firefox/addon/copy-alt-text/).

**Comment by gregtatum** [comment]
This is tracked in: https://bugzilla.mozilla.org/show_bug.cgi?id=1819205
