### ISSUE TITLE
Skips Placeholder text

### ISSUE THREAD

**Issue by BassyBoo55** [mozilla/firefox-translations#705]
### Describe the bug

It skips placeholder text in buttons. This makes navigating for example a train station website quite difficult if you do not understand the language.

### To Reproduce

1. Go to https://reiseauskunft.bahn.de/bin/query.exe/dn?start=1&existOptimizePrice=1&S=&REQ0JourneyStopsSID=&Z=&REQ0JourneyStopsZID=&date=So.%2C+16.04.2023&time=11%3A27&timesel=depart&returnDate=&returnTime=&optimize=0&auskunft_travelers_number=1&tariffTravellerType.1=E&tariffTravellerReductionClass.1=0&tariffClass=2&externRequest=yes&HWAI=JS%21js%3Dyes%21ajax%3Dyes%21&rit=1
2. See the placeholders in the text boxes for the station names are left untranslated

### Expected behavior

The text in the placeholders are to be translated.

### Screenshots

![image](https://user-images.githubusercontent.com/80031375/232298296-7aa19d5c-527f-4919-8f5c-e330c131b1a2.png)

### Firefox Browser version

111.0.1

### Processor information

Ryzen 5 3600

### OS version

Windows 10 build 19045.2846

### System type

64-bit

### Firefox Translation Extension version

1.3.2buildid20230220.141944

### Webpage on which issue was observed

https://reiseauskunft.bahn.de/bin/query.exe/dn?start=1&existOptimizePrice=1&S=&REQ0JourneyStopsSID=&Z=&REQ0JourneyStopsZID=&date=So.%2C+16.04.2023&time=11%3A27&timesel=depart&returnDate=&returnTime=&optimize=0&auskunft_travelers_number=1&tariffTravellerType.1=E&tariffTravellerReductionClass.1=0&tariffClass=2&externRequest=yes&HWAI=JS%21js%3Dyes%21ajax%3Dyes%21&rit=1

### Language of the webpage

Dutch

### Translating to (language)

English GB

### Console logs from Web Developer Tools

Using fallback gemm implementation [bergamot-translator-worker.js:2965:17](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/bergamot-translator-worker.js)
Wasm Runtime initialized Successfully (preRun -> onRuntimeInitialized) in 0.006 secs [translationWorker.js:83:29](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Creating Translation Service with config: {"cacheSize":0} [translationWorker.js:358:25](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Translation Service created successfully [translationWorker.js:360:25](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Constructing translation model deen [translationWorker.js:388:21](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: false
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            [translationWorker.js:450:21](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Aligned memory sizes: Model:17140837, Shortlist:5047568,  Vocab: 784269 [translationWorker.js:451:21](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Constructing translation model ende [translationWorker.js:388:21](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: true
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            [translationWorker.js:450:21](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Aligned memory sizes: Model:17140835, Shortlist:3943644,  Vocab: 784269 [translationWorker.js:451:21](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Model 'deen' successfully constructed. Time taken: 0.395 secs [translationWorker.js:327:23](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
loadLanguageModel function complete [translationWorker.js:350:21](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Ziel nach Start" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 6 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Ziel nach Start" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 6 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Ziel nach Start" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 6 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 1" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 1" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 2" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 3" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 1" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 2" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 3" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 13 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 1" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 2" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 3" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 6 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 1" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 2" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 3" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 6 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 1" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 2" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 3" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 6 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 1" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 2" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 3" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 6 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "von Start nach Ziel" 3 [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 1" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 2" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Plain text received to translate with QE: "Rückfahrt - Abschnitt 3" [translationWorker.js:163:45](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)
Restoring back source text and html flag 6 [translationWorker.js:181:41](moz-extension://74e23f0a-9e1e-4e4a-8eb6-b51f34e44e63/controller/translation/translationWorker.js)

**Comment by marco-c** [comment]
We are not going to fix this in the addon, but we are tracking this in https://bugzilla.mozilla.org/show_bug.cgi?id=1819205 for the built-in version.
