### ISSUE TITLE
translate `title` attributes

### ISSUE THREAD

**Issue by yukulele** [mozilla/firefox-translations#708]
### Describe the solution you'd like

`title` (and probably `alt`) attributes should be translated.

**Comment by cadeyrn** [comment]
Duplicate of #501 and [BZ-1819205](https://bugzilla.mozilla.org/show_bug.cgi?id=1819205) for the native Firefox integration.

**Comment by yukulele** [comment]
#501 is about `<title>` element, this is about `title` attribute

**Comment by cadeyrn** [comment]
Sorry, you're right. At least BZ-1819205 is really about the title attribute.
