### ISSUE TITLE
Wrong EN - DE translation / Missing instant feedback possibility

### ISSUE THREAD

**Issue by Anke** [mozilla/firefox-translations#711]
### Describe the bug

English original:
Allows Android devices to use beacons much like iOS devices do. An app can request to get notifications when one or more beacons appear or disappear. An app can also request to get a ranging update from one or more beacons. It also allows Android devices to send beacon transmissions, even in the background.

German Firefox translation:
Ermöglicht Android-Geräte, Beacons zu verwenden, wie es iOS-Geräte tun. Eine App kann verlangen, Benachrichtigungen zu erhalten, wenn ein oder mehrere Leuchtfeuer erscheinen oder verschwinden. Eine App kann auch beantragen, ein entsprechendes Update von einem oder mehrere Leuchtfeuer zu erhalten. Es ermöglicht auch Android-Geräte, auch im Hintergrund Speckübertragungen zu senden.

### To Reproduce

Go to https://reports.exodus-privacy.eu.org/en/trackers/219/ and have the first paragraph translated into German.

### Expected behavior

Translation of beacon:
There's no one-word translation for "beacons" in information technology, as beacons can be a variety of things to allow user tracking. Neither are beacons light signals, in German "Leuchtfeuer" nor are "beacon transmissions" "Speckübertragungen"! Bacon is "Speck" in German. So if the text insinuates an IT topic, then "beacons" should be "Beacons" in German.

### Additional context

BTW: When I first used Frefox translations, I remember there was something like a button to instantly report wrong translations. While in FF translations setup there's an activated checkbox "Report errors", only I cannot find any button or form to do so. I can't imagine it to be a good idea to report translation errors right here between bugs and feature requests etc.

I don't really like the top-bar in the browser, but finding the translator in the context menu is great!

### Firefox Browser version

112.0.1

### OS version

WIN10

### System type

64-bit

### Firefox Translation Extension version

1.3.2buildid20230220.141944

### Webpage on which issue was observed

see above

### Language of the webpage

en

### Translating to (language)

de

### Console logs from Web Developer Tools

nothing critical

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
You can report this and additional translation errors on https://docs.google.com/forms/d/e/1FAIpQLSdoRWnsHX6vVnGIRyLi4Kl-p0GrmeVIioqWsTz3aVTRfLScng/viewform.
