### ISSUE TITLE
User preferences are not respected

### ISSUE THREAD

**Issue by patcheco1001** [mozilla/firefox-translations#712]
### Describe the bug

The user preferences on whether to send interaction/analytic data are not taken into account since I can see that this extension continue to ping incoming.telemetry.mozilla.org every minute.
There is no difference between enabled or disabled.
If I disable this extension, these ping stopped.

### To Reproduce

1. Just launch Firefox and navigate to internet
2. To check these ping I'm using Pi-hole. You can use any equivalent DNS or a tools that can display the DNS traffic

### Expected behavior

If the interaction data option is disabled in this extension's settings, it should not send anything to incoming.telemetry.mozilla.org every minute

### Screenshots

![Capture d'écran 2023-04-29 131856](https://user-images.githubusercontent.com/8749048/235300251-38c6f435-8808-4970-aef2-0e5bf0938e55.png)
![Capture d'écran 2023-04-29 131932](https://user-images.githubusercontent.com/8749048/235300256-afa1b967-5897-436d-a199-a077c4a66fec.png)

### Firefox Browser version

112.0.2

### Processor information

Intel i7-7700HQ

### OS version

Windows 11 Pro

### System type

64-bit

### Firefox Translation Extension version

1.3.2buildid20230220.141944

### Webpage on which issue was observed

any page

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
