### ISSUE TITLE
A good model to feed English to Japanese translation to

### ISSUE THREAD

**Issue by GunGunGun** [mozilla/firefox-translations#714]
### Is your feature request related to a problem? Please describe.

To add Japanese translation to FT because it's very needed for many people, it's makes FT more appealing.

### Describe the solution you'd like

Download this model, open fairseq folder and grab the fairseq model, use it to train Japanese model for FT, this model is very accurate when it comes to Japanese, but its file size is huge.

Link: https://filedownload.sfo3.cdn.digitaloceanspaces.com/Sugoi-Translator-Toolkit-V5.0-Public.rar

### Describe alternatives you've considered

No.

### Additional context

No.

**Comment by andrenatal** [comment]
Thanks @GunGunGun . I'll take a look.

**Comment by GunGunGun** [comment]
@andrenatal 

Hope this is helpful, if you extracted the archive, the model file should be in `Code\backendServer\Program-Backend\Sugoi-Japanese-Translator\offlineTranslation\fairseq\japaneseModel\big.pretrain.pt`

Thanks and the team for making this project and addon, this is a game changing for many of us and I hope it will success.

**Comment by sylvestre** [comment]
Do you know what is the license and provenance of this dataset?
Thanks

**Comment by sylvestre** [comment]
@GunGunGun ping? thanks

**Comment by marco-c** [comment]
There are some other models at http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/ that we might investigate using.

**Comment by GunGunGun** [comment]
> @GunGunGun ping? thanks



> @GunGunGun ping? thanks

I can't find any information about the license of this model, but we can use JParaCrawl: http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
We are going to investigate Japanese in the future.
