### ISSUE TITLE
Error when highlighting in red is enabled

### ISSUE THREAD

**Issue by heftig** [mozilla/firefox-translations#721]
### Describe the bug

"We found an error loading the translation engine." attempting to translate with highlighting errors in red enabled.

Digging out the error before it's sent to Sentry shows the message "CSSStyleSheet.insertRule: Not allowed to access cross-origin stylesheet".

### To Reproduce

1. Go to https://www.der-postillon.com/2023/05/lg-anschlag.html
2. Open Firefox Translations.
3. Set to translate from German to English.
4. Keep highlighting errors in red enabled.
5. Click Translate.

### Expected behavior

Translation works and does not show an error message.

### Firefox Browser version

115.0a1 (2023-05-25)

### Processor information

x86-64 [hasMMX, hasSSE, hasSSE2, hasSSE3, hasSSSE3, hasSSE4_1, hasSSE4_2, hasAVX, hasAVX2, hasAES]

### OS version

Arch Linux

### System type

64-bit

### Firefox Translation Extension version

1.3.2buildid20230220.141944

### Webpage on which issue was observed

https://www.der-postillon.com/2023/05/lg-anschlag.html

### Language of the webpage

German

### Translating to (language)

English

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
