### ISSUE TITLE
[Language Request] Add Romanian Translation 

### ISSUE THREAD

**Issue by claudiu64** [mozilla/firefox-translations#723]
### Is your feature request related to a problem? Please describe.

This language is not supported yet.

### Describe the solution you'd like

Add the Romanian language to the add-on. 

### Additional context

Are they working to add the Romanian language? I am waiting for an answer.

**Comment by marco-c** [comment]
We are going to track language requests in Mozilla Connect. Please vote the languages you'd like to see us support.
For example, [here's the Romanian request](https://connect.mozilla.org/t5/ideas/support-romanian-translations/idi-p/33417#M19277).
