### ISSUE TITLE
Video is not accessible, actual documentation would be better

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/firefox-translations#724]
### Is your feature request related to a problem? Please describe.

The project page tells users "Please refer to this video on how to use the extension."

Any video poses a ton and a half of accessibility and usability problems. This video features text that's too small to read, a lot of flashng, and then painful scrolling, leaving me with severe motion sickness.

### Describe the solution you'd like

Actual written documentation.

### Describe alternatives you've considered

Closing the video.

Watching the rest of the video and vomiting over my keyboard.

**Comment by marco-c** [comment]
We are not going to fix this for the addon, but the built-in version will definitely have at least an accessible SUMO page to explain it.
