### ISSUE TITLE
"An error occurred while loading the translation engine" with Firefox and Linux

### ISSUE THREAD

**Issue by theyoungstone** [mozilla/firefox-translations#726]
### Describe the bug

When I want to translate with the extension, I have the error "Une erreur s'est produite lors du chargement du moteur de traduction" (An error occurred while loading the translation engine) 

Firefox 114.0.1 (64 bits), Linux Ubuntu 23.04 up to date

### To Reproduce

Install the extension and try to translate, a site or simply a character chain

### Expected behavior

Translation

### Screenshots

![Capture d’écran_2023-06-13_08-17-32](https://github.com/mozilla/firefox-translations/assets/21762148/4cfa6610-59bb-43c7-a714-f5a6656c3992)
![Capture d’écran_2023-06-13_08-18-19](https://github.com/mozilla/firefox-translations/assets/21762148/b9a43113-fa2e-4392-895e-e5bb45bb41f3)

### Firefox Browser version

114.0.1 (64 bits)

### Processor information

AMD Athlon(tm) II X4 640 Processor

### OS version

Ubuntu 23.04 - Linux antec 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### System type

64-bit

### Firefox Translation Extension version

1.3.2buildid20230220.141944

### Webpage on which issue was observed

All

### Language of the webpage

English

### Translating to (language)

French

### Console logs from Web Developer Tools

Using fallback gemm implementation [bergamot-translator-worker.js:2965:17](moz-extension://89c452dd-58e7-4c1a-b09c-0c90dc7718f3/controller/translation/bergamot-translator-worker.js)
failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 32288: unrecognized opcode: fd c [bergamot-translator-worker.js:526:11](moz-extension://89c452dd-58e7-4c1a-b09c-0c90dc7718f3/controller/translation/bergamot-translator-worker.js)
Error loading wasm module. [translationWorker.js:73:29](moz-extension://89c452dd-58e7-4c1a-b09c-0c90dc7718f3/controller/translation/translationWorker.js)
Aborted(CompileError: wasm validation error: at offset 32288: unrecognized opcode: fd c) [bergamot-translator-worker.js:445:9](moz-extension://89c452dd-58e7-4c1a-b09c-0c90dc7718f3/controller/translation/bergamot-translator-worker.js)
RuntimeError: Aborted(CompileError: wasm validation error: at offset 32288: unrecognized opcode: fd c). Build with -s ASSERTIONS=1 for more info. [bergamot-translator-worker.js:449:14](moz-extension://89c452dd-58e7-4c1a-b09c-0c90dc7718f3/controller/translation/bergamot-translator-worker.js)

**Comment by cadeyrn** [comment]
SSE 4.1 is a strict requirement for Firefox Translations. Your CPU is too old and does not support SSE 4.1. You can follow [BZ-1811908](https://bugzilla.mozilla.org/show_bug.cgi?id=1811908) to see if/once the requirement will be changed for the native integration in Firefox.

**Comment by theyoungstone** [comment]
Thanks for the answer.
