### ISSUE TITLE
Request: set <html lang="..."> attribute

### ISSUE THREAD

**Issue by mattheww-skyward** [mozilla/firefox-translations#727]
### Is your feature request related to a problem? Please describe.

I'm trying to detect how often pages on my site are translated, and to what language, in order to prioritize adding first-party translations.

### Describe the solution you'd like

It would be nice if the extension updated the page's lang attribute to match its new language.  Google Translate and Safari Translate do this, so there's precedent.

### Describe alternatives you've considered

I could add a hidden span with a canary string like "hello world" or "my hovercraft is full of eels" and compare the text to a table of known translations.  This would probably work, but it seems less elegant and reliable than reading off an ISO 639 code in a well-established location.

### Additional context

I'd be happy to implement this, if it's accepted.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
I moved this to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842804.
