### ISSUE TITLE
REQUEST: Add an option to restore the Translation Banner (if user has accidentally clicked "Never offer translations")

### ISSUE THREAD

**Issue by zpangwin** [mozilla/firefox-translations#729]
### Is your feature request related to a problem? Please describe.

On desktop Firefox, if a user accidentally clicks the option "Never offer translations" from the translation banner - or later changes their mind - then it is not very obvious how to "Undo" this action and restore the banner.

No corresponding toggle for this setting exists under either the Addon Preferences, the Firefox Language settings, or on the toolbar fly-out menu.

For most users, this would result in confusion for how to restore it and frustration while trying and failing to do so. A much better UX would be to have some way of turning this back on that does not involve completely uninstalling and reinstalling the addon. 

### Describe the solution you'd like

Some option to re-enable the translation bar via either a checkbox or a button could be added to either:

1. The Addon Preferences page
2. The pop-out menu that appears when clicking on the addon's toolbar button
3. Under the Firefox settings > General tab > Languages section
4. some combination (or all) of the above

So that users can quickly and easily turn this behavior on/off.

### Describe alternatives you've considered

Uninstalling and reinstalling the addon does restore the translation bar but that seems a bit excessive and not at all a good UX for most users. Especially considering how easy it is to click the wrong thing or that a user may later change their mind and wish to have the banner.

### Additional context

Tested under:

* Firefox v114.0 / Fedora Linux 38 / Firefox Translations v1.3.2buildid20230220.141944 against [https://www.welt.de/](https://www.welt.de/)
* Also tested the same under Librewolf v114.0.1 and had the same experience

No issues with the actual translations; those worked fine and this feature request only concerns the UI/UX.

**Comment by cadeyrn** [comment]
I don't want to argue against an additional checkbox in the preferencse but is the translation button in the address bar not already more visible than something that takes a very small place in the large preferences interface?

**Comment by zpangwin** [comment]
> is the translation button in the address bar not already more visible than something that takes a very small place in the large preferences interface?

Now that you mention it, and I finally noticed it, that is extremely helpful (appreciate that btw). So apparently I'm an idiot and/or blind for missing that.

That said, I guarantee you that if I missed it, that there will be others besides me that completely miss it as well. One other possibility would be either mention the address bar button in the [AMO description](https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/) or possibly even draw a red box/circle around it in one of the screenshots to call it out for the oblivious like myself.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
