### ISSUE TITLE
Add ability to choose destination language other than browser language

### ISSUE THREAD

**Issue by mdavis-xyz** [mozilla/firefox-translations#730]
### Is your feature request related to a problem? Please describe.

I'm a native English speaker trying to learn French. Because I'm trying to learn French I've changed my Firefox settings to have Firefox itself set to French, and to request the French version of websites if available.

However I'm still learning. So often I can't understand the French site I'm on. I want to give up translating myself, and use a tool to translate for me. That's what I was hoping this extension does.

However it doesn't do that.

# Desired behaviour

After installing the extension, I go into the extension settings and tell the extension that I can speak English and not French.

When I visit an English site, I am not prompted for a translation, and the page is not translated from English to French. It remains in English.

When I visit a site in French, the banner appears up the top offering to translate the page to English.

# Actual Behaviour.

I can't see a relevant option to tell the extension which languages I can speak. It just assumes I'm fluent in French and not English.

When I visit an English site, the banner appears up the top offering to translate the page to French.

When I visit a site in French, I am not prompted for a translation, and the page is not translated from French to English. It remains in French.

I am able to copy-paste individual snippets into the dialogue that appears when clicking the extension icon, which is slightly more convenient than switching tabs and pasting into Google Translate. But it is not translating the whole page as per the screenshots in the extension listing.

### Describe the solution you'd like

See above

### Describe alternatives you've considered

I don't know how else this could work.

**Comment by mdavis-xyz** [comment]
Oh, I see now. There's *two* extension icons, with very different behaviour.

![screenshot-translate](https://github.com/mozilla/firefox-translations/assets/7035647/9b01781f-230c-4d09-aa00-948042c10616)

Ok, by clicking on the icon in the address bar I can toggle translation of a particular page. Ok, great. So this extension is still usable for me.

The issue then is when to show the banner. That's currently not configurable. (Other than not showing it at all.)

**Comment by MaloneGerald** [comment]
I think I can help Firefox with the Romanian translation ....or French. #Git is open surce ...correct ? Right? ... like #OS_Linux.

**Comment by marco-c** [comment]
@MaloneGerald can you help by providing data sources or by contributing code?
