### ISSUE TITLE
Use dictionary lookup for single words

### ISSUE THREAD

**Issue by JulianWDev** [mozilla/firefox-translations#731]
### Is your feature request related to a problem? Please describe.

The translation engine is relatively competent at translating larger pieces of text, however, it struggles with single words or short sentences, which are very common on websites. Sometimes, the engine will translate what's supposed to be a single word into a sentence, or invent context that is not there. Example: the word "about" in an english website gets translated into "over het hele bedrijf" in Dutch. I've seen this behaviour with other languages as well.

### Describe the solution you'd like

When the translation engine detects that the to be translated element is only one word (or perhaps two or three, some experimentation might be necessary) it can attempt to do a simple dictionary lookup for that word. There are various open-source dictionaries that seem suited to this task. They could be downloaded together with the translation language packs. 

It seems to me this would definitely enhance the navigation experience with translation enabled, as the dictionary translations should be of higher quality.

This would also have the advantage of speeding up translation for websites, as a lot of the UI elements will consist of single words (agree, download, about, continue, etc.), and a dictionary lookup is likely to be faster than running the translation engine.

**Comment by marco-c** [comment]
Building heuristics around this will be very hard compared to just relying on improving the translation models.
E.g. sometimes when translating a single word from a language you might get multiple words in another language.
