### ISSUE TITLE
Translate button is not visible in almost all Light themes

### ISSUE THREAD

**Issue by regs01** [mozilla/firefox-translations#732]
### Describe the bug

Translate button is not visible in almost all Light themes. Only stock light theme has unreadable white font on light gray background. For all light themes from AMO the button is invisible.

### To Reproduce

Switch to light theme

### Expected behavior

Translate button should be visible

### Screenshots

<img width="131" alt="firefox_2023-06-23_19-32-30" src="https://github.com/mozilla/firefox-translations/assets/10468217/3fa0bda0-a75e-4b0c-9f78-1d470926acb7">

### System type

None

**Comment by bharathkalyans** [comment]
Attaching snapshots would be helpful @regs01

**Comment by regs01** [comment]
> Attaching snapshots would be helpful @regs01

Snapshots? Screenshots? There is a screenshot.

**Comment by bharathkalyans** [comment]
Oh, looks like I missed it. It isn't easily visible, looks like a GitHub checkbox.

**Comment by marco-c** [comment]
We are not going to make any improvements or fixes to the addon since we are now focusing on the built-in version.
If the problem is still visibile in the built-in version, let us know by filing a bug on [Bugzilla](https://bugzilla.mozilla.org/).

**Comment by regs01** [comment]
What is built-in version?

**Comment by cadeyrn** [comment]
> What is built-in version?

Firefox will get a native translation feature so that you no longer need an add-on. You can already test it in Nightly builds of Firefox. It will be the stable release of Firefox in the coming months.

**Comment by regs01** [comment]
> > What is built-in version?
> 
> Firefox will get a native translation feature so that you no longer need an add-on. You can already test it in Nightly builds of Firefox. It will be the stable release of Firefox in the coming months.

But I see there are still commits for the extension. Last is 14 hours ago. And there are over 50 issues are open. Why denying only some specific problem? Why not to shut down and archive repository at all, if it's no longer in development?

**Comment by marco-c** [comment]
The only real commit was the one to disable the addon icon if the built-in feature is enabled, which is needed so we don't show two icons.
I'm slowly closing all open issues and migrating some to Bugzilla.
