### ISSUE TITLE
Japanese language translation support

### ISSUE THREAD

**Issue by RellikJaeger** [mozilla/firefox-translations#740]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Please add Japanese language translation support

### Describe alternatives you've considered

I'm using 3rd party extensions for the Japanese language translation

### Additional context

None

**Comment by marco-c** [comment]
We are no longer maintaining the addon, but the good news is that we are bringing the feature natively in Firefox soon.
You can suggest additional languages on https://connect.mozilla.org/.

Japanese was already suggested, see https://connect.mozilla.org/t5/ideas/japanese-translate-option-in-firefox-translations/idi-p/22959. You can add your vote to it.
