### ISSUE TITLE
From external webextension

### ISSUE THREAD

**Issue by lollita** [mozilla/firefox-translations#741]
### Describe the solution you'd like

Do it is possible to istance from other external webextension: translation and Language Detection?
For example to translate a sentence?

**Comment by marco-c** [comment]
This extension is in maintenance mode, we are building the functionality as part of Firefox itself.

**Comment by lollita** [comment]
I know it, but do it is possible in Firefox itself?

**Comment by evrenesat** [comment]
I also wonder if/when [Translation component](https://bugzilla.mozilla.org/buglist.cgi?product=Firefox&component=Translation&bug_status=__open__) will be exposed to web extensions or websites? Is this already planned?
