### ISSUE TITLE
Yandex feedback form is not translated

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations#87]
1. Go to https://yandex.ru/support/connect-forms/common/feedback.html
2. Press translate with "Enable translation of forms" checked.
3. Click the form text field

Expected: 
1. The page is completely translated from Russian to English
2. Outbound translations dialogue appears

Actual:
1. The page is translated only partially and the form is not translated at all
2. Outbound translations dialogue doesn't appear

![Screen Shot 2022-02-09 at 11 50 45 AM](https://user-images.githubusercontent.com/2486505/153285744-f25f1988-2d94-47b0-9ba4-ac6cf91473a4.png)

**Comment by andrenatal** [comment]
And the reason is, as you print states, that the form is inside an `iframe`, and the current implementation does not scan `iframes`.

**Comment by andrenatal** [comment]
Maybe you can take this one @eu9ene ?

**Comment by eu9ene** [comment]
depends on #135
