### ISSUE TITLE
Content classification per item in the translation batch

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#94]
We need to be able to identify if the string content is text or html individually [here](https://github.com/mozilla/firefox-translations/blob/main/extension/controller/translation/translationWorker.js#L542) and have one ResponseOption per input item in the batch instead to the entire request.

The corresponding issue tracking this feature in engine: https://github.com/browsermt/bergamot-translator/issues/345

**Comment by abhi-agg** [comment]
This is closed via https://github.com/mozilla/firefox-translations/pull/111.
