### ISSUE TITLE
Use translation cache

### ISSUE THREAD

**Issue by jerinphilip** [mozilla/firefox-translations#96]
The translation engine provides a cache (https://github.com/browsermt/bergamot-translator/issues/201) at the sentence level. In addition, there is some experimentation and study from https://github.com/XapaJIaMnu/translateLocally/pull/75. 

For the extension, we expect this to be useful at least in the following scenarios:

1. **Recurring page elements over multiple pages** Pages like Wikipedia or news websites which users browse continuously and have some recurring across pages text (e.g. sidebars and such UI elements) that will be repeatedly translated each time. Translation (and the underlying matrix multiplications) are time-consuming. The cache would avoid some heavy computations that would occur otherwise. 
2. **Outbound translation** If the user is entering multiple sentences, then repeatedly translating the whole sentences over and over will lead to sluggishness. I experience this when I type a large text and continue to edit it at https://mozilla.github.io/translate/. The updates on the right happen for about 20 seconds after I type in, even at say 500 characters.

The cache is easy to enable - implement the bindings for cache config (two values - how many sentences to store, whether to enable or not) at WebAssembly and start configuring at JS. Please consider using the cache.

**Comment by andrenatal** [comment]
The extension creates one engine per page load in its own translationWorker, which is not shared across other tabs, so the state is not shared across multiple pages/reloads. How it would work in this case?

**Comment by andrenatal** [comment]
Or better: if there's a way to enable is only when OT is in use, then it could be fine.

**Comment by andrenatal** [comment]
Reminder to self: revisit with the secops team if it's ok to host the nmt wasm module in the background script, which would make translation happen faster. Also assess the memory usage implications of this approach.

**Comment by andrenatal** [comment]
Closed by #144
